### ISSUE TITLE
[SANDBOX] AddressContactQueue and its dead letter queue is created in default '/' vhost

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/tmail-backend#1007]
## Why

Even if we specify the vhost e.g. `sandbox`:

![Image](https://github.com/linagora/tmail-backend/assets/55171818/745830bd-3e3d-4987-9f66-ac27d3d9ceb0)

Meanwhile, the remaining contact related queues are created in the correct vhost:

![Image](https://github.com/linagora/tmail-backend/assets/55171818/a71342d5-1c34-4ae4-bc89-216937ad32cb)

This happens for `tenant-upn` or `postgres` tenants also.

We need to provide a good isolation.

## How

Try to reproduce in tests and debug.

## DoD

Fixed.

**Comment by Arsnael** [comment]
Weird I thought I did a fix regarding that, maybe still not enough

**Comment by Arsnael** [comment]
=> https://github.com/linagora/tmail-backend/pull/944

I thought that was enough to plug the vhost param to the email adress contact rabbitmq conf but maybe I missed something...

However I just managed to see that if you add the vhost in the uri, it works.

**Comment by Arsnael** [comment]
https://ci.linagora.com/linagora/lrs/saas/tools/helm-charts/tmail-backend/-/merge_requests/46

I think if we have the vhost for the normal uri, makes sense for address contact uri as well. Might affect the creation of the queue and the link. 

Anyways this works and solves the issue (keep getting conflicts these days between sandbox and other envs quorum/not quorum on that queue)

**Comment by quantranhong1999** [comment]
> Anyways this works and solves the issue (keep getting conflicts these days between sandbox and other envs quorum/not quorum on that queue)

I am more or less done with sandbox. Please feel free to override it now.

**Comment by Arsnael** [comment]
Still better to have that queue in its vhost like all the others though :)
