### ISSUE TITLE
[Bug] Leak resource at CalendarEventReplyPerformer

### ISSUE THREAD

**Issue by vttranlina** [linagora/tmail-backend#1020]
How to re-produce?

Running `com.linagora.tmail.james.MemoryLinagoraCalendarEventAcceptMethodTest` 
Log:
```
Dispose email:17:07:34.705 [ERROR] o.a.j.l.a.Disposable$LeakAwareFinalizer - Leak detected! Resource org.apache.james.server.core.MimeMessageInputStreamSource$Resource@6e500b8e was not released before its referent was garbage-collected. 
Resource management needs to be reviewed: ensure to always call dispose() for disposable objects you work with. 
Consider enabling advanced leak detection to further identify the problem.
```

# Dod 
No aware log

**Comment by vttranlina** [comment]
I still have not caught the where leak it. 
The `LifecycleUtil.dispose` already invoked after enqueue MailImpl

At the @chibenwa 's comment: https://github.com/linagora/tmail-backend/pull/970#discussion_r1521430370
> Use MimeMessageInputStreamSource

The method `MimeMessageInputStreamSource create(String key, InputStream in)` was not used in `prod` code before CalendarEvent.
Not sure if it is stable or not

**Comment by vttranlina** [comment]
Related to CalendarEvent, 
do you think we should "cache" the mimeMessage (mail template) that loads from the IO template file? And reuse it for each reply (just replace mustache when using)

**Comment by chibenwa** [comment]
> do you think we should "cache" the mimeMessage (mail template) that loads from the IO template file? And reuse it for each reply (just replace mustache when using)

IMO we can load it again each time, just call "dispose"

**Comment by vttranlina** [comment]
pr: 
- https://github.com/apache/james-project/pull/2214
- https://github.com/linagora/tmail-backend/pull/1021
