### ISSUE TITLE
JMAP - fault tolerance when Redis down 

### ISSUE THREAD

**Issue by vttranlina** [linagora/tmail-backend#1024]
Based on `james-project`  but for tmail-backend
https://github.com/linagora/james-project/issues/5175
Eg: `Email/send` method

**Comment by chibenwa** [comment]
By acting on the event bus configuration, working on this for apache/james-project` would already cover this for `linagora/tmail-backend` ?

**Comment by vttranlina** [comment]
was resolved by https://github.com/linagora/tmail-backend/pull/1026
