### ISSUE TITLE
Inlined image in signature broken in GMail

### ISSUE THREAD

**Issue by Arsnael** [linagora/tmail-backend#1027]
From https://github.com/linagora/tmail-flutter/issues/2849

GMail do not support inlined base64 image.

This concerns the way we insert inlined images in signatures for now, keep in mind this work would be bound to the identity and the way to insert images in the signature's identity.

Brain storming:
```
Session extention:
 - URI com:linagora:params:public:assets
 - publicAssetTotalSize: UnsignedInt space that can be hosted

PublicAsset JMAP objects

 - id (serverSet)
 - publicURI (serverSet)
 - size (serverSet)
 - blobId
 - identityIds: Id[]|null, default to null
 
/get 
/set create 
    front need to upload the image first
    back needs to copy the content (not just upload)
    back needs to validate the content type: `image/*`
/set destroy
/set update on identityIds

Client (Twake mail) is responsible of deleting PublicAssets with no identity associated with them.

GET (no auth) jmap.linagora.com/publicAsset/xyz
    Route would need to be added in Apisix basicAuth routes to bypass OIDC authentication
```

**Comment by vttranlina** [comment]
> GET (no auth) jmap.linagora.com/publicAsset/xyz

Should we be concerned about private data when "no auth"?  

Gmail generates a signed URL for the image with a sort expiration time. (After expiration time, you need to re-open the email or reload page one new)

**Comment by chibenwa** [comment]
The user is fully aware of the data exposed there. No auth is entirely the point.
We might generate a complex enough random string to discourage crawling attempts.

**Comment by chibenwa** [comment]
> Gmail generates a signed URL for the image with a sort expiration time. (After expiration time, you need to re-open the email or reload page one new)

Complex.

URL need to be accessed several years onto the future. and we cannot execute logic when reading the mail (like signing the url)

A signature without expiracy is of little use, and not really better than just a random enough string.

**Comment by vttranlina** [comment]
> GET (no auth) jmap.linagora.com/publicAsset/xyz
>    Route would need to be added in Apisix basicAuth routes to bypass OIDC authentication

We can directly use the public URL from S3 (OVH), then don't need to forward to `jmap.linagora.com` server

**Comment by quantranhong1999** [comment]
How about upon `Identity/set`, TMail client instead of storing image under the based64 encoded:

`"htmlSignature": "<p>my signature with image</p><p><img src=\"data:image/jpg;base64,/9j/4AAQSkZJRg...`

It uploads the image as an attachment via the upload route, gets the `blobId` returned e.g. `f72818e0-0d11-11ef-9d4e-7d1058f3d6e1_5`, uses it as the `cid`, then stores the `htmlSignature` as:

`"htmlSignature": "<p>my signature with image</p><p><img src=\"cid:f72818e0-0d11-11ef-9d4e-7d1058f3d6e1_5...`

When the TMail client sends mail: it does `Email/set` with an attachment that refers to the above image with the same `cid` e.g. here `f72818e0-0d11-11ef-9d4e-7d1058f3d6e1_5`. Then Gmail can likely load image from attachment using the `cid`.

Does that sound possible to you?

**Comment by vttranlina** [comment]
>  Then Gmail can likely load image from attachment using the cid.

How Gmail can know cid here is blobId of tmail-backend, and can fetch image data from {jmap_tmail_server}/download/{blobId}?

**Comment by vttranlina** [comment]
Bonus: Here is the email file with a picture in the signature (I sent it from Tmail to Gmail). It displays correctly in Thunderbird and Tmail but not in Gmail.
[testSignatureImage.txt](https://github.com/linagora/tmail-backend/files/15246491/testSignatureImage.txt)

**Comment by Arsnael** [comment]
multipart, I think what @quantranhong1999 is trying to propose is something similar to inline images in body using the CID (that shows in gmail)

> Does that sound possible to you?

I thought about it too, but I ain't sure. It sounds adding a lot of complexity frontend side, also when updating a signature could have an edge case lying.

Also in your example uploading the image using jmap upload route is not enough, as the upload bucket cleans up oldest files usually after reaching a certain hidden quota for the user, might need to move it to an other bucket . We would still need some way to clean that up.

Maybe the initial proposition by Benoit could still be used (to be able to manage identity images by jmap) but instead of having a public uri, we could just do as you say, including the PublicAsset as a cid.

**Comment by vttranlina** [comment]
> This way uses the sending email with the inline attachment nature of email, GMail does not know and does not need to know how TMail manages the blob.

I tried to  download the email (eml file) on the Gmail side, then saw it is a base64 image, 
`blodId` - `cid` is just a logic in tmail side,

**Comment by chibenwa** [comment]
> We can directly use the public URL from S3 (OVH), then don't need to forward to jmap.linagora.com server

This extension allow this, yes! 

Agree we can try, though current blob store is not suited for this.

I would then prefer it to be served from a distinct bucket that TMail base one (in order not to impact safety and confidentiallity of regular user data).

The current blob store is not suited for this though we can likely have a dedicated tmail component for this and use our own s3client dedicated for this use. (with lower thread resources). Or find a way to reuse the one of the S3blobStoreDAO (likely better to extract a S3ClientFactory on james side and inject it!)

**Comment by chibenwa** [comment]
@quantranhong1999 inlined attachments with CID comes with several major drawbacks:

 - 1/ The image binary data is stored on each and every email. That quickly makes for a lot of data. With the http link that's not the case.
 - 2/ Composing with CID would mean we get to reference the attachment content forever and that is hard to do! We would need to modify the `Identity` object for that. THis means only tmail would be able to use the resulting signature. With the https that's not the case: every JMAP client can use the signature, only tmail can edit it (that's ok)
  - 3/ Uploading the attachment data every time you send a mail?
  - 4/ Heavy burdon on the mobile team.
  
  I would like us to go with the https link suggestion. If fastmail do this, they already weighted the pros and cons for us.

**Comment by Arsnael** [comment]
From discussion with the team and mobile team:

- if using route to expose public uri of the image on our side: do we need some routine in the edge case that maybe for example the dns change? Like for example linagora.com => lingora.fr, what about all the existing assets with linagora.com url?
- mobile team wondering how they should proceed on their side, we think upload image via jmap upload route, then using the /set create method, from which they should get back in the response the server set field publicURI that they can use to put in an image tag with the url?
- interoperability question: what happens if we set up a signature with image with tmail client and then use an other client that does not support that extension?
- maybe we can propose an easier design? in the current one proposed, we might need two tables with cassandra: one to represent the public assets, one maybe having identityId as PK and the public assets it links to to ease the search. What about maybe having in publicAsset table just one identityId (could be part of PK with id) and rely on deduplication with the blob store? Maybe we could have duplicated data on other columns but it's small, also we don't think lot of users have multiple identities, and if maybe not often same images among signatures. That would simplify the design and allow to just have one cassandra table instead of maybe 2?
- when creating an identity, if we upload an image to the signature, identity does not exist yet... So need to create the public asset with identityIds to null, then updating it after creating the identity? Might be a bit tricky on the front side
- if using S3 public links, question raised about the cost, as you have to pay for traffic it seems? (like if I send a thousand mails with an inline signature) Tung knows it's the case with AWS service, what about OVH? Internal traffic (tmail asking for S3 blob) free, but external traffic (s3 public uri) has a cost
- miss a username column in publicAsset object (/get all assets of user for example?)
- if want to search publicAssets belonging to one identity, we might need to add a /query method as well, with IdentityId as a filter option?
- frontend side: img html tag with maybe id property set to PublicAsset id so they can fetch directly it with /get method, also making sure it's not maybe a public uri from an other website?
- implies we need a quota for those public assets per user (publicAssetTotalSize)

I think we should discuss about it with PO monday in tmail meeting to clarify all of this, as a lot of concerns have been raised

**Comment by chibenwa** [comment]
> if using route to expose public uri of the image on our side: do we need some routine in the edge case that maybe for example the dns change? Like for example linagora.com => lingora.fr, what about all the existing assets with linagora.com url?

Overkill IMO

> mobile team wondering how they should proceed on their side, we think upload image via jmap upload route, then using the /set create method, from which they should get back in the response the server set field publicURI that they can use to put in an image tag with the url?

Yes

> interoperability question: what happens if we set up a signature with image with tmail client and then use an other client that does not support that extension?

The other client would be able to use the link generated by tmail. All good.

> maybe we can propose an easier design? in the current one proposed, we might need two tables with cassandra: one to represent the public assets, one maybe having identityId as PK and the public assets it links to to ease the search. What about maybe having in publicAsset table just one identityId (could be part of PK with id) and rely on deduplication with the blob store? Maybe we could have duplicated data on other columns but it's small, also we don't think lot of users have multiple identities, and if maybe not often same images among signatures. That would simplify the design and allow to just have one cassandra table instead of maybe 2?

IMO we can...

```
PK username
CK assetId
C blobId
C contentType
```

The link can be:

`https://jmap.linagora.com/publicAsset/{accountId}/{assetId}`

Pretty sure that way it is one table.

Note: leaking the username in the URL (as accountId) is OK as I already get it from sender mail address in the mail in the first place.

> when creating an identity, if we upload an image to the signature, identity does not exist yet... So need to create the public asset with identityIds to null, then updating it after creating the identity? Might be a bit tricky on the front side

That's why I propose identityIds as a separate entity.

THe flow would be:

 - a Upload your binary data
 - b Create the public asset
 - c Create the identity
 - d Update the public asset with the identityId
 
 Note: b, c, d can be easily done in one roundtrip (one JMAP request)
 
 > if using S3 public links, question raised about the cost, as you have to pay for traffic it seems? (like if I send a thousand mails with an inline signature) Tung knows it's the case with AWS service, what about OVH? Internal traffic (tmail asking for S3 blob) free, but external traffic (s3 public uri) has a cost
 
Read costs are the same wether you proxy the read or not as far as I know...

Interested to know if we can set some limitations though...

> if want to search publicAssets belonging to one identity, we might need to add a /query method as well, with IdentityId as a filter option?

Or just list all the public assets of a user.

For the time being we can expect the cardinality to be low.

> frontend side: img html tag with maybe id property set to PublicAsset id so they can fetch directly it with /get method, also making sure it's not maybe a public uri from an other website?

(Or a HTML comment?)

**Comment by chibenwa** [comment]
> implies we need a quota for those public assets per user (publicAssetTotalSize)

Yes. Static configuration IMO is OK for this.

**Comment by chibenwa** [comment]
> I think we should discuss about it with PO monday in tmail meeting to clarify all of this, as a lot of concerns have been raised

Did I clarified things?

:-p

**Comment by Arsnael** [comment]
@team: I think the list of tickets could be: 

- ADR
- JMAP extension com:linagora:params:public:assets => field publicAssetTotalSize
- POJO PublicAsset
- PublicAsset DAO
- PublicAsset/get
- PublicAsset/set create
- PublicAsset/set destroy
- PublicAsset/set update
- Implement JMAP route {jmap_endpoint}/publicAsset/{accountId}/{assetId}
- Implement Quota for PublicAssets 
- Documentation JMAP feature


PublicAsset JMAP object:

 - id (serverSet)
 - publicURI (serverSet)
 - size (serverSet)
 - username
 - blobId
 - identityIds: Id[]|null, default to null

Cassandra table:

PK username
CK assetId
C blobId
C contentType
C identityIds (frozen set?)

Public URI (not stored, built with the response):

{jmap_endpoint}/publicAsset/{accountId}/{assetId}

Did I miss or misunderstood something? I think we can start writing tickets based on this for thursday

**Comment by quantranhong1999** [comment]
> @team: I think the list of tickets could be:

Missing the JMAP specs ticket and repository tickets IMO.

**Comment by Arsnael** [comment]
> Missing the JMAP specs ticket and repository tickets IMO.

JMAP spec that's pretty much the jmap doc for me

Repository I would likely put that with DAO (just wasn't precise enough) but do you think it should be separated?

**Comment by quantranhong1999** [comment]
> Repository I would likely put that with DAO (just wasn't precise enough) but do you think it should be separated?

Normally we do: 
- Repository + memory implementation
- Cassandra implementation
- now Postgress implementation too

I think we can put the DAO in the same repository ticket.

**Comment by Arsnael** [comment]
You are right, updated the list

**Comment by vttranlina** [comment]
Related to OVH S3 public traffic price:

On the  OVH site don't write details exactly the price, it just 
```
Outbound public network traffic is included in the price of instances on all locations, except the Asia-Pacific region (Singapore and Sydney). In both regions, 1 TB/month of outbound public traffic is included for each Public Cloud project. Beyond this quota, each additional GB of traffic is charged. Inbound network traffic from the public network is included in all cases and in all regions.
```
Ref : https://www.ovhcloud.com/en/public-cloud/prices/

I asked  @ducnm0711 ,  We have to try it out to measure it

**Comment by Arsnael** [comment]
Dont think we should think too much about it for now though, but thanks for having a look

**Comment by Arsnael** [comment]
Coming back on what I said, likely better to have a dedicated ticket for jmap specs publicasset
