### ISSUE TITLE
PublicAssetRepository + memory implementation

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/tmail-backend#1039]
# Why
We need storage APIs for PublicAsset.

# How
### POJO
Transform the JMAP object:
```
id (serverSet)
publicURI (serverSet)
size (serverSet)
blobId
identityIds: Id[]|null, default to null
```

Notes: I removed `username` from the object as I think it is useless to expose the username to the client side. Meanwhile, in DB we still need to store the user owns the asset.

Introduce in `tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/model` something like:

```scala
package com.linagora.tmail.james.jmap.model

import java.net.URI
import java.util.UUID

import org.apache.james.blob.api.BlobId
import org.apache.james.jmap.api.model.IdentityId
import org.apache.james.jmap.api.model.Size.Size

case class PublicAssetId(value: UUID)

case class PublicURI(value: URI) extends AnyVal

case class PublicAssetCreationRequest(blobId: BlobId)

case class PublicAsset(id: PublicAssetId,
                       publicURI: PublicURI,
                       size: Size,
                       blobId: BlobId,
                       identityIds: Seq[IdentityId])

```

### PublicAssetRepository

```java
public interface PublicAssetRepository {
    Publisher<PublicAsset> create(Username username, PublicAssetCreationRequest creationRequest);

    Publisher<Void> update(Username username, Set<IdentityId> identityIds);

    Publisher<Void> revoke(Username username, PublicAssetId id);

    Publisher<Void> revoke(Username username);

    Publisher<PublicAsset> get(Username username, Set<PublicAssetId> ids);

    Publisher<PublicAsset> list(Username username);
}
```

# DoD
Memory implementation + contract tests.

**Comment by quantranhong1999** [comment]
I think this POJO should go with the repository ticket.

**Comment by chibenwa** [comment]
agree

**Comment by vttranlina** [comment]
Do we need a column for the storage Assets metadata?

eg:
For storage `Content-Type`

**Comment by quantranhong1999** [comment]
> Do we need a column for the storage Assets metadata?
eg:
For storage Content-Type

That is what I doubted too. If we need it, then yes.

**Comment by quantranhong1999** [comment]
> Isn't that info in the attachment table, that you can get with the blob_id?

Hmm, that is true, but it is just a pure blob and has nothing to do with attachment yet.

**Comment by Arsnael** [comment]
My bad, uploadsv2 table has the metadata of the upload with content type and should be enough to verify it upon /set create

**Comment by Arsnael** [comment]
@chibenwa actually no need of publicURI to be stored on db right, as we can build it up with accountId and assetId?

However, do we:
- return an absolute path, in which case we might want a prefix conf in jmap.properties (cause maybe we want to access directly from jmap endpoint, maybe through apisix because jmap endpoint is not exposed outside the cluster, etc)
- return a relative path, and it's frontend's job to put the prefix?

**Comment by Arsnael** [comment]
Still maybe need contentType for when we return to the front the image from object storage?

**Comment by Arsnael** [comment]
Need a dedicated bucket for storing PublicAsset or can use the default one?

**Comment by chibenwa** [comment]
> Need a dedicated bucket for storing PublicAsset or can use the default one?

Default one is OK?

**Comment by vttranlina** [comment]
pr https://github.com/linagora/tmail-backend/pull/1055
