### ISSUE TITLE
Cassandra implementation for PublicAssetRepository

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/tmail-backend#1040]
## Why 
We need Cassandra's implementation for `PublicAssetRepository`.  

## Requires
- https://github.com/linagora/tmail-backend/issues/1039

## How
- Table structure

```
PK username TEXT
CK assetId UUID
C blobId TEXT
C contentType TEXT
C identityIds Frozen Set<TEXT>
```

Do we really need `contentType` though? If yes, likely we need to add `contentType` to the `PublicAsset` object.

## DoD 
Pass contract tests.

**Comment by Arsnael** [comment]
No need contentType

**Comment by quantranhong1999** [comment]
https://github.com/linagora/tmail-backend/pull/1058
