### ISSUE TITLE
Postgres implementation for PublicAssetRepository

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/tmail-backend#1041]
## Why 
We need Postgres's implementation for `PublicAssetRepository`.  

## Requires
- https://github.com/linagora/tmail-backend/issues/1039

## How
- rebase on the master branch to get the Repository interface.
- Table structure:

```sql
CREATE TABLE public_assets (
    username TEXT NOT NULL,
    asset_id UUID NOT NULL,
    blob_id TEXT NOT NULL,
    content_type TEXT,
    identity_ids TEXT[] ,

    PRIMARY KEY (username, asset_id)
);
```
A dedicated index for the `username` column.

## DoD 
Pass contract tests.

**Comment by Arsnael** [comment]
Wasn't the PK username and asset_id (that I think could be just id?) a CK?

**Comment by quantranhong1999** [comment]
> Wasn't the PK username and asset_id a CK?

I do not get your question. This is PostgreSQL :p

**Comment by Arsnael** [comment]
Nevermind :) was end of the day and I wrote too many tickets, forget this^^

**Comment by Arsnael** [comment]
Missing size

**Comment by quantranhong1999** [comment]
https://github.com/linagora/tmail-backend/pull/1068
