### ISSUE TITLE
User deletion: PublicAsset

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/tmail-backend#1043]
## Why

Upon user deletion, related PublicAsset(s) should be cleaned.

Upon username change, related PublicAsset(s) should be migrated.

## How

- Implement `UsernameChangeTaskStep` and `DeleteUserDataTaskStep`
- Guice binding

## DoD
Unit tests + integration tests (for guice binding)
Notice to Guice binding for postgres-app as well.

**Comment by Arsnael** [comment]
Nice catch, was missing

**Comment by quantranhong1999** [comment]
Skip username change migration for public asset cf https://github.com/linagora/james-project-private/pull/810#discussion_r1607978710

**Comment by hungphan227** [comment]
pr https://github.com/linagora/tmail-backend/pull/1065
