### ISSUE TITLE
Implement Quota for PublicAssets 

### ISSUE THREAD

**Issue by vttranlina** [linagora/tmail-backend#1044]
## Why
Control resource when the user uploads PublicAsset
Epic: https://github.com/linagora/tmail-backend/issues/1027

## How
- Create 2 new Events:

```
case class TmailPublicAssetAddedEvent(eventId: EventId, username: Username, id: PublicAssetId, size: Size) extends TmailContactUserEvent {}

case class TmailPublicAssetDeletedEvent(eventId: EventId, username: Username, id: PublicAssetId, size: Size) extends TmailContactUserEvent {}
```

- Dispatch the corresponding event when the user invokes JMAP PublicAsset/set, PublicAsset/destroy successfully
- Create PublicAssetEventListener, try to hang the PublicAsset event, then update the current quota. 
```
class PublicAssetEventListener @Inject()(UserQuotaRootResolver: UserQuotaRootResolver, currentQuotaManager: CurrentQuotaManager) extends ReactiveGroupEventListener
```

## Dod 
Write PublicAssetEventListenerIntegrationTest

**Comment by quantranhong1999** [comment]
How about updating the quota synchronously?

**Comment by Arsnael** [comment]
I believe yes, I would expect something similar to upload quota, where we seem to update the quota right after the upload in the reactive pipeline, no need to dispatch events

**Comment by chibenwa** [comment]
> How about updating the quota synchronously?

+1

We are purely in the jmap stack, not event for this!

**Comment by Arsnael** [comment]
+ having error handling on /set create when quota is exceeded.

**Comment by hungphan227** [comment]
pr https://github.com/linagora/tmail-backend/pull/1071
