### ISSUE TITLE
Implement JMAP route to get content of the public asset

### ISSUE THREAD

**Issue by vttranlina** [linagora/tmail-backend#1045]
## Why 
Epic: https://github.com/linagora/tmail-backend/issues/1027
When a client (e.g., web browser, mobile app) requests the content of a public asset, the Tmail JMAP server needs to serve that content.

## How

- Create a new `PublicAssetRoutes` class with the following implementation:

```scala
class PublicAssetRoutes(publicAssetRepository: PublicAssetRepository,
                        blobResolvers: BlobResolvers) extends JMAPRoutes {

  override def routes(): Stream[JMAPRoute] = Stream.of(
    JMAPRoute.builder()
      .endpoint(new Endpoint(HttpMethod.GET, s"/publicAsset/{$accountId}/{$assetId}"))
      .action((request, response) => getAsset(request, response))
      .corsHeaders())

  private def getAsset(request: HttpServerRequest, response: HttpServerResponse): SMono[Unit] = {
    // checking if accountId and assetId are existing
    // if not, return 404
    // else, using blobResolvers to get the blob of the asset
    // then apply the blob to the response
  }
}
```

Note that this is a public endpoint, so authentication is not required.

- Bind `PublicAssetRoutes` to `JMAPRoutes` using `Guice`:
```
Multibinder.newSetBinder(binder, classOf[JMAPRoutes])
    routes.addBinding().to(classOf[PublicAssetRoutes])
```

- Write integration tests.

## Dod 
- Tests pass.
- Documentation.

Ref: 
[LinagoraServicesDiscoveryRoutes](https://github.com/linagora/tmail-backend/blob/78af34f4700201b965e78b4651ae1993c69d22fb/tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/service/discovery/LinagoraServicesDiscoveryRoutes.scala#L75)

[DownloadRoutes](https://github.com/apache/james-project/blob/fd83dae0bf5b626c6d0276523307ec1816f48b3e/server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/routes/DownloadRoutes.scala#L246)

**Comment by chibenwa** [comment]
> using blobResolvers to get the blob of the asset

No. 

Else lookup the publiczAsset repository and read the blob into the blobStore.

**Comment by quantranhong1999** [comment]
`/publicAsset/{$accountId}/{$assetId}"`

We can not infer `username` from `accountId` (1 way hashing).

Is it ok to expose the username in the URI e.g. `/publicAsset/{$username}/{$assetId}"`?

**Comment by quantranhong1999** [comment]
> Is it ok to expose the username in the URI e.g. /publicAsset/{$username}/{$assetId}"?

I think this is ok:
- the recipient got the username of the sender anyway
- Our code is public. If anyone really wants to do an exploration attack, they know how to hash `username` to `accountId`, therefore using `accountId` won't be much safer.
- This is a "public" route/feature already, so leaked public resources seem to be acceptable to me.

**Comment by Arsnael** [comment]
Good point... Or what about more simple, just assetId is enough? ` /publicAsset/{$assetId}` ? After all, asset ids are unique, the uri is public, no need auth...

**Comment by quantranhong1999** [comment]
> Good point... Or what about more simple, just assetId is enough?  /publicAsset/{$assetId} ? After all, asset ids are unique, the uri is public, no need auth...

Hmm, our repository API is relying on username though. Query only by `assetId` is not visible.

**Comment by vttranlina** [comment]
If that, we need one more api for query by one PublicAssetId parameter
Look like needing one more Cassandra table

**Comment by Arsnael** [comment]
You are right. Ok witht he username then

**Comment by quantranhong1999** [comment]
https://github.com/linagora/tmail-backend/pull/1062
