### ISSUE TITLE
Update apisix configuration for get public assets endpoint

### ISSUE THREAD

**Issue by vttranlina** [linagora/tmail-backend#1046]
## Why
epic: https://github.com/linagora/tmail-backend/issues/1027
When the Tmail JMAP server is behind Apisix, we need to update the Apisix configuration to not require authentication for requests to the Get public asset endpoint.

The unrestricted endpoint is `/publicAsset/{$accountId}/{$assetId}`.

Ref: https://github.com/linagora/tmail-backend/issues/1045

**Comment by hungphan227** [comment]
+helm

**Comment by quantranhong1999** [comment]
docker compose demo part: https://github.com/linagora/tmail-backend/pull/1072

**Comment by quantranhong1999** [comment]
I reopen this as there is Helm chart part left and likely production change too.

**Comment by chibenwa** [comment]
Oh sorry

**Comment by quantranhong1999** [comment]
> Oh sorry

No problem ^^

**Comment by quantranhong1999** [comment]
> docker compose demo part: https://github.com/linagora/tmail-backend/pull/1072

I realize that we need to support other origins and not just `tmail.linagora.com` for example: https://github.com/linagora/tmail-backend/pull/1075

Otherwise other website may not be able to access the public asset.

**Comment by quantranhong1999** [comment]
helm apisix part: https://ci.linagora.com/linagora/lrs/saas/deployments/tmail/emaily-staging-apps/-/merge_requests/41

**Comment by quantranhong1999** [comment]
for the `tmail.linagora.com` part cc @Arsnael Can you do a pair with me maybe on Thursday? I don't want to touch prod alone :D

**Comment by quantranhong1999** [comment]
added the APISIX route on prod
