### ISSUE TITLE
Documentation JMAP PublicAsset feature

### ISSUE THREAD

**Issue by vttranlina** [linagora/tmail-backend#1047]
Document for Jmap methods: PublicAsset/get, PublicAsset/set create, update, PublicAsset/destroy

Location: [docs/modules/ROOT/pages/tmail-backend/jmap-extensions](https://github.com/linagora/tmail-backend/tree/8084bd34932647099b3cfd80fc7ade1e69c5768b/docs/modules/ROOT/pages/tmail-backend/jmap-extensions)

**Comment by quantranhong1999** [comment]
https://github.com/linagora/tmail-backend/pull/1069
