### ISSUE TITLE
[PublicAsset] PublicAsset/set create JMAP method

### ISSUE THREAD

**Issue by Arsnael** [linagora/tmail-backend#1048]
The /set create JMAP method for PublicAsset takes following fields as request:

- blobId : `Id` the blobId it refers to in the upload bucket 
- identityIds: `Id[]` the identities this asset is attached to. Can be null. If omitted, considered as null

The blobId needs to refer to a blob that has been previously uploaded in the upload bucket via the jmap upload route. We need to check that the blob exists, need to copy the content into the bucket for public assets and validate that the content is an image.

Request:

```
{
  "using": ["urn:ietf:params:jmap:core", "com:linagora:params:public:assets"],
  "methodCalls": [
    [
      "PublicAsset/set", {
        "accountId": "29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6",
        "create": {
          "4f29": {
            "blobId": "1234",
            "identityIds": ["12", "34"]
          }
        }
      }, "0"
    ]
  ]
}
```

Response:

```
{
  "sessionState": "2c9f1b12-b35a-43e6-9af2-0106fb53a943",
  "methodResponses": [
    ["PublicAsset/set", {
      "accountId": "29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6",
      "newState": "2c9f1b12-b35a-43e6-9af2-0106fb53a943",
      "created": {
        "4f29": {
          "id": "123456",
          "publicURI": "http://jmap/accountid/assetid",
          "size": 65432
        }
      }
    }, "0"]
  ]
}
```

DoD: integration tests

**Comment by chibenwa** [comment]
identityIds need to be validated

**Comment by vttranlina** [comment]
draft pr https://github.com/linagora/tmail-backend/pull/1057
