### ISSUE TITLE
[PublicAsset] PublicAsset/set update JMAP method

### ISSUE THREAD

**Issue by Arsnael** [linagora/tmail-backend#1050]
classic set update jmap method. Only identityIds can be updated

Request:

```
{
  "using": ["urn:ietf:params:jmap:core", "com:linagora:params:public:assets"],
  "methodCalls": [
    [
      "PublicAsset/set", {
        "accountId": "29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6",
        "update": {
          "4f29": {
            "identityIds": ["12", "34", "56"]
          }
        }
      }, "0"
    ]
  ]
}
```

Response:

```
{
  "sessionState": "2c9f1b12-b35a-43e6-9af2-0106fb53a943",
  "methodResponses": [
    ["PublicAsset/set", {
      "accountId": "29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6",
      "newState": "2c9f1b12-b35a-43e6-9af2-0106fb53a943",
      "updated": {
        "4f29": null
      }
    }, "0"]
  ]
}
```

DoD: integration tests

**Comment by chibenwa** [comment]
We need to enforce that:

 - When I update with an identity ID that do not exist, the operation is rejected.
 - When I remove an identity, other identity ids shall be removed in the background?  (other task?)

**Comment by vttranlina** [comment]
> When I remove an identity, other identity ids shall be removed in the background? (other task?)

Task created for it
- https://github.com/linagora/tmail-backend/issues/1059
- https://github.com/linagora/james-project/issues/5198

**Comment by vttranlina** [comment]
pr https://github.com/linagora/tmail-backend/pull/1063
