### ISSUE TITLE
[ICS reply] Issue with Outlook

### ISSUE THREAD

**Issue by Arsnael** [linagora/tmail-backend#1064]
Outlook still does not recognize our reply form the jmap extension to a calendar event, as a result, no update is made on outlook calendar with the attendance of the TMail participant.

After checking around and testing a bit myself, this is what I found. I compared with inviting a google account as well, to see the differences.

ics files between gmail and tmail look nearly identical. I think ours is genuine, I don't think this is our problem

Then browsing the net I found this: https://stackoverflow.com/questions/72812057/ics-file-sended-to-outlook-are-not-reconized-as-event

Just being less than 2 years old and looking exactly like the problem we are having. Seems you need to add in the content-type header of the calendar ics attachment method=REPLY as well.

I checked the source file of the email sent by gmail, that's what they do:

Content-Type: text/calendar; charset="UTF-8"; method=REPLY

I checked the source of email sent by TMail and it's missing:

Content-Type: text/calendar; charset=UTF-8

My 2 cents: we need to add method=REPLY in the content-type header of the ics attachment file when doing the reply answer.

Find a way to do this, and when it's merged, upgrade tmail on prod with latest release and this patched change to see if it solves the issue, and verify that we send the correct content-type header

**Comment by chibenwa** [comment]
+1 nice diagnostic! Should be easy to fix now ;-)

On Gmail reply is there a text/calendar part? On tmail reply?

**Comment by chibenwa** [comment]
Please post the GMail EML as a reference too...

**Comment by Arsnael** [comment]
There is a text/calendar part on both yes

Gmail eml:

[gmail-ics-reply.eml.zip](https://github.com/linagora/tmail-backend/files/15433179/gmail-ics-reply.eml.zip)

**Comment by Arsnael** [comment]
https://github.com/linagora/tmail-backend/pull/1067

**Comment by Arsnael** [comment]
I wanted to try to deploy it on prod with a patch so the frontend team could test it, but it's a custom image from @chibenwa and I am not sure what the patches on latest release are about

So will put on hold for now.

**Comment by chibenwa** [comment]
Please go ahead

**Comment by Arsnael** [comment]
Tested. Works on my end, the reply is recognized by Outlook and status is updated into their calendar.
