### ISSUE TITLE
Implement change email addresses for TeamMailbox

### ISSUE THREAD

**Issue by vttranlina** [linagora/tmail-backend#1076]
When username change ensures new username still can access the old teamMailbox

Code looks like:
`class TeamMailboxUsernameChangeTaskStep @Inject()(repository: TeamMailboxRepository) extends UsernameChangeTaskStep` 

it will similar with what we did in JmapSettingsUsernameChangeTaskStep, LabelUsernameChangeTaskStep

**Comment by chibenwa** [comment]
I think this is covered by ACL changes upon user-rename but yes writing a test does not hurt for sure!

**Comment by chibenwa** [comment]
CF https://github.com/linagora/tmail-backend/pull/1133

As anticipated, current username migration covers the use case. I added the test case and no extra development is needed.
