### ISSUE TITLE
Cannot invoke \"net.fortuna.ical4j.model.property.Method.getValue()\" because the return value of \"net.fortuna.ical4j.model.Calendar.getMethod()\" is null

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-backend#1080]
### Description of the bug

server-fail :red_circle: 

### Reproduction Steps

[Calendar invite.ics.txt](https://github.com/user-attachments/files/15514571/Calendar.invite.ics.txt)

### Expected result

I expect a nicer method level failure.

### Definition of done

Explicit tests with this ICS...

[Calendar invite.ics.txt](https://github.com/user-attachments/files/15515080/Calendar.invite.ics.txt)

**Comment by chibenwa** [comment]
Idem check what happens when answering an event with no organizers. With no attendee.

**Comment by quantranhong1999** [comment]
https://github.com/linagora/tmail-backend/pull/1081
