### ISSUE TITLE
[TeamMailbox] Refactor webadmin routes on team mailbox member management

### ISSUE THREAD

**Issue by Arsnael** [linagora/tmail-backend#1086]
Refactor webadmin routes on team mailbox member management to take into account the new role field of a member. Reminder that the role of a manager is symbolized by the user getting the right `a` on the tyeam mailbox.

- Showing roles when listing team mailbox members:

```
curl -XGET http://ip:port/domains/domain.tld/team-mailboxes/marketting/members

[
  {
     "username": "bob@domain.tld",
     "role": "manager"
  },
  {
     "username": "alice@domain.tld",
     "role": "member"
  },
...
]
```

-  Add new manager or promote existing user with role manager:

```
curl -XPUT http://ip:port/domains/domain.tld/team-mailboxes/marketing/members/bob@domain.tld?role=manager
```

- Add new member or unpromote existing manager

```
curl -XPUT http://ip:port/domains/domain.tld/team-mailboxes/marketing/members/bob@domain.tld?role=member
```

Absence of the query param `role` will default to current behavior, adding a user with role member to the team mailbox.

Refactor as well the tests, and the tests should pass with the new model

Dont forget to readapt the webadmin doc in consequence as well

**Comment by quantranhong1999** [comment]
We need webadmin docs changes too.

**Comment by hungphan227** [comment]
pr https://github.com/linagora/tmail-backend/pull/1105
