### ISSUE TITLE
[TeamMailbox] Capability object for new jmap TeamMembers extension

### ISSUE THREAD

**Issue by Arsnael** [linagora/tmail-backend#1089]
Introduce the JMAP common capability object "com:linagora:params:team:members"

The object is empty.

Do the Guice bindings in CapabilityFactory

**Comment by chibenwa** [comment]
Isn't the teamMailbox capability enough? WHy a new capability is needed?

**Comment by quantranhong1999** [comment]
Hmm likely `com:linagora:params:jmap:team:mailboxes` is already enough.

**Comment by Arsnael** [comment]
Fair I forgot we had it already, with a revoke access method.
