### ISSUE TITLE
[TeamMailbox] Members/set JMAP method

### ISSUE THREAD

**Issue by Arsnael** [linagora/tmail-backend#1090]
Request:

```
[
    "Members/set",
    {
        "accountId": "xyz",
        "update": {
            "team-mailbox-name"; {
                "member/cedric@domain.tld": {"role":"member"},
                "member/alice@domain.tld": null
            }
        }
    }
    "#0
]   
```

Response:

```
[
    "Members/set",
    {
        "updated": {
            "team-mailbox-name": null
        }
    },
    "#0
]
```

Notes:
- only a manager can use the /set method
- a manager can promote other managers, but can't unpromote existing managers
- only partial update support (a full reset support would be problematic, with the can't promote/unpromote managers case)

DoD: Integration tests

**Comment by chibenwa** [comment]
> a manager can't promote/unpromote other managers, it can only add/remove members

If you have `a` right in theory you can act as the owner thus promoting other people too, at least considering IMAP.

I think we could start implementing it this way...

**Second question** as a member can I use this to remove me from the team mailbox? (leave?)

**Comment by quantranhong1999** [comment]
> Second question as a member can I use this to remove me from the team mailbox? (leave?)

It sounds like the same use case of `TeamMailbox/revokeAccess` (Allows user to revoke his access to a team mailbox which he is part of without having to ask an admin to do such an action.)

**Comment by Arsnael** [comment]
> Second question as a member can I use this to remove me from the team mailbox? (leave?)

There is already a jmap method for that, the `TeamMailbox/revokeAccess` method?

> If you have a right in theory you can act as the owner thus promoting other people too, at least considering IMAP.

I don't know, that could lead to abuses out of webadmin control..? I'm not too sure for this case

**Comment by chibenwa** [comment]
Well the use case is allow to promote other managers without bothering the admin. 
Similar to gitlab...

> There is already a jmap method for that, the TeamMailbox/revokeAccess method?

Very true. Sorry I forgot...

**Comment by Arsnael** [comment]
> Well the use case is allow to promote other managers without bothering the admin.

Ok. We agree it shouldnt be able to unpromote though right?

**Comment by chibenwa** [comment]
> Ok. We agree it shouldnt be able to unpromote though right?

Unsure, we can start by forbiding unpromote first.

**Comment by hungphan227** [comment]
@Arsnael is this api used to update multiple team mailboxes at once?

**Comment by Arsnael** [comment]
By jmap /set method definition, yes. He needs to be manager of all the mailboxes being updated though

**Comment by hungphan227** [comment]
pr https://github.com/linagora/tmail-backend/pull/1114
