### ISSUE TITLE
Object storage: experiment with Object lock

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-backend#1103]
## How?

Ensure "blobid list is enabled"

Start a local tmail server with a test bucket on OVH configured with object lock on.

Ensure you can send one mail to several local recipients.

## Why?

Given a 30 deduplication period we could also enforce at the data layer a non deletion for 30 days using that feature.

Idem, it could be usefull for backup buckets...

**Comment by vttranlina** [comment]
My experiment

- [x] Ensure "blobid list is enabled"

- [x] Start a local tmail server with a test bucket on OVH configured with object lock on.

Note: I replaced OVH with a Minio local container for easier testing.

- [x] Ensure you can send one mail to several local recipients.

Yes: it works normal :green_heart:

__________
Detail
#### Source code test:
- tmail-backend: https://github.com/linagora/tmail-backend/commit/17fafab562d909a77970d40a89622f222608bee8
- james-project: https://github.com/apache/james-project/commit/6446762f3d57c1b8edc233b1b089f83b58662cea 
(I directly modified the createBucket method in S3BlobStoreDAO)

test case `com.linagora.tmail.james.ObjectLockTest#sendMailShouldSucceed` succeed

- Verified that Object Locking was enabled for the bucket using the WebAdmin console![image](https://github.com/linagora/tmail-backend/assets/81145350/de916e51-1db5-427c-92dd-468a5171db45)

**Comment by vttranlina** [comment]
The process is more complicated than I initially thought.

The S3 API (MinIO) supports two object lock modes:

- **Governance** mode: The object can be permanently deleted by the root user.
- **Compliance** mode: The object cannot be permanently deleted, even by the root user.

The object lock feature and versioning feature were used simultaneously. The "object lock" is designed to prevent permanent deletion of objects. When a normal delete object request is made, it still succeeds (HTTP response returns 204). In reality, MinIO marks that object with a "deleted flag" (creating a new version).

> Can we specify a time for which the lock is held?

Yes, we can.

> Did you try to delete the object using S3 APIs while the lock was effective?

During the "lock time," we cannot permanently delete the object. For example:

`curl --location --request DELETE 'http://172.20.0.2:9000/my-bucket3/my-object-key?versionId=b4e183c9-25f6-4d86-a2fc-74b9341fa293'
`
=> This request will fail.

`curl --location --request DELETE 'http://172.20.0.2:9000/my-bucket3/my-object-key'` 

=> This request will succeed.

**Comment by chibenwa** [comment]
Ok cool so it can basicaly work as a safety belt for S3 tooling.
