### ISSUE TITLE
Release tmail-backend 0.10.2

### ISSUE THREAD

**Issue by Arsnael** [linagora/tmail-backend#1116]
So that we can benefit from all the lib upgrades done not long ago on james and tmail

- [x] Tag release 0.10.2-rc1 
- [x] changelog
- [x] deploy sandbox
- [x] perf tests
- [x] deploy preprod
- [ ] QA tests
- [x] Tag final release 0.10.2
- [x] Update notion pages for tmail-backend release log and features tracking (https://www.notion.so/linagora/Back-end-s-release-note-cb529c89d588492aac5ba1f76c0cd494 and https://www.notion.so/linagora/Backend-features-support-2e077cb3f00443c9a8154f0fdc954daf)
- [x] deploy prod

**Comment by Arsnael** [comment]
* upn: https://ci.linagora.com/linagora/lrs/saas/deployments/tmail/emaily-staging-apps/-/merge_requests/43
* sandbox: https://ci.linagora.com/linagora/lrs/saas/deployments/tmail/sandbox-emaily-apps/-/merge_requests/20

**Comment by Arsnael** [comment]
Compared to previous release: https://github.com/linagora/james-project-private/issues/806#issuecomment-2147035487

# imap

![Image](https://github.com/linagora/tmail-backend/assets/9005025/1228b2af-0d08-46de-817d-cf766b446a2a)

Much better perfs overall. I remember last time results were a bit odd. Dont know if was unlucky (maybe issues with ovh platform) or if libs upgrades and few other changes made a difference here.

Looks good overall

# jmap

![Image](https://github.com/linagora/tmail-backend/assets/9005025/7f4e0035-7ebd-43b2-84b2-200eabd74616)

Similar perfs, except for submit emails that is twice better in p99 (???) Not sure how but more than welcome... Or maybe because I kicked out of the user list user50, that has reached its quota, and it makes everything smoother?

Anyways, looking good.

**Comment by Arsnael** [comment]
Changelog: https://ci.linagora.com/linagora/lgs/software-linagora-com-website/-/merge_requests/53

**Comment by Arsnael** [comment]
Good for prod lng deployment IMO

**Comment by chibenwa** [comment]
FYI I will prepare a deployment for CNB as well

**Comment by Arsnael** [comment]
Deployed on prod
