### ISSUE TITLE
Fix migration for classic queues

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-backend#1119]
### Description of the bug

Fatal error while starting James","context":"default","exception":"com.rabbitmq.client.ShutdownSignalException: channel error; protocol method: #method<channel.close>(reply-code=406, 

reply-text=PRECONDITION_FAILED - inequivalent arg 'x-queue-version' for queue 'emailAddressContactEvent-dead-letter-queue'
 in vhost 'cnb_tmail': received the value '2' of type 'signedint' but current is none
 
 I need an option not to use this parameter when starting james.

### Reproduction Steps

Use classic queues. Like preprod?

### Expected result

Start without failure.

**Comment by quantranhong1999** [comment]
"If you want to stick with the older RabbitMQ 
versions and avoid this breaking change, you could set the JVM property `fallback.classic.queues.v1` to `true` (defaults to `false`)."

**Comment by chibenwa** [comment]
We then need to add the option in helm charts.

**Comment by chibenwa** [comment]
Can it be done monday?

**Comment by quantranhong1999** [comment]
> Can it be done monday?

Yes, I will take care of it.

**Comment by chibenwa** [comment]
I found a way to do this (jvmExtraProperties)

**Comment by Arsnael** [comment]
> Use classic queues. Like preprod?

FYI Preprod is using quorum queues i believe.

Note that I did the fallback to v1 classic queues on prod lng when deployed the latest release, as I didn't want to disturb much things back then
