### ISSUE TITLE
CalendarEvent reply: can not reply when user is invited via mailing list

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/tmail-backend#1121]
### Description of the bug

Given I received an event invitation via the mailing list `vnstaff@linagora.com`:

![Image](https://github.com/linagora/tmail-backend/assets/55171818/255a7771-b3da-4c2c-9a21-063925089f8b)

I as `hqtran@linagora.com` can not reply to the invitation with the error:

```json
{
    "sessionState": "2c9f1b12-b35a-43e6-9af2-0106fb53a943",
    "methodResponses": [
        [
            "CalendarEvent/maybe",
            {
                "accountId": "8e1534a48ceb6a660b23b18d0de5fba066b2179de5872d4426f90a2cc931095d",
                "notMaybe": {
                    "494419f0-3dcb-11ef-a845-bb314806fd1f_5": {
                        "type": "invalidPatch",
                        "description": "Can not reply when not invited to attend"
                    }
                }
            },
            "c0"
        ]
    ]
}
```

### Reproduction Steps

Try to reply the next OpenTechTalk invitation.

### Expected result

The user should be able to reply to the invitation, as he was actually invited (via the mailing list).

### Context

TMail prod (0.10.1.2)

cc @hoangdat

**Comment by quantranhong1999** [comment]
Solution: Upon checking if the user is invited, we should check if there is any mailing list/alias in the ATTENDEE, and if it contains the user?

Worst case: relaxing allows the user to reply freely?

**Comment by vttranlina** [comment]
not sure it is a bug or "feature"

**Comment by chibenwa** [comment]
![image](https://github.com/linagora/tmail-backend/assets/6928740/061e2b93-5b39-4f50-9dbe-c892a8cdae22)

GMail behaviour

=> it is a feature

**Comment by vttranlina** [comment]
fix pr https://github.com/linagora/tmail-backend/pull/1123
