### ISSUE TITLE
[MU] Make IMAP/SMTP impersonation work with THunderbird

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-backend#1132]
### What

secretary@gov.mu should manage emails of minister@gov.mu

She needs to access minister mailbox with her own password.

Impersonation of PLAIN AUTH (`minister\0secretary\0secret`) is not supported by MUA.

### How

Work around existing auth syntax to convey the delegation meaning.

Proposition:  use `secretary+minister@gov.mu` as a login of PLAIN AUTH to convey the meaning *secreatary authenticate with her password and then accesses minister@gov.mu account*.

### Implemetation

Write a custom `TMailLoginProcessor` for IMAP in Twake mail implementing this logic.

Define a `TmailImapPackage` reusing `DefaultNoAuth`.

Write a custom `TMailAuthCmdHandler` for SMTP in Twake mail implementing this logic.

Write a `TmailCmdHandlerLoader` replacing AuthCmdHandler in CoreCmdHandlerLoader. 

Using configuration for using `TmailCmdHandlerLoader` and `TmailImapPackage` is OK. No need to alter exising guice bindings.

### Definition of dome

 - [ ] Memory integration tests of this authentication method
 - [ ] Video showing it working with thunderbird

**Comment by vttranlina** [comment]
- [ ] IMAP 
WIP: https://github.com/linagora/tmail-backend/pull/1137

**Comment by chibenwa** [comment]
Dont forget to push PR before the weekend nheee

**Comment by vttranlina** [comment]
IMAP and SMTP code implementation + Video demo with Thunderbird: https://github.com/linagora/tmail-backend/pull/1137
