### ISSUE TITLE
Enable multithreading for Redis

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/tmail-backend#1139]
## Why

Redis 6 upper supports multithread, but Redis uses only a single thread by default.

We can enable multithreaded for Redis to get better performance.

Claimed by Redis configuration: `Using I/O threads it is possible to easily speedup two times Redis without resorting to pipelining nor sharding of the instance.` cf https://raw.githubusercontent.com/redis/redis/7.2/redis.conf

## How

- Try configuration:
```
io-threads 4
io-threads-do-reads yes
```

And performance test Redis e.g. using the [`redis-benchmark` tool ](https://redis.io/docs/latest/operate/oss_and_stack/management/optimization/benchmarks/).

And maybe even do a performance test TMail with Redis Event Bus.

If the result is good we can follow up by applying this configuration for our Redis deployments.

**Comment by quantranhong1999** [comment]
Notes: this likely would not benefit the MU deployment though, as we plan to use a single CPU core VM for Redis.

**Comment by vttranlina** [comment]
> Redis uses only a single thread by default.

Q: do you know why?
any pros/cons of this?

**Comment by quantranhong1999** [comment]
> Q: do you know why?

From what I read on Redis configuration doc:
- people can use many 1-core Redis to scale (likely because Redis has been famous for single thread)
- people can use pipelining (a kind of batch) to send requests for better performance
- only a part of Redis support multi thread though
- ...

> any pros/cons of this?

Pros of course easily x2 performance, claimed by the doc.

Cons, I am not sure yet TBH.

**Comment by quantranhong1999** [comment]
> And performance test Redis e.g. using the [redis-benchmark tool ](https://redis.io/docs/latest/operate/oss_and_stack/management/optimization/benchmarks/).

I have performance tested locally with about 1 million requests for each Redis command, and compared Redis default one (single thread) vs Redis multi (4) threads: 
- Throughput increased 50%
- Latency reduced 50%

More detail: https://www.diffchecker.com/BbBhN5pK/

> Cons, I am not sure yet TBH.

At least so far I tested our Redis Event Bus test suite against the Redis multi thread enabled, the test suite seems stable.

**Comment by quantranhong1999** [comment]
Because most of our Redis deployments won't benefit from this, I decided to just note the knowledge: https://github.com/apache/james-project/pull/2370
