### ISSUE TITLE
[MU] Make Apisix plugin runner - support redis sentinel

### ISSUE THREAD

**Issue by vttranlina** [linagora/tmail-backend#1145]
## Why?
For [MU] deployment, SSO, Apisix, and Redis Sentinel are required.
 The current `tmail-apisix-plugin-runner` does not support configuration parsing for Sentinel.

**Comment by vttranlina** [comment]
pr https://github.com/linagora/tmail-backend/pull/1144

**Comment by vttranlina** [comment]
> Merged. Can we generate a new tag @vttranlina ?

yes

**Comment by Arsnael** [comment]
https://github.com/linagora/tmail-backend/pull/1146

**Comment by Arsnael** [comment]
And i think since the time upgrading the base image of apisix would be nice as well :) => https://github.com/linagora/tmail-backend/pull/1147

Better test it on staging before moving to this though
