### ISSUE TITLE
[Document] TMail validate reception handler 

### ISSUE THREAD

**Issue by vttranlina** [linagora/tmail-backend#1149]
This is a customized SMTP extension, but it has not been documented anywhere yet.: tmail-backend/smtp-extensions/src/main/java/com/linagora/tmail/smtp/TMailValidRcptHandler.java

Document location: docs/modules/ROOT/pages/tmail-backend/smtp-extensions/tmailValidRcptHandler.adoc

**Comment by Arsnael** [comment]
Good catch @vttranlina thanks !

**Comment by chibenwa** [comment]
Move this to todo please

**Comment by vttranlina** [comment]
https://github.com/linagora/tmail-backend/pull/1154
