### ISSUE TITLE
[PublicAsset] Cleanup oldest public assets when quota is reached

### ISSUE THREAD

**Issue by Arsnael** [linagora/tmail-backend#1150]
cf https://github.com/linagora/tmail-flutter/issues/3043#issuecomment-2268621035 for context

Similar to quota uploads, implement a logic where we would automatically delete oldest public assets not referenced anymore by identities, or by identities not existing anymore when the quota for it is reached.

DoD: integration tests

**Comment by chibenwa** [comment]
But we cleanup data tgat is no longer referebces by existing identities signatures ie no associated identities, or the associated identitiesno longer exist.

**Comment by Arsnael** [comment]
Updated, thanks

**Comment by vttranlina** [comment]
pr https://github.com/linagora/tmail-backend/pull/1153
