### ISSUE TITLE
Advertize FCM configuration in the session

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-backend#1187]
Currently TMail flutter client is hardcoded regarding FCM configuration.

THis setup do NOT allow one tenant per instalation

We shall advertize FCM configuration through the FCM capability in the session. Something close to fcm.env file on the mobile app.

Cc @Arsnael @hoangdat 

1 st step: propose and validate fcm.properties and API changes.
2 nd step: implement it
3 rd step: deploy it

**Comment by Arsnael** [comment]
https://github.com/linagora/tmail-backend/pull/1221
