### ISSUE TITLE
EncryptedProjectionCleanupListener

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-backend#119]
```
Upon expunged listener,
When a messageId is no longer referenced,
Then the EncryptedEmailContentStore is cleaned up
```

## Definition of done

Unit tests at the mailbox manager level

**Comment by vttranlina** [comment]
The `ReactiveGroupEventListener` implementation has a problem with get messageId list when mailbox deletion.
=> Using `PreDeletionHook` implementation
