### ISSUE TITLE
APISIX need to support ticket authentication route

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/tmail-backend#1192]
Frontend team start to integrate WebSocket.

Browser does not support sending `Authorization` header upon HTTP handshake request => solution: https://github.com/linagora/tmail-backend/blob/master/docs/modules/ROOT/pages/tmail-backend/jmap-extensions/ticketAuthentication.adoc

It seems we have enabled the ticket route in our code by default. But we need to expose the route via APISIX:
- OIDC ticket endpoint
- basic auth ticket endpoint

DoD:
- [x] demo docker compose => https://github.com/linagora/tmail-backend/pull/1194
- [x] Helm chart
  - [x] Allow configure TWP JMAP authentication strategies => https://ci.linagora.com/linagora/lrs/saas/tools/helm-charts/tmail-backend/-/merge_requests/78
  - [x] Enable `TicketAuthenticationStrategy` on DEV env => https://ci.linagora.com/linagora/lrs/saas/deployments/twake/twake-workplace-apps/-/merge_requests/141
  - [x] Exposed ticket routes in APISIX helm chart
     - https://ci.linagora.com/linagora/lrs/saas/tools/helm-charts/tmail-apisix/-/merge_requests/3
     - https://ci.linagora.com/linagora/lrs/saas/deployments/twake/twake-workplace-apps/-/merge_requests/142
- [x] test and deliver to the FE team

cc @tddang-linagora @hoangdat

**Comment by chibenwa** [comment]
> Browser does not support sending Authorization header upon HTTP handshake request 

Please confirm this is also the case with Flutter! (Never knows!)

**Comment by quantranhong1999** [comment]
> > Browser does not support sending Authorization header upon HTTP handshake request 
> 
> Please confirm this is also the case with Flutter! (Never knows!)

Cc @tddang-linagora

**Comment by Arsnael** [comment]
https://github.com/linagora/tmail-backend/pull/1194 merged

**Comment by tddang-linagora** [comment]
> > Browser does not support sending Authorization header upon HTTP handshake request
> 
> Please confirm this is also the case with Flutter! (Never knows!)

Confirmed
