### ISSUE TITLE
[S3 reliability] write accross 2 AZ blobstore implementation

### ISSUE THREAD

**Issue by Arsnael** [linagora/tmail-backend#1198]
The goal would be to offer a feature where we can write blobs across 2 availability zones synchronously.

### Configuration changes

In blob.properties

```
objectstorage.s3.secondary.enabled=true
objectstorage.s3.secondary.endPoint=${env:TMAIL_S3_ENDPOINT}
objectstorage.s3.secondary.region=${env:TMAIL_S3_REGION}
objectstorage.s3.secondary.accessKeyId=${env:TMAIL_S3_ACCESS_KEY}
objectstorage.s3.secondary.secretKey=${env:TMAIL_S3_SECRET_KEY}
```

Plugged to the Tmail blob module chooser

### Code & location

maven module: `tmail-baclend/blob/secondary-blob-store`

Write a `SecondaryBlobStoreDAO` class that takes 2 blob store DAO

#### Nominal case

```
GIVEN we parallely write to blobStoreA and blobStoreB
WHEN both operation succeeds
THEN we return a storage success
```

#### Partial failure

```
GIVEN we parallely write to blobStoreA and blobStoreB
WHEN write on blobStoreA succeeds and write on blobStoreB fails (or the reverse)
THEN the write fails
```

The partial error handling modifying this requirement will be handled in an other ticket.

#### Total failure

```
GIVEN we parallely write to blobStoreA and blobStoreB
WHEN write on blobStoreA fails and write on blobStoreB fails
THEN the write fails
AND no message is published on RabbitMQ
```

#### Read path

Read operation are performed in A, and fallback to B in case of error, or if the object is not found in A.

Plug this into the TMail blob module chooser

### Definition of done:

 - Unit tests for `SecondaryBlobStoreDAO`
 - Distributed app integration tests: given correctly configured tmail distributed when I receive a mail, it gets stored in A and B

**Comment by quantranhong1999** [comment]
> Plug this into the TMail blob module chooser

Likely should load the `SecondaryBlobStoreDAO` upon `objectstorage.s3.secondary.enabled=true`.

> Definition of done:

- Video: local docker compose + 2 zenko server. I save mail and it gets objects in both zenko servers.

Can do that without partial failure though.

**Comment by Arsnael** [comment]
In case of partial failure here, as retry is not handled yet, should we fail or succeed the operation?

**Comment by chibenwa** [comment]
> In case of partial failure here, as retry is not handled yet, should we fail or succeed the operation?

We can fail on partial write failure.

**Comment by hungphan227** [comment]
draft pr https://github.com/linagora/tmail-backend/pull/1214

**Comment by hungphan227** [comment]
need to use some fields, methods in James but they are private.

change to public PR https://github.com/apache/james-project/pull/2443
