### ISSUE TITLE
[S3 reliability] Partial error handling

### ISSUE THREAD

**Issue by Arsnael** [linagora/tmail-backend#1199]
After completing the previous task (cf #1198 ), you will need to change the behavior of partial failure case to handle retries with a RabbitMQ queue.

```
GIVEN we parallely write to blobStoreA and blobStoreB
WHEN write on blobStoreA succeeds and write on blobStoreB fails (or the reverse)
THEN we publish a message on RabbitMQ to retry the write operation later
AND the write succeeds
```

This means we need to set up a RabbitMQ queue to retry failed writes. The listener of the queue would then **asynchronously** read blobStoreA to complete the write on blobStoreB.

Definition of done:

- Integration tests

**Comment by hungphan227** [comment]
What happens if retry fail?

**Comment by chibenwa** [comment]
If we leverage tmail event bus we get that for free.

**Comment by quantranhong1999** [comment]
I have just checked our EventBus processing flow. It seems:

1. We first process the event message.
2. If processing the message fails (e.g. can not write to the second S3), we publish message to retry exchange and retry it for maximum of N times.
3. After N times, if retry still fails, we store the message in `EventDeadLetters` in database. And we have a reprocessing task to reprocess messages in `EventDeadLetters` already.
4. If we can not persist messages to `EventDeadLetters`, we fallback to NACK the rabbitmq message. Therefore the message would be put in configured RabbitMQ dead letter queue.

> What happens if retry fail?

It seems we are good as Benoit said `If we leverage tmail event bus we get that for free.`

Not related to this but I wonder how do we process the messages in RabbitMQ dead letter queues? I do not see reprocessing code for RabbitMQ dead letter queues.

**Comment by chibenwa** [comment]
>  how do we process the messages in RabbitMQ dead letter queues?

Use the shovel plugin to move thm back into the main queue. THis is trivial in the 'admin' platform for RabbitMQ.

**Comment by hungphan227** [comment]
There are two ways to implement the new event for secondary blob store
- create new serializer in TMail that extend MailboxEventSerializer in James (this is my current solution. However, currently I have an issue with this)
- create a whole new event bus class in Tmail

Because of the issue of the first solution, now I switch to the second solution.

@chibenwa @Arsnael please give comment if you have another idea.

**Comment by chibenwa** [comment]
> create a whole new event bus class in Tmail

Of course that's the way to go.

And of course we shall use the tmail event bus for this.
