### ISSUE TITLE
Auto-complete for recipients

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-backend#1204]
Be sure that we index and search against first name + display name (using prefix search)

Definition of done:

 - [x] Default mapping is modified in order to handle prefix search https://github.com/linagora/tmail-backend/blob/d66c57b34955c58592984537d4fe7351900e016e/tmail-backend/jmap/extensions-opensearch/src/main/java/com/linagora/tmail/james/jmap/ContactMappingFactory.java#L98
 - [x] Unit tests regarding this
 - [x] Document mapping change ( done on tenant upn ) :
     - Create the new index
     - Expose the new index under the write alias
     - reindex data from the old index to the new
     - Expose the new index behing the read alias
     - Remove the old index frombehind the read and write alias
     - Delete the old index

**Comment by quantranhong1999** [comment]
WIP: https://github.com/linagora/tmail-backend/pull/1205

**Comment by quantranhong1999** [comment]
> Document mapping change 

https://github.com/linagora/tmail-backend/pull/1206

> done on tenant upn 

Migration done on tenant upn.

**Comment by quantranhong1999** [comment]
It seems TMail frontend only fires autocomplete requests when having at least 3 chars.

Maybe in the capability object, we should return minimum characters to autocomplete?

```
"com:linagora:params:jmap:contact:autocomplete": {
  "minInputLength": 2
}
```

**Comment by chibenwa** [comment]
> Maybe in the capability object, we should return minimum characters to autocomplete?

That's a great idea!

@quantranhong1999  open an issue for this?

**Comment by quantranhong1999** [comment]
> @quantranhong1999 open an issue for this?

https://github.com/linagora/tmail-backend/issues/1209
