### ISSUE TITLE
[MU] Allow use of custom schema for LDAP Mailing lists

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-backend#1208]
Given attibute with value

`businessCategory: cn=memberRestrictedList,ou=twakeListType,ou=nomenclature,o=gov,c=mu`

then the LDAP Mailing list mailet should behave as if it was

`memberRestrictedList`

(Simply sanitize CN)

**Comment by chibenwa** [comment]
(emergency)

**Comment by quantranhong1999** [comment]
Is that schema valid? Duplicated `ou`?

**Comment by quantranhong1999** [comment]
I had a talk with Duc about LinID schema. I guess we can not change that then.

**Comment by quantranhong1999** [comment]
https://github.com/linagora/tmail-backend/pull/1212
