### ISSUE TITLE
EncryptedEmailDetailedView/get method

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-backend#121]
EncryptedEmailDetailedView has the following fields:

 - id: messageId backed

 - html: String (GPG armor)

 - attachmentMetadata: String (GPG armor of the JSON string representing attachments)

 - attachmentContents: List[String] (list of blobIds to download each attachment descibed in the encrypted JSON)

**Comment by Arsnael** [comment]
Same remark as previously, if no encryption for the user, does it mean no entries in the table?

Missing also a DoD. I guess would probably be similar to the EncryptedEmailFastView/get method ticket?
* Getting one EncryptedEmailFastView
* not found when not encrypted
* not found when message does not exist
* property filtering
* mixing found & notFound
* delegation testing

**Comment by chibenwa** [comment]
> delegation testing

GPG and delegation should not be expected to work IMO

We did no code regarding this just yet ... It's a complex topic...
