### ISSUE TITLE
EncryptedEmailFastView/get method

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-backend#122]
EncryptedEmailFastView have the following fields:

 - id: messageId backed

 - preview: String (gpg armored of the encrypted content)

 - hasAttachment: Boolean

EncryptedEmailFastView/get is a classic /get method. ids field is compulsory.

# DOD

- Getting one EncryptedEmailFastView
- not found when not encrypted
- not found when message does not exist
- property filtering
- mixing found & notFound
- delegation testing

**Comment by Arsnael** [comment]
Why preview should be null if encryption is not enabled for that user? Shouldn't the view have no entries for users not using encryption?

**Comment by chibenwa** [comment]
> Shouldn't the view have no entries at all for users not using encryption?

I agree returning not found.

**Comment by Arsnael** [comment]
> I agree returning not found.

Yes looked like what you meant in your DoD :) Thanks
