### ISSUE TITLE
tooBigEmailsShouldBeRejected in MemoryLinagoraEmailSendMethodTest fail

### ISSUE THREAD

**Issue by hungphan227** [linagora/tmail-backend#1222]
tooBigEmailsShouldBeRejected in MemoryLinagoraEmailSendMethodTest fail when updating james SHA to 10a6d95aab22d3de7163749a8bec8c2f7fb7c031 (https://github.com/apache/james-project/commit/10a6d95aab22d3de7163749a8bec8c2f7fb7c031)

FIX!!!

**Comment by quantranhong1999** [comment]
What is the jmap error message? Likely we can just adapt the test.

**Comment by chibenwa** [comment]
> What is the jmap error message? Likely we can just adapt the test.

Yes that's it.

To exceed the size of an email the test is sending a 20 MB HTML which is rejected because it exceeds the maximum size of a JMAP request.

The way around cf same test in `EmailSetMethodContract` is to create two attachments of 11 MB each instead.
