### ISSUE TITLE
Create a separate Guice module for OpenPaaS communication

### ISSUE THREAD

**Issue by HoussemNasri** [linagora/tmail-backend#1223]
# Description

We should have a separate Guice module for OpenPaaS communication to be able to inject custom RabbitMQ configuration that is specific to OpenPaas.

**Comment by chibenwa** [comment]
> Depends on: https://github.com/linagora/tmail-backend/pull/1215

Not really. IMO the too tasks are independant.

We can also write a `OpenPaaSAmqpForwardAttribute` mailet that is exactly `AmqpForwardAttribute` but configured using OpenPaaS configuration.

**Comment by chibenwa** [comment]
We decided with Houssem to not implement fallback for distributed-app to the main RabbitMQChannelPool.

We can live with 2 pools (we already live with 4 of them!)
