### ISSUE TITLE
PublicAsset: we are missing the PG implementation

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-backend#1238]
Implement it in https://github.com/linagora/tmail-backend/tree/postgresql/tmail-backend/jmap/extensions-postgres/src/main/java/com/linagora/tmail/james/jmap

CF https://github.com/linagora/tmail-backend/tree/postgresql/tmail-backend/jmap/extensions-cassandra/src/main/scala/com/linagora/tmail/james/jmap/publicAsset and bind it in postgres-app

**Comment by quantranhong1999** [comment]
Postgres implementation for public asset is already done and well bound: https://github.com/linagora/tmail-backend/blob/postgresql/tmail-backend/jmap/extensions-postgres/src/main/scala/com/linagora/tmail/james/jmap/publicAsset/PostgresPublicAssetRepository.scala#L18

Meanwhile it is truly not the case for `TicketStore`.

**Comment by chibenwa** [comment]
Oups sorry missed it!
