### ISSUE TITLE
Websocket tickets: we are missing the PG implementation

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-backend#1239]
CF https://github.com/linagora/tmail-backend/tree/postgresql/tmail-backend/jmap/extensions-cassandra/src/main/scala/com/linagora/tmail/james/jmap/ticket

Implement it in https://github.com/linagora/tmail-backend/tree/postgresql/tmail-backend/jmap/extensions-postgres/src/main/java/com/linagora/tmail/james/jmap and bind it in postgres-app

**Comment by quantranhong1999** [comment]
https://github.com/linagora/tmail-backend/pull/1271
