### ISSUE TITLE
Use a CreatedBlobIdList and do a BlobStoreDAO wrapper to ensure we don't write blobs twice

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-backend#124]
# Why

OVH blobStore do not support read/write isolation

We can not read blobs while we are re-writting them.

Re-writting blobs is very current with the deduplication enabled and leads to a lot of errors on production

# How

In a new `openpaas-james/openpaas-james/blob/blobid-list` maven project

Create a table the only stores blobIds (PK:blobId String)

```
class CassandraCreatedBlobIdStore {
  def isStored(blobId: BlobId): Publisher[Boolean]
  def reference(blobId: BlobId): Publisher[Unit]
  def isStored(blobId: BlobId): Publisher[Unit]
}
```

Write a BlobStoreDAO that decorates another BlobStoreDAO and only write the blob if it is not yet stored in the default bucket:

```
class SingleSaveBlobStoreDAO(blobStoreDAO, cassandraCreatedBlobIdStore) {
   ...
}
```

Note deletes in the default bucket should throw. Note: you should run the BlobStoreDAO contract.

In TMail write a new blobStoreModule chooser to wrap S3blobStoreDAO if deduplication is enabled (and only if!) - ask Benoit for help on this phase if needed.

**Comment by tanandy** [comment]
interesting,  indeed AWS worked on that topic hardly especially for big data workloads.

S3 is currently strongly consistent with strong read after write while OS swift is eventually consistent and its a huge different indeed

**Comment by chibenwa** [comment]
> so the problem is more using and support eventually consistent architecture when strongly consistency is not available

Yes. And **deduplication** requires consistency as several email shares the same blobs.

We can work around using a third party DB to keep the information that data is already stored and thus skip that step.

**Comment by chibenwa** [comment]
TODO write an ADR for this.

**Comment by rouazana** [comment]
I don't understand how you expect to achieve consistency between two datastores in a distributed environment. Hopefully the ADR will answer this :)

**Comment by chibenwa** [comment]
> I don't understand how you expect to achieve consistency between two datastores in a distributed environment. Hopefully the ADR will answer this :)

You are very right, let's accept the fatality of our destiny  ;-)

Now that I finished joking `achieve consistency between two datastores` -> we don't need that. So let's get this argument out of our way.

```
Given that blobs are immutable
And that storing a blob twice is acceptable (current behaviour) - correspond to when saving a blobId to C* fails so is rare
And that we have no deletion (yup)
Then we can avoid almost all 400 errors that pops on concurrent append/reads on the same key
```

Now I see you coming, how does it play with deduplication?

BlobId will ship a notion of generation, we never delete stuff of the current generation, so we never dete stuff that we are appending, so we don't mess up with the blobId list.

Note that it is scoped to the default bucket not to interfere with the DeletedMessageVault.

And yes, this "solution" is better to me that taking the risk of weak isolation that could result in further data corruption... But maybe you have alternative designs?

BTW I thought you were in vacations...

**Comment by rouazana** [comment]
I'm still not sure to get your point.

You tell:

> Re-writting blobs is very current with the deduplication enabled and leads to a lot of errors on production

and also:

> We can work around using a third party DB to keep the information that data is already stored and thus skip that step.

Suppose you have server A which is writting blobA and server B which is also writting blobA at the same time. Even if you store in Cassandra that blobAId has been stored, you cannot do that before server B also starts to write it, unless using bad locking mechanisms on top of Cassandra.

So if I get you well, you try to reduce the case where this can happen, but there are still cases were there will be data corruption on top of OVH. Did I get it well?

> Now I see you coming, how does it play with deduplication?

Nope, I'm not on this field.

> BTW I thought you were in vacations...

Seems I'm back! :)

**Comment by chibenwa** [comment]
> Suppose you have server A which is writting blobA and server B which is also writting blobA at the same time. Even if you store in Cassandra that blobAId has been stored, you cannot do that before server B also starts to write it, unless using bad locking mechanisms on top of Cassandra.


Sure this is not addressed 100% of the time.

But consider the more generic use case:

 - I forward a mail with attachment already stored -> that, will be handled
 - I send a mail to bob cedric denis edouard (and a single server would be doing the reading and writing) -> that, will be handled

That, would make me feel safer.

As a reminder reading the object storage metadata to avoid double storage was, last time I tried, shockingly slow.

Other solution: switch to AWS, use their proven K8S clusters, use their managed Cassandras, and use their S3 with isolation...

**Comment by chibenwa** [comment]
Really I don't see why we should discard a solution that would objectively make us way safer, @rouazana .

**Comment by chibenwa** [comment]
ADR https://github.com/linagora/james-project-private/pull/108

**Comment by rouazana** [comment]
why is this ADR private while this repository and this issue is public?

**Comment by chibenwa** [comment]
> why is this ADR private while this repository and this issue is public?

Because TMail ADRs are private for now. Let see how this evolves.
