### ISSUE TITLE
LabelGetMethodContract asserts the vault extension (oups)

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-backend#1241]
![image](https://github.com/user-attachments/assets/0c0f2f35-1b44-48db-a1a3-fa23c9f92dfa)

https://github.com/linagora/tmail-backend/blob/15b098a682fc69a0368c7ba49bfb9b3772e20bb0/tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LabelGetMethodContract.scala#L51

Of course it shall assert the label extension...

**Comment by vttranlina** [comment]
pr https://github.com/linagora/tmail-backend/pull/1242
