### ISSUE TITLE
[S3 realibility] Redeliver event dead letters to the queue

### ISSUE THREAD

**Issue by hungphan227** [linagora/tmail-backend#1253]
## Why

When one of S3 is down for a long time, blob events would be stored in event dead letters table. James already has a task to redeliver dead letters back to the queue.

Unfortunately, EventDeadLettersRedeliverService (single instance) only has one EventDeadLetters instance -> only one EventSerializer instance (currently it is MailboxEventSerializer). Therefore, it does not work with blob event dead letters.

Refactoring code is needed to apply EventDeadLettersRedeliverService for blob event dead letters

## How

- Move EventSerializer from CassandraEventDeadLettersDAO to CassandraEventDeadLetters
- Update retrieveFailedEvent method in CassandraEventDeadLettersDAO to return String instead of Event
- Create method getEventSerializer in EventBus interface
- In EventDeadLettersRedeliverService, create Map<Group, EventSerializer>

## DoD

Integration tests

**Comment by hungphan227** [comment]
@Arsnael @chibenwa if you have other ideas please comment

**Comment by hungphan227** [comment]
welcome any thoughts on this

**Comment by hungphan227** [comment]
@chibenwa if you have other thoughts pleas comment

**Comment by quantranhong1999** [comment]
Sounds ok to me

**Comment by quantranhong1999** [comment]
Maybe make this a James ticket as it would benefit `EventDeadLetters` to reprocess JMAP events with `JmapEventSerializer` too (rather than only `MailboxEventSerializer`)?

**Comment by chibenwa** [comment]
I think this would be the simplest indeed:

 - Create method eventSerializer in EventBus interface
 - Add a multibinder with all EventBusses
 - EventDeadLetter reprocess service would take that set of eventbus. When reprocessing:
    - List all event bus, foreach
    - Try to deserialize the event
    - if deserialize then reprocess the event
    - if not deserialized then try next event bus.

**Comment by hungphan227** [comment]
James: https://github.com/apache/james-project/pull/2465
Tmail-backend: https://github.com/linagora/tmail-backend/pull/1249
