### ISSUE TITLE
Mobile APP app grid

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-backend#1289]
### Why

Hint the end user about related apps he can install 

For CNB / MU: he shall be advised `Twake Sync`

For Linagora: `Twake Sync`, `Twake chat` and why not `LinShare`

For TWP:  `Twake chat` 

=> We see that this app grid is deployment dependant

So this means the back needs to be configured for it, and info carried over to the front.

### What

Add a section in `/.well-known/linagora-ecosystem`:

```
"mobileApps": {
    "Twake Chat": {
        "logoURL": "https://xyz",
        "appId": "abc"
    },
    "Twake Drive": {
        "logoURL": "https://xyz",
        "webLink": "https://tdrive.linagora.com"
    },
    ...
}
```

Should be configurable...

**Comment by vttranlina** [comment]
pr https://github.com/linagora/tmail-backend/pull/1347

**Comment by hoangdat** [comment]
Hi @back-end team,
Cc @chibenwa @Arsnael 

please add configuration for: Twake Chat and Twake Sync like this
```
  "mobileApps": {   
    "Twake Chat": {
        "logoURL": "https://xyz",
        "androidPackageId": "app.twake.android.chat",
        "iosUrlScheme": "twake.chat",    
        "iosAppStoreLink": "itms-apps://itunes.apple.com/us/app/twake-chat/id6473384641"
    },
    "Twake Sync": {
        "logoURL": "https://xyz", 
        "androidPackageId": "com.twake.android.sync"
    }
  }
```

**Comment by vttranlina** [comment]
@hoangdat I created a deployment ticket. 
Please track it at:
- https://github.com/linagora/tmail-backend/issues/1350
