### ISSUE TITLE
Simple health-check URL

### ISSUE THREAD

**Issue by guimard** [linagora/tmail-backend#1301]
### Description of the bug

Some load-balancer doesn't accept query parameters inside a Health-Check URL. Is it possible to provide an alias like
`/healthcheck` that hide the real health-check URL ?

**Comment by chibenwa** [comment]
If I remember the discussion this is for a LB to ensure the health of a JMAP service and thus shall be a sub-endpoint of the jmap endpoint.

How about:


```
curl 'https://jmap.govmu.org/.well-known/webfinger?resource=https://jmap.govmu.org&rel=http://openid.net/specs/connect/1.0/issuer' -v
```

?

It is not authenticated and would allow to ensure the JMAP server / service is online...

**Comment by guimard** [comment]
> If I remember the discussion this is for a LB to ensure the health of a JMAP service and thus shall be a sub-endpoint of the jmap endpoint.
> 
> How about:
> 
> ```
> curl 'https://jmap.govmu.org/.well-known/webfinger?resource=https://jmap.govmu.org&rel=http://openid.net/specs/connect/1.0/issuer' -v
> ```
> 
> ?
> 
> It is not authenticated and would allow to ensure the JMAP server / service is online...
You're right, We need to have a simplified alias for this

**Comment by chibenwa** [comment]
Yes?

**Comment by chibenwa** [comment]
On govmu nginx we might very well be able to do this?

**Comment by Arsnael** [comment]
I agree nginx should be able to allow abstraction of the query params?

**Comment by vttranlina** [comment]
Simple health-check url: https://jmap.govmu.org/healthcheck
pr: https://ci.linagora.com/linagora/lrs/saas/infrastructures/gov-mauritius/-/merge_requests/57
