### ISSUE TITLE
[CNB] Add optional suffix for bucket names of secondary blob store

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-backend#1307]
### Description 

I want to have distinct bucket names for primary blob store and secondary blob store because I need to host them on the same OVH account.

![image](https://github.com/user-attachments/assets/e0d77588-278b-4f78-976f-78f96ca464e4)

Hence, I need a `blobStore.properties` :

```
objectstorage.s3.secondary.bucket.suffix=copy
``` 

Also include a HELM chart property for this.

**Comment by quantranhong1999** [comment]
How about `objectstorage.s3.secondary.bucketPrefix`?

Suffix would likely require changes on James's S3BlobStoreConfiguration.

**Comment by quantranhong1999** [comment]
code change: https://github.com/linagora/tmail-backend/pull/1309

**Comment by quantranhong1999** [comment]
helm v5.2: https://ci.linagora.com/linagora/lrs/saas/tools/helm-charts/tmail-backend/-/merge_requests/109

I would take the chance to backport the secondary blob store config to branch 4.0 too as it seems 4.0 still can be used by CNB prod...

**Comment by chibenwa** [comment]
Ok I get what happens...

SecondaryBlobStore asks to use `tmail-cnb-preprod-copy`

But secondary S3BlobStore DAO applies "bucket resolver logic".

As the bucket is not the default bucket `tmail-cnb-preprod` it do adds on the fly `tmail-cnb-preprod-` prefix

CF 

```
objectstorage.bucketPrefix=tmail-cnb-preprod-
```

Resulting in the above result

**Comment by chibenwa** [comment]
My conclusion is that in order not to double apply the prefix onto the second S3 blob store the namespace of the second blob store must include the suffix, so that it detects it is the default bucketname and do not add suffix.

**Comment by chibenwa** [comment]
CF https://github.com/linagora/tmail-backend/pull/1316
