### ISSUE TITLE
Rename openpaas-james repository to tmail-backend

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-backend#133]
- Fix issues on ZenHub side
 - Fix Jenkins 2

**Comment by Arsnael** [comment]
https://ci.linagora.com/rcordier/james-ci/merge_requests/6

Should we change the certs and domain names as well? 

Like using linagora certs instead of openpaas ones and changing from https://james-jenkins.open-paas.org to https://james-jenkins.linagora.com for example?

**Comment by chibenwa** [comment]
To https://tmail-jenkins.linagora.com you mean? 

Yes if possible...

**Comment by Arsnael** [comment]
Might require a bit of work but will try :)

**Comment by chibenwa** [comment]
To be honest it is IMO not a priority.
