### ISSUE TITLE
Restart RabbitMQ consumers when vital queue got no consumers

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/tmail-backend#1358]
## Why

Today, there were no consumers on `deleted-message-vault-work-queue` of MU, so we needed to restart TMail ourselves.

We should have a mechanism to automatically spot the no consumers issues and restart them.

Originally it seems @chibenwa thought about writing a healthcheck for RabbitMQ consumers on the queues + auto restart TMail.

However, I checked the code and got another simple idea.

## How

- Add the `deleted-message-vault-work-queue` (could be other queues as well) to [`ScheduledReconnectionHandler`](https://github.com/linagora/tmail-backend/blob/master/tmail-backend/guice/distributed/src/main/java/com/linagora/tmail/ScheduledReconnectionHandler.java#L280) monitoring list

## DoD
- Test the `ScheduledReconnectionHandler` more to ensure it can correctly restart the consumers if a queue in the list has no consumer.

**Comment by chibenwa** [comment]
Deleted Message Vault may be disabled.

However the list of queues is static. We need to make sure queue consumption still runs if `ScheduledReconnectionHandler` has queue configured that do not exist

(write explicit tests for it, passing `abc-i-do-not-exist` as a queue in tests?)

**Comment by quantranhong1999** [comment]
> (write explicit tests for it, passing abc-i-do-not-exist as a queue in tests?)

+1

> However the list of queues is static.

We can make the list configurable.

**Comment by quantranhong1999** [comment]
Likely we need a `ScheduledReconnectionHandler` implementation for deleted message vault work queue on James side.

**Comment by chibenwa** [comment]
No my feeling is that by handling the missing queue leniently we could keep this sttatic, just monitor the queue that exist and keep the configuration burdown low.

**Comment by chibenwa** [comment]
I'm against conf for this: it will get forgotten. The alternative would be to link it with the module chooser but it looks complex...

**Comment by quantranhong1999** [comment]
> Likely we need a ScheduledReconnectionHandler implementation for deleted message vault work queue on James side.

https://github.com/apache/james-project/pull/2546

> (write explicit tests for it, passing abc-i-do-not-exist as a queue in tests?)

https://github.com/linagora/tmail-backend/pull/1366
