### ISSUE TITLE
[MU] Push contacts to Sabre via DAV

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-backend#1381]
### Why?

On MU deployment OpenPaaS fails at acting correctly when consuming the queue `collector:email`

We want a more resilient mechanism to collect contacts from email sent.

### How?

Create then directly onto Sabre using DAV impersonation.

We will add a mailet doing that onto the openpaas extension

Steps 1: Given the mail address of the recipient use a deterministic way to comput the uid and filename. Proposal `HEX(sha1(mailAddress))`

Step 2: Get the OpenPaaS `_id`

Step 3: see if the contact exists: `GET https://dav.linagora.com/addressbooks/{_id}/collected/{hex(sha1(mailAddress))}.vcf`

Step 4: PUT the contact : `PUT /addressbooks/{_id}/collected/{hex(sha1(mailAddress))}.vcf`

Bundle this in a `CardDavCollectedContact` mailet.

Replace the OpenPaaSAMQPForwarder used for this.

**Comment by vttranlina** [comment]
https://github.com/linagora/tmail-backend/pull/1417
