### ISSUE TITLE
Relocate memory implementations from jmap-extensions to jmap-extensions-api

### ISSUE THREAD

**Issue by HoussemNasri** [linagora/tmail-backend#1399]
All memory implementations (and tests) in `jmap-extensions` should be relocated to `jmap-extensions-api`.

## definition of done
All `Memory*` prefixed classes reside in `jmap-extensions-api`.

*Originally posted: https://github.com/linagora/tmail-backend/pull/1339#discussion_r1875941249*

**Comment by chibenwa** [comment]
Ok to split it in another task if done timely
