### ISSUE TITLE
Shutdown triggers massive Redis logs...

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-backend#1414]
### Description of the bug

![image](https://github.com/user-attachments/assets/7786ccb1-ee88-48b7-8504-7bfc902f16d5)

Investigate.

 - if the log is benign silent it after shutdown
 - if the throwing situation can be avoided with better resource management, avoid it
 - or can we better manage the shutdown sequence, with more time to iterate through Redis streams?

**Comment by quantranhong1999** [comment]
https://github.com/linagora/tmail-backend/pull/1423
