### ISSUE TITLE
Web socket for backend container with basic auth

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/tmail-backend#1416]
## Context
- Front end need to integration test web socket capability
- Front end is using basic https://github.com/linagora/tmail-flutter/blob/master/backend-docker/docker-compose.yaml to run back end container, and using basic auth to login
- Web socket on back end container with basic auth is currently broken on their docker compose setup

We need to help them to fix their backend setup.

**Comment by quantranhong1999** [comment]
created by @tddang-linagora

**Comment by vttranlina** [comment]
Please add `authentication.strategy.rfc8621=BasicAuthenticationStrategy` to jmap.properties, move it to the container, and try again.

**Comment by tddang-linagora** [comment]
> authentication.strategy.rfc8621=BasicAuthenticationStrategy

It still failed with `HTTP Authentication failed; no valid credentials available`
![Screenshot 2024-12-18 at 10 08 24](https://github.com/user-attachments/assets/02a06647-8331-413a-bb94-d03d8cf121c1)

**Comment by Arsnael** [comment]
Auth websocket by ticket, need to add as well in `authentication.strategy.rfc8621` :  `com.linagora.tmail.james.jmap.ticket.TicketAuthenticationStrategy`

**Comment by Arsnael** [comment]
Sat down with @tddang-linagora , solved.

Closing ticket

**Comment by tddang-linagora** [comment]
It's working perfectly now. Thank you.
