### ISSUE TITLE
During LDAP outages, email delivery should still proceed

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-backend#157]
## Why?

Currently TMail relies on the LDAP for user identity.

This means every time we resolve a mail, we look up the user to know if we handle him or not. So we perform a LDAP request.

This causes two problems:

 - 1. We put undue pressure on the LDAP upon SMTP bursts
 - 2. When the LDAP is down, emails cannot be received/sent 

We would like to mitigate these two impacts.

## How?

Have combined user repository:

 - existence checks are performed against a Cassandra table
 - Authentication (SMTP / IMAP) is still resolved against the LDAP (because LDAP might not expose the hash for synchronization)
 - We provide synchronisation endpoint to synchronise the LDAP and the cassandra table. A CRON can be configured to fix this.

Cc @atan-linagora  do you agree with this?

## Yes but can you be more precise on the implementation details?

Sure.

In TMail `tmail-backend/combined-identity` create a new `CombinedUsersRepository` that takes as an argument a `CassandraUsersRepository` and `ReadOnlyUsersLDAPRepository`. 

This repository:
   - Rejects new user addition
   - Rejects password updates
   - Test passwords against the LDAP
   - But check contains, list, etc... against cassandra.

Write a couple of unit tests for this class.

Write a new module chooser for Tmail distributed and Tmail distributed-esv6-backport (rewrite of `org.apache.james.data.UsersRepositoryModuleChooser`): 
   - If the LDAP user repo FQDN is specified, instanciate the LDAP repository
   - If the Combiner user repo FQDN is specified, instanciate it. We expect the same config than LDAP repository, so that we can instanciate it to.
   - Default to the Cassandra repo.

Config `usersrepository.xml` would look like this:

```
<?xml version="1.0"?>
<usersrepository name="LocalUsers"
    class="com.linagora.tmail.identity.CombinedUsersRepository"
    ldapHost="ldap://ldap:389"
    principal="uid=james-user,ou=people,dc=james,dc=org"
    credentials="secret"
    userBase="ou=people,dc=james,dc=org"
    userIdAttribute="mail"
    userObjectClass="person">
    <supportsVirtualHosting>true</supportsVirtualHosting>
</usersrepository>
```

Provide a task to synchronize the two repositories in `tmail-backend/webadmin/combined-identity` :

```
curl -XPOST http://port:ip/users?task=synchronize
```

This task will:
 - list users of the LDAP. list users of Cassandra. Hold the 2 lists in memory in HashSets.
 - For each user name contained in the LDAP we will verify it exists in Cassandra. Missing cassandra entries are created with a STRONG password of 24 random generated characters (Will never be used but better be safe). 
 - For each user name contained in Cassandra we will verify it exists in LDAP. Dandling Cassandra entries shall be removed

OPS will then configure a CRON job for this every 10 minutes.

**Comment by chibenwa** [comment]
![Screenshot from 2021-05-31 09-50-54.png](https://images.zenhubusercontent.com/5ef2aee69879df3417738ce4/1d39c227-37a1-4b05-82ef-6048d84e3d87)

![Screenshot from 2021-05-31 09-51-40.png](https://images.zenhubusercontent.com/5ef2aee69879df3417738ce4/687bed30-118a-499d-a833-cbe8c38201fd)

**Comment by rouazana** [comment]
I think LDAP is much more efficient than Cassandra to handle authentication requests.

To solve your issue regarding the availability of Linagora's LDAP I see 2 simpler solutions:
- use an LDAP mirror near James. LDAP synchronization is pretty standard and easy to configure. You will then have a local read-only replica which will answer faster than Cassandra.
- use an existing synchronization tool such as LSC.

**Comment by chibenwa** [comment]
> I think LDAP is much more efficient than Cassandra to handle authentication requests.

 - 1. It is not the point. I am much more concerned about resiliency cf repeated LDAP incidents @linagora recently.
 - 2. It's configurable: I'm free to use the combined version and you are free not to.
 - 3. It's configurable: if it is a bad idea we will just switch back to the default configuration
 - 4. You miss read. The proposal is to still rely on LDAP as an AUTH backend (to not duplicate passwords hash)
 - 5. Then justify to top mgt the email service downtime, that is unecessary, in the absence of LDAP.
 
 Cassandra, now, is the strong point of our infrastructre, rock solid, up to 36 Kops not even stressed out (the CPU of the James servers vanishes first!) so I really don't mind switching the load of the LDAP to Cassandra. In term of performance it is not significative at all.
 
 > To solve your issue regarding the availability of Linagora's LDAP I see 2 simpler solutions:
 >   -  use an LDAP mirror near James. LDAP synchronization is pretty standard and easy to configure. You will then have a local read-only replica which will answer faster than Cassandra.
 >   - use an existing synchronization tool such as LSC.
 
 Not doable. EG: UPN do not let access password hashes.
 
 Every one get his biases. Time to move forward in my opinion.

**Comment by tanandy** [comment]
fyi @fmartin-linagora

**Comment by tanandy** [comment]
@chibenwa sorry but i have not the time to dig into it right now.

btw this seems fair to start comparing existing solution. we have a cron and a local usersrepo. Is the cron embedded to james (care about scaling class) or something external ? how it authenticates / retrieve stuff

**Comment by rouazana** [comment]
> It is not the point. I am much more concerned about resiliency cf repeated LDAP incidents @linagora recently.

Right, I also think LDAP is much more resilient than Cassandra to handle authentication requests.

If you want to use a local repository for users, fair. And I did not misread. But then you can just use an existing synchronization mechanism such as LSC instead of reinventing one.

**Comment by tanandy** [comment]
so we can use LSC to feed the local repo right ?

**Comment by chibenwa** [comment]
> But then you can just use an existing synchronization mechanism such as LSC instead of reinventing one.

We cannot assume the LDAP will expose password hashes.

So we need a logical "AND" inside James logic anyway (to delegate the auth request to the LDAP having access to the creds, and to delegate all other request to a more trust worthy mechanism.).

The composite approach is compulsory.

Now that said:

> Right, I also think LDAP is much more resilient than Cassandra to handle authentication requests.

My direct experience do not prove me that.

We can do the user sync to the local DB with LSC if it please you. If you provide help doing so @rouazana .

**Comment by rouazana** [comment]
> My direct experience do not prove me that.

Do you have other experience with LDAP than an old outdated misconfigured platform?

**Comment by rouazana** [comment]
> We can do the user sync to the local DB with LSC if it please you. If you provide help doing so @rouazana .

With pleasure. We already have a James plugin, just need to add the user API: https://github.com/lsc-project/lsc-james-plugin

**Comment by chibenwa** [comment]
> Do you have other experience with LDAP than an old outdated misconfigured platform?

No and I do not plan to.

But again: **It is configurable** (police size 48).

My goal is to be able to handle the crappy platforms I will be handed with, without inpacting too much my workload. Given that I live in an environment with this kind of concerns I have to adapt.

Give me an envirnment with a LDAP I can trust, and yes sure I gonna run the LDAP UsersRepository.

**Comment by chibenwa** [comment]
> With pleasure. We already have a James plugin, just need to add the user API: https://github.com/lsc-project/lsc-james-plugin

Great then: 

 - 1. Let's implement the CompositeUsersRepository and its module chooser
 - 2. Let's add a LSC script to sync the users when their PWD is not available (fake passwords in Cassandra) - IE UPN use case
 - 3. Let's write the sync script when we can have access to the passwords hash - Linagora use case maybe (not even sure)

**Comment by rouazana** [comment]
> Give me an envirnment with a LDAP I can trust, and yes sure I gonna run the LDAP UsersRepository.

That's exactly my proposal: build a local LDAP replica so you can trust it ^^

**Comment by rouazana** [comment]
> Let's write the sync script when we can have access to the passwords hash - Linagora use case maybe (not even sure)

1. you can also use LSC for that
2. it's a bad idea because you won't be able to handle the password policy

**Comment by chibenwa** [comment]
> That's exactly my proposal: build a local LDAP replica so you can trust it ^^

Yet what is the point if I do not have the rights to copy password hashes to it :-) 

I still need extensive logic to say use this LDAP for Auth, and this one for existence checks.

------------------------

I had a quick review of what is needed on the LSC stuff:

 - methods to add / remove users in  [JamesDAO](https://github.com/lsc-project/lsc-james-plugin/blob/master/src/main/java/org/lsc/plugins/connectors/james/JamesDao.java)
 - then we need to create a JamesUserDstService similar to [this](https://github.com/lsc-project/lsc-james-plugin/blob/master/src/main/java/org/lsc/plugins/connectors/james/JamesAliasDstService.java) Here...
      - What is the goal of "pivot" -> list of user in our case
      - then getBean just returns the user itself without any backend call I imagine.
      - Apply adds / remove users.
 - We then can declare operation like [here](https://github.com/lsc-project/lsc-james-plugin/blob/master/sample/ldap-to-james/lsc.xml)
  - We can set up a LDAP for testing this with stuff like [this](https://github.com/linagora/james-project/tree/master/server/data/data-ldap/src/test/resources/invalid/ldif-files)
  
  
 > you can also use LSC for that
 
 Link?
 
 > it's a bad idea because you won't be able to handle the password policy
 
 Be more explicit please.

**Comment by rouazana** [comment]
> Yet what is the point if I do not have the rights to copy password hashes to it :-)

As far as I remember, it's a very rare case.

> >  you can also use LSC for that
> Link?

Sorry? Pasword synchronization is a very basic task for LSC. A password is just an LDAP attribute like others...



> > it's a bad idea because you won't be able to handle the password policy
> Be more explicit please.

When you are interacting with an LDAP directory, you can expect it to handle password failures in a way to avoid brute force attacks. For example if a user type an incorrect password 10 times in less than 1 mn, you can block the account for some minutes. Of course this is highly configurable and there is a range of possibilities given the security recommendations of each customer.

**Comment by rouazana** [comment]
> What is the goal of "pivot" -> list of user in our case

A pivot is an attribute which value is the same and is unique in both the source and the destination of the synchronization.

> then getBean just returns the user itself without any backend call I imagine.

In general it's not expected, because list return the minimal set (only the pivot in general) while getBean return the full attribute list you need to sync. But maybe in this case if there is only the pivot to sync it could work... Need to check edge cases though.

**Comment by chibenwa** [comment]
> As far as I remember, it's a very rare case.

Yet we run into it.

> When you are interacting with an LDAP directory, you can expect it to handle password failures in a way to avoid brute force attacks. For example if a user type an incorrect password 10 times in less than 1 mn, you can block the account for some minutes.

A good thing that so far I plan to keep auth against a LDAP backend...

**Comment by fmartin-linagora** [comment]
Nice, let's add a 8th directory to the LINAGORA infrastructure instead of fixing the SI issue. :'(
Once LDAP is properly deployed and configured, with a stable network, it is very fast and reliable service. (as Rapael said).

**Comment by tanandy** [comment]
> Nice, let's add a 8th directory to the LINAGORA infrastructure instead of fixing the SI issue. :'(
> Once LDAP is properly deployed and configured, with a stable network, it is very fast and reliable service. (as Rapael said).

what do you mean, we dont add new directory ???

**Comment by fmartin-linagora** [comment]
the solution were talking about was to deploy a new local LDAP replica. If I understood well what was written above.

**Comment by tanandy** [comment]
> the solution were talking about was to deploy a new local LDAP replica. If I understood well what was written above.

its more about a local user dbs

**Comment by Arsnael** [comment]
Well you did not understand :D Here it's just having the list of users in Cassandra in case LDAP is down, so that we can still do mail processing. 

>  Once LDAP is properly deployed and configured, with a stable network, it is very fast and reliable service. (as Rapael said).

I've been hearing that for a long time, never saw it coming. And that does not mean your LDAP is gonna be a superman that never has problems and never goes down. If you have external troubles out of your control and your LDAP instance is unavailable because well OVH has troubles for examples, James can still process incoming emails.

But we still use LDAP for users connections, that does not change.

**Comment by tanandy** [comment]
> Well you did not understand :D Here it's just having the list of users in Cassandra in case LDAP is down, so that we can still do mail processing.
> 
> > Once LDAP is properly deployed and configured, with a stable network, it is very fast and reliable service. (as Rapael said).
> 
> I've been hearing that for a long time, never saw it coming. And that does not mean your LDAP is gonna be a superman that never has problems and never goes down. If you have external troubles out of your control and your LDAP instance is unavailable because well OVH has troubles for examples, James can still process incoming emails.
> 
> But we still use LDAP for users connections, that does not change.

yes, you cannot create adherence like this on the LDAP if you dont need it

**Comment by fmartin-linagora** [comment]
ok, just a local cache for the list of "available" users.
