### ISSUE TITLE
PGP: ClearEmailContent => EncryptedEmailContent

### ISSUE THREAD

**Issue by Arsnael** [linagora/tmail-backend#174]
Write the transformation to get:

```
class EncryptedEmailContentFactory(...) {
   def encrypt(clearEmailContent: ClearEmailContent): EncryptedEmailContent = ???
}

case class EncryptedEmailContent(
   encryptedPreview: String, 
   encryptedHtml: String, 
   hasAttachment: Boolean /* non encrypted */,  
   encryptedAttachmentMetadata: String /* JSON payload representing the attachment metadata that is encrypted */,
   encryptedAttachmentContents: List[String])
```

Here are details for JSON payload for encryptedAttachmentMetadata :

An **EncryptedAttachment** have the following properties

 - **position**: Integer, position in the mime parts.
 - **blobId**: String, can be used to download the GPG armor of this message. TMail uses the following pattern: `encryptedAttachment_{messageId}_{position}`.
 - **name**: String, File name of this attachment.
 - **contentType**: String, ContentType of this attachment.
 - **cid**: String, CID of this attachment.
 - **isInline**: Boolean, is this attachment inlined?
 - **size**: Positive integer, size of this attachment.

## Definition of Done

Simple unit tests about this encryption

**Comment by Arsnael** [comment]
From Tung, in closed wronged place ticket:

> With this structor, how can we matching each element in `encryptedAttachmentContents` with corresponding in `encryptedAttachmentMetadata`?

My knowledge with attachments is limited... But I would guess maybe the position of the metadata? But I'm not sure.

**Comment by vttranlina** [comment]
@chibenwa how can we get a `position` property?

**Comment by Arsnael** [comment]
I answered in your PR @vttranlina
