### ISSUE TITLE
Implement a LongLivedToken authentication strategy

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-backend#211]
In TMail JMAP extensions, implement an `AuthenticationStrategy` backed by the `LongLivedTokenStore` ( #209 ).

Syntax:

`Authorization: Bearer {username}_{UUID secret - LongLivedTokenSecret}`

Be sure to write unit tests for it, especially:
  - username can start, end, contain, possibly multiple times `_` character.

**Comment by vttranlina** [comment]
Does it have to relate to JWT tokens (https://github.com/linagora/tmail-backend/pull/221 )?

**Comment by chibenwa** [comment]
No, JWTs are used for short lived tokens
