### ISSUE TITLE
Implement GET /token endpoint (long live token auth only)

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-backend#213]
Implement a endpoint that given a long lived token will return a short lived token.

Short lived tokens are JWT token signed on the fly by the backend.

Here is the JMAP route specification:

```
GET /token?type=shortLived&deviceId=xxxx

Authorization: bearer bob@localhost_UUIDTOKEN
```

Use the authenticationMethod introduced in #211 and the JWT signer in #208.

And will return:

```
{ 
   "token": "aaaaabbbbccccc",
   "expiresOn": "2020-08-17T11:39:40.906+07:00"
}
```

Note that the call fails when a wrong clientId is specified (mis-match)...

**Comment by vttranlina** [comment]
This is webAdmin endpoint?

**Comment by chibenwa** [comment]
No a JMAP one.

**Comment by chibenwa** [comment]
(like `GET /jmap/session`)

**Comment by vttranlina** [comment]
Do we need to check `deviceId` in the parameter is matching with longLivedToken store in the database?
I think No,

**Comment by Arsnael** [comment]
> Do we need to check `deviceId` in the parameter is matching with longLivedToken store in the database?
> I think No,

I think yes, as you can have multiple long lived token on different devices. You need to check that the long lived token put in auth header is matching with the deviceId in our db. If not then what would be the point to have this param in the request then? :)
