### ISSUE TITLE
Cassandra implementation of the FunctionalMailboxRepository

### ISSUE THREAD

**Issue by Arsnael** [linagora/tmail-backend#255]
Following #254, you will implement the Cassandra version of the `FunctionalMailboxRepository`. The DAO will create the pair INBOX and Sent mailboxes in mailbox table for the FM. The DAO can be defined following this:
```
FunctionalMailboxDAO:
  - create(f: FunctionalMailbox): Publisher[Void]
  - delete(f: FunctionalMailbox): Publisher[Void]
  - list(domain: Domain): Publisher[FunctionalMailboxes]
```

DoD: Cassandra implementation + unit tests

**Comment by chibenwa** [comment]
Non sense: We use directly the MailboxManager to store this - we do not need additional structures.
