### ISSUE TITLE
Modularize Namespace of mailbox share extension in James

### ISSUE THREAD

**Issue by vttranlina** [linagora/tmail-backend#267]
Move the `org.apache.james.jmap.mail.MailboxNamespace` and related to separate module, 
make it generic and usable for custom things to be able to use it

**Comment by vttranlina** [comment]
it should in #jame-project

**Comment by chibenwa** [comment]
-> This needs to be open on `linagora/james-project` github project
 
 `make it generic and usable for custom things` -> How? Why? (I have already answered these questions here: https://www.mail-archive.com/server-dev@james.apache.org/msg71116.html **## Being able to specify custom namespaces in JMAP Mailbox/get**)
