### ISSUE TITLE
Builiding without installing artifacts

### ISSUE THREAD

**Issue by rouazana** [linagora/tmail-backend#27]
The building documentation tells that we need to build with `mvn clean install`. As far as I know it is a bad practice and it is preferred to do `mvn clean package` to not fill your .m2 we temporary snapshots artifacts.
Is there a way to build this project without installing the artefacts?

Bonus question: when skipping the tests with `-DskipTests` does it skip them for apache/james only or for both? Then how to build apache/james without the tests and linagora/openpaas-james with the tests?

Finally I don't get why we need this git submodule trick. Why not just asking apache/james to deliver the snaphshots on a regular basis (on commit for example) on the Apache Nexus?

**Comment by Arsnael** [comment]
I think for the `mvn clean install` it is because you have packages like the jmap temporary one that are used by the apps but not present then when you are trying to generate the docker with jib directly on an app. However it was at first, I guess it could change, specially since the mob yesterday where we put the build with jib part of the maven lifecycle. So maybe you could do with that a `mvn clean package` and it would build your containers at once with this.

Why is `mvn clean install` a bad practice btw? Just curious.

When using `-DskipTests` it skips for both. 

git submodule trick allows us to always have the latest code at hand, but also maybe you could be working on something and see there is a bug in apache/james and being able to fix it in the same time also I would say?

**Comment by chibenwa** [comment]
No objections to do a mvn package, but then you always need to build the full project.

**Comment by chibenwa** [comment]
> Then how to build apache/james without the tests and linagora/openpaas-james with the tests?

```
mvn clean install -DskipTests
cd openpaas-james
mvn clean package
```

Does the trick for me.
```

**Comment by chibenwa** [comment]
> Finally I don't get why we need this git submodule trick. Why not just asking apache/james to deliver the snaphshots on a regular basis (on commit for example) on the Apache Nexus?

Because while working on Openpaas James I might need to do changes in Apache James.

Example: https://github.com/linagora/openpaas-james/pull/25

That's REALLY valuable.

**Comment by rouazana** [comment]
> > Then how to build apache/james without the tests and linagora/openpaas-james with the tests?
> 
> ```
> mvn clean install -DskipTests
> cd openpaas-james
> mvn clean package
> ```
> 
> Does the trick for me.

In which directory is issued the first command?

**Comment by rouazana** [comment]
> Why is `mvn clean install` a bad practice btw? Just curious.

As I told: "to not fill your .m2 we temporary snapshots artifacts" (s/we/with). When you are building a product you have chances to get the local artifact instead of the real one, and to build a product depending on temporary (from a PR or from old code) artifacts.

**Comment by rouazana** [comment]
It seems the main issue here is related to the IDE. What prevents you from setting your IDE to look for sources at the same time in the apache/james and in the linagora/openpaas-james repositories? (I'm pretty sure this is feasible without relying on git submodule)

**Comment by Arsnael** [comment]
> to get the local artifact instead of the real one, and to build a product depending on temporary (from a PR or from old code) artifacts.

But as I believe said before, what if we need to modify both repos to see the result? How can we test it if we don't have james local changes as well taken into account? we wait for a merge on the apache repo?

How is a git submodule a "trick" btw? When you read the description of git submodules:

```
It often happens that while working on one project, you need to use another project from within it. Perhaps it’s a library that a third party developed or that you’re developing separately and using in multiple parent projects. A common issue arises in these scenarios: you want to be able to treat the two projects as separate yet still be able to use one from within the other.

[...]

Git addresses this issue using submodules. Submodules allow you to keep a Git repository as a subdirectory of another Git repository. This lets you clone another repository into your project and keep your commits separate.
```

Isn't that our case? I would say configuring the IDE as you describe above sounds more like a trick than this TBH^^'
