### ISSUE TITLE
Implement .well-known/webfinger

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-backend#326]
https://openid.net/specs/openid-connect-discovery-1_0.html

| WebFinger   Parameter|	Value |
|resource |	https://jmap.linagora.com/ |
|host |	jmap.linagora.com |
|rel |	http://openid.net/specs/connect/1.0/issuer |

```
GET https://jmap.linagora.com/.well-known/webfinger
    ?resource=https%3A%2F%2Fjmap.linagora.com
    &rel=http%3A%2F%2Fopenid.net%2Fspecs%2Fconnect%2F1.0%2Fissuer
    HTTP/1.1
  HTTP/1.1 200 OK
  Content-Type: application/jrd+json

  {
   "subject": "https://jmap.linagora.com/oidc",
   "links":
    [
     {
      "rel": "http://openid.net/specs/connect/1.0/issuer",
      "href": "https://auth.linagora.com/auth/realms/jmap"
     }
    ]
  }
```

This enable then the client to `GET https://auth.linagora.com/auth/realms/jmap/.well-known/openid-configuration`...

DOD

 - Write an ADR explaining the problem, the solution and its limitations
 - implement an optional endpoint on the TMail JMAP server exposing webfinger
 - Takes as a configuration parameter the subject, the id.provider.url
 - HELM chart endpoint using this to support OpenID discovery

**Comment by Arsnael** [comment]
Now that I reread that... Helm chart? Do we? Isn't just that part of the jmap endpoint?

However maybe we need to add it in Krakend?

**Comment by chibenwa** [comment]
I mean: we need to configure that endpoint in krakend helm chart yes of course.

**Comment by Arsnael** [comment]
yeah mixed up with James sorry :)
