### ISSUE TITLE
Loading cache abstraction and configuration option for RateLimitingPlan repo

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-backend#344]
Caching per domain entities that are often queries will yield huge benefits.

This could be configured via options of the mailets?

**Comment by quantranhong1999** [comment]
Do we have anywhere in James using Caching Abstraction yet?

**Comment by vttranlina** [comment]
> Do we have anywhere in James using Caching Abstraction yet?

You can search `com.google.common.cache.LoadingCache`
good luck

**Comment by vttranlina** [comment]
btw, CaffeeIn Cache look like is better than Guava Cache 
https://github.com/ben-manes/caffeine

We can try it, or not, because it isn't necessary to add more lib dependency, more heavy

**Comment by chibenwa** [comment]
caffein is used by Cassandra dudes, for sure it is the hell of a good library, though we got limited caching use cases, thus Im usure of 'adding yet another dependency'. What would be the gains of caffein vs LoadingCache?

**Comment by vttranlina** [comment]
> What would be the gains of caffein vs LoadingCache?

I read some topics that written caffeine has better performance (in more case)

**Comment by chibenwa** [comment]
> I read some topics that written caffeine has better performance (in more case)

Early optimisation is the route of all evils. Our cache usage is likely light, thus I would keep good old borring tech...
