### ISSUE TITLE
Reindex task to create domain contacts

### ISSUE THREAD

**Issue by Arsnael** [linagora/tmail-backend#363]
Create a reindexing task to create/update/fix inconsistencies for domain contacts.

We could have different modes:
* `rebuildAll`: it drops the index entries prior to reindexing and rebuilds the domain contacts index. Should be the default mode
* `fixOutdated`: 
  * For each domain on TMail server:
  * list contacts of the domain -> add missing ones to the index
  * list indexed domain contacts -> remove ones not present in UsersRepository anymore

An example could be:

```
curl -XPOST http://ip:port/domains/contacts?task=reIndex&mode=rebuildAll
```

**DoD**: Integration tests

**Comment by chibenwa** [comment]
Can we get a curl example of what to implement?

Task parameters also?

**Comment by chibenwa** [comment]
Not needed with a LSC script
