### ISSUE TITLE
Set up TMail event bus, event for new contacts, listener to index

### ISSUE THREAD

**Issue by Arsnael** [linagora/tmail-backend#364]
Reusing the event bus generalization, we can add a new one for TMail that will take care of handling events proper to TMail server, like for the contacts. 

We can identify the Tmail event bus with the NamingStrategy `tmailEvent`.

We need to implement new events for contacts, like this:

```
trait TmailEvent implements Event

trait TmailContactUserEvent(eventId: EventId, username: Username, contact: MailAddress, firstname: String, lastname: String) implements TmailEvent

case class TmailContactUserAddedEvent(eventId: EventId, username: Username, contact: MailAddress, firstname: String, lastname: String) implements TmailContactUserEvent
```

Then we need a new listener to listen to those events and index new contacts : `TmailContactListener`

**DoD**: integration tests showing when we fire TmailContactEvents on the Tmail event bus, the listener indexes them well

**Comment by chibenwa** [comment]
-> we will get more complex events for contacts: Create? Delete? Belonging to a user or a domain? Potentially updates...

**Comment by Arsnael** [comment]
I get the future concern but for now we only treat Added contact events right? not delete not update? I just modified to give space to future updates but only using what we need now.

**Comment by chibenwa** [comment]
Yes they can be added later on.

**Comment by chibenwa** [comment]
TODO take into account names

**Comment by chibenwa** [comment]
TmailContactDomainEvent not needed

**Comment by Arsnael** [comment]
Updated
