### ISSUE TITLE
Create a custom ES auto-complete analyzer in James

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/tmail-backend#366]
## Why 
CF: https://github.com/linagora/tmail-backend/issues/365#issuecomment-1073500063
Elasticsearch's search_as_you_type field uses Edge N-gram filter which is not convenient for our use case (email address). 
We need to create a custom analyzer which base on [N-gram filter](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-ngram-tokenfilter.html?baymax=rec&rogue=rec-1&elektra=guide)

## How
- Add a custom analyzer in `IndexCreationFactory`
Something to notice about: by default the denta between max_gram and min_gram <= 1 which is likely not enough for our case => may need to increase it by specify `index.max_ngram_diff`.

## DoD
- Unit tests the custom analyzer

**Comment by chibenwa** [comment]
Duplicate https://github.com/linagora/james-project/issues/4466
