### ISSUE TITLE
WebAdmin API to create, update, list, delete, get contacts

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-backend#367]
## Why?

We want to include firstName and familyName to contacts when possible.

This information is available on the LDAP thus we will need to synchronise it too.

## API proposal

Listing contacts:

```
curl -XGET http://ip:port/domains/domain.tld/contacts

will return a list of contact mail addresses:

["mailAddress1", "mailAddress2"]
```

Getting contacts: (not a priority)

```
curl -XGET http://ip:port/domains/domain.tld/contacts/btellier

will return the detail of the contact:

{
    "id": "id1",
    "emailAddress": "btellier@domain.tld",
    "firstname": "Tellier",
    "surname": "Benoit"
}
```

Note that firstname and surname are nullable.

Creating a contact:

```
curl -XPOST http://ip:port/domains/domain.tld/contacts

{
    "emailAddress": "btellier@linagora.com",
    "firstname": "Tellier",
    "surname": "Benoit"
}
```

Will return 201, using the location header to communicate the URL of the created entry. Response payload will include the id:

```
Location: /domains/domain.tld/contacts/btellier
{
    "id": "id1"
}
```

Delete a contact:

```
curl -XDELETE http://ip:port/domains/domain.tld/contacts/btellier
```

Update a contact:

```
curl -XPUT http://ip:port/domains/domain.tld/contacts/btellier

{
    "firstname": "Tellier",
    "surname": "Benoit"
}
```

All fields are nullable.

Listing all contacts of all domains:

```
curl -XGET http://ip:port/domains/contacts

will return a list of contact mail addresses from all domains:

["mailAddress1", "mailAddress2", "mailAddress3"]
```

**Comment by Arsnael** [comment]
Got an issue with formatting, otherwise I'm good :)

**Comment by chibenwa** [comment]
As discussed on another issue we would like to support auto-completion of firstname, familyname when available.

Thus we would need to add them to the contact POJO, and index them as well.

Can we handle such changes in this ticket too?

Cc @quantranhong1999

**Comment by quantranhong1999** [comment]
> Can we handle such changes in this ticket too?

yes. I will modify them.

**Comment by vttranlina** [comment]
When grooming, we talked about it won't contain the UPDATE API, is it oke? or did we forget something?

**Comment by Arsnael** [comment]
> When grooming, we talked about it won't contain the UPDATE API, is it oke? or did we forget something?

As I understand, @quantranhong1999 made a suggestion to add also the autocomplete not only on email address but also on firstname and surname. 

Thus we need to sync all of those with a LSC script against the LDAP. So to be able to sync correctly the info with LDAP, you need the CRUD. If a name gets changed on LDAP for example, you need to update it :)

**Comment by quantranhong1999** [comment]
> > Can we handle such changes in this ticket too?
> 
> yes. I will modify them.

Updated. And create a new ticket: https://github.com/linagora/tmail-backend/issues/375

Q: Why do we separate the first name and surname (but not put it into only 1 full name)? What if MUA/contact app just support extract fullname?

**Comment by chibenwa** [comment]
> Q: Why do we separate the first name and surname (but not put it into only 1 full name)? What if MUA/contact app just support extract fullname?

Contact apps have the 2 fields. If we need to we can put that into the familyName field with the surname field empty.

**Comment by quantranhong1999** [comment]
Can we have an API to get all domain contacts regardless of which domain? (I think LSC service' getListPivots method needs it).
curl -XGET http://ip:port/domains/contacts

**Comment by Arsnael** [comment]
PR : https://github.com/linagora/tmail-backend/pull/404

**Comment by chibenwa** [comment]
> Can we have an API to get all domain contacts regardless of which domain? (I think LSC service' getListPivots method needs it).
> curl -XGET http://ip:port/domains/contacts

Makes sense...

**Comment by quantranhong1999** [comment]
Avoid duplicated Test if a domain exists route's path:
https://github.com/linagora/tmail-backend/pull/407
