### ISSUE TITLE
JMAP EmailAddress auto-completion method

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/tmail-backend#368]
## Why 
This JMAP API can be used by mobile apps/web mail to get auto-complete results (can be used by mobile apps to provide more results).

## How
This is a custom method that takes inspiration from [a standard “/query” method](https://jmap.io/spec-core.html#query).
Request:
```json
[
	[
		"TMailContact/autocomplete", {
			"accountId": "29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6",
			"filter": {
				"text": "tran"
			}
		},
		"c1"
	]
]
```

Response:
```json
[
	[
		"TMailContact/autocomplete",
		{
			"accountId": "29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6",
			"list": [{
                                "id": "1",
				"firstname": "Quan",
				"surname": "Tran",
				"emailAddress": "hqtran@linagora.com"
			}, {
                                "id": "2",
				"firstname": "Tung",
				"surname": "Tran",
				"emailAddress": "vttran@linagora.com"
			}]
		},
		"c1"
	]
]
```

## DoD
- Contract tests

**Comment by chibenwa** [comment]
While I mostly agree `/query` should return an `id` and not a `mail address`. I suggest calling the method `Contact/autocomplete`.

Furthermore a MUA can be interested for display infos of recipients to be specifying `Benoit Tellier <btellier@linagora.com>` instead of just `btellier@linagora.com`.

I think we should be returning directly contact POJOs.

**Comment by chibenwa** [comment]
By not doing a `/query` method we can remove `canCalculateChanges` and `limit` from the response.

**Comment by chibenwa** [comment]
Missing `id` for auto-completion suggestions.

**Comment by chibenwa** [comment]
Missing limit...

Server needs to enforce an upper limit. if server modifies the client specified limit, it should be in the result.

Also we need to document the session capability associated with this.

**Comment by chibenwa** [comment]
queryState is likely not relevant
