### ISSUE TITLE
LSC to sync contacts

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-backend#370]
# Why

Synchronize mail address, firstname, surname of LDAP entries

# How

Leveraging #367 write a TMail LSC script for synchronising contacts with a LDAP

**Comment by quantranhong1999** [comment]
MOB prefer

**Comment by quantranhong1999** [comment]
https://github.com/lsc-project/lsc-james-plugin/pull/4

**Comment by chibenwa** [comment]
My question is...

In the end this is TMail specific... Not really related to James.

Shouldnt we have a dedicated tmail-lsc for this?

**Comment by quantranhong1999** [comment]
Fork PR: https://github.com/linagora/tmail-lsc/pull/1

**Comment by quantranhong1999** [comment]
Setup James jenkins for TMail LSC: https://ci.linagora.com/rcordier/james-ci/-/merge_requests/20

**Comment by quantranhong1999** [comment]
Sync contact PR (reopened at our tmail-lsc): https://github.com/linagora/tmail-lsc/pull/2

**Comment by quantranhong1999** [comment]
A fix to correctly sync firstname and surname: https://github.com/linagora/tmail-lsc/pull/3

Tested and work smoothly on preprod.
- GET https://james-admin.upn.integration-open-paas.org/domains/upn.integration-open-paas.org/contacts
=> Many duummy contacts

- GET https://james-admin.upn.integration-open-paas.org/domains/parisnanterre.fr/contacts/jumeyer
```json
{
    "id": "3a1bdca2-6f3f-3226-a7a8-9e7efc307dd6",
    "emailAddress": "jumeyer@parisnanterre.fr",
    "firstname": "Julie",
    "surname": "Meyer"
}
```
- GET https://james-admin.upn.integration-open-paas.org/domains/upn.integration-open-paas.org/contacts/firstname461.surname461
```json
{
    "id": "b44bfa90-b892-3ef6-8baf-53824d7e4b97",
    "emailAddress": "firstname461.surname461@upn.integration-open-paas.org",
    "firstname": "Firstname461",
    "surname": "Surname461"
}
```

**Comment by quantranhong1999** [comment]
However, the GET ALL contacts route looks like not working properly as we expected:

- GET https://james-admin.upn.integration-open-paas.org/domains/contacts
```json
{
    "statusCode": 404,
    "type": "InvalidArgument",
    "message": "The domain list does not contain: contacts",
    "details": null
}
```

This is because we duplicated James domain route: 
![image.png](https://images.zenhubusercontent.com/5f7fe3b8b67a756e7c63d181/6c974c5f-2c0f-4df8-a84c-1e7971541989)

We need to change the GET ALL contacts route path.

**Comment by chibenwa** [comment]
> Many duummy contacts

That's a problem. Can we find a way to specify a list of domain to synchronize and not synchronize them all?

**Comment by quantranhong1999** [comment]
> That's a problem. Can we find a way to specify a list of domain to synchronize and not synchronize them all?

I did provide a quick solution here: https://github.com/linagora/tmail-lsc/pull/3
