### ISSUE TITLE
Mailet to collect contacts

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-backend#371]
Write a mailet that saves recipient information into the sendar database:

 - mail address
 - First name
 - Surname 

This mailet will leverage the TMail event bus to ensure we reliably and asynchronously index those.

**Comment by chibenwa** [comment]
Look at ContactExtractor... 

Do a mailet that index and that also does ContactExtractor (put contact info as an attribute)

**Comment by vttranlina** [comment]
I'm confusing a case:
Alice send a mail to Bob
our expected: Bob will have contact of Alice (even Alice is not an internal user)
I'm right?
