### ISSUE TITLE
Proposal AMQP format between Tmail and contact APP

### ISSUE THREAD

**Issue by vttranlina** [linagora/tmail-backend#372]
## Why?
In order to synchronize contact data from external (here is ContactAPP) to Tmail, we need to provide a protocol in TMail for that.
AMQP has been chosen. => We need to define AMQP format 

## How 
We can based on `reactor.rabbitmq.OutboundMessage` 

```java
    private final String exchange;
    private final String routingKey;
    private final BasicProperties properties;
    private final byte[] body;
```

- `body` is a serialized data of contact. 
Example
```json
{
    "emailAddress": "btellier@linagora.com",
    "firstname": "Tellier",
    "surname": "Benoit"
}
```

## DOD
- Create POJO Message and Deserialize message factory

## Ref 
https://www.rabbitmq.com/amqp-0-9-1-reference.html

**Comment by chibenwa** [comment]
For bodies I have a proposal in #369 .

This needs to be discussed with contact team.
