### ISSUE TITLE
Document the feature Auto-complete Contact

### ISSUE THREAD

**Issue by vttranlina** [linagora/tmail-backend#374]
Epic: https://github.com/linagora/tmail-backend/issues/311
Write a doc in https://github.com/linagora/tmail-backend/tree/master/docs

**Comment by chibenwa** [comment]
Includes :

 - [ ] Feature description
 - [ ] JMAP endpoint
 - [ ] Webadmin additions
 - [ ] How to run LSC scripts to sync contacts from a LDAP
 - [ ] AMQP endpoint to sync a contact application
