### ISSUE TITLE
Auto-complete repository should support index contact name

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/tmail-backend#375]
## Why
We need to support auto-complete not only the email address but also the contact name (First name and surname).

## How
- Modify `EmailAddressContact` POJO : adding firstname and surname fields
- Modify `EmailAddressContactSearchEngine:index`: make it support indexing firstname and surname also.
- Modify the InMemory implementation accordingly.

## DoD
- Contract tests

**Comment by chibenwa** [comment]
TODO #362 + #375 bundled in one ticket!

**Comment by quantranhong1999** [comment]
> TODO #362 + #375 bundled in one ticket!

Merged into https://github.com/linagora/tmail-backend/issues/362
