### ISSUE TITLE
Performance tests for contact auto-complete

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-backend#378]
- Write a gatling scenario exercising contact search
 - Run it on preprod
 - Compare with OpenPaaS results.

**Comment by vttranlina** [comment]
- Run it on preprod: wait for lsc script to generate sample data

**Comment by vttranlina** [comment]
Gatling scenario https://github.com/linagora/james-gatling/pull/134

**Comment by quantranhong1999** [comment]
At first, I run the default AC simulation with 5k users, 3 James pods => too much AC req/s leading timeout (>60s auto-complete). It looks like the ES bottleneck.

I reduced the AC throughput by pausing it every 2 seconds.

### 1k users, ~300 mean AC req/s, peek 500 req/s
![image.png](https://images.zenhubusercontent.com/5f7fe3b8b67a756e7c63d181/b5b54aed-6f26-47b5-97e8-6340ca74e93d)

```
Please open the following file: /home/hqtran/repo/james-gatling/target/gatling/tmailcontactautocompletesimulation-20220428053320298/index.html
```

**Comment by Arsnael** [comment]
Indeed... I just rechecked the simulation, no pause is too much and not really realistic either.

Wondering if shouldn't even put the pause a bit higher...

**Comment by quantranhong1999** [comment]
> Indeed... I just rechecked the simulation, no pause is too much and not really realistic either.

In `during` section, we had been sending the auto-complete request repeatedly ([up to 4 millions request in 200 seconds](https://github.com/linagora/james-gatling/pull/134#issuecomment-1097831564))

**Comment by Arsnael** [comment]
Yes we should add a pause :)

**Comment by quantranhong1999** [comment]
> Yes we should add a pause :)

https://github.com/linagora/james-gatling/pull/137

**Comment by quantranhong1999** [comment]
### 1k2 users, mean ~350 req/s, peek ~600 req/s disabled glowroot, warmed up
![image](https://user-images.githubusercontent.com/55171818/165722487-7d795924-b852-4029-89c0-0a6b8c74fd42.png)

```
Please open the following file: /home/hqtran/repo/james-gatling/target/gatling/tmailcontactautocompletesimulation-20220428085742516/index.html
```

I think we can say our Auto-complete is at 350 request/s.

**Comment by vttranlina** [comment]
> ### 1k2 users, mean ~350 req/s, peek ~600 req/s disabled glowroot, warmed up

How many contacts?
