### ISSUE TITLE
Add update and delete in EmailAddressSearchContact API

### ISSUE THREAD

**Issue by Arsnael** [linagora/tmail-backend#385]
After #362, we can add also the update and delete operations in the API for being able to handle later the CRUD with the LSC synchronization.

```
def update(domain: Domain, fields: ContactFields): Publisher[EmailAddressContact]

def update(accountId: accountId, fields: ContactFields): Publisher[EmailAddressContact]

def delete(domain: Domain, address: MailAddress): Publisher[Void]

def delete(accountId: accountId, address: MailAddress): Publisher[Void]
```

**DoD**: Add unit tests in the existing contract

**Comment by chibenwa** [comment]
> def update(domain: Domain, fields: ContactFields)

I should have a way to patch only some of the fields. Think `PATCH`. Maybe we will need a newer POJO to represent this.

**Comment by Arsnael** [comment]
I don't think we need the patch... we should not have much operations like this performed, better to not complexify the API more.

Also for domains with ldap and lsc, the email would be the pivot. If there is an update on the name, we change it. If the email change though, via ldap it should be perceived as a delete of the old one and creation of a new one (so delete + create, no update)

On the third party contact client side, maybe trickier. For name change I think it's the same principle, but how should we tackle email change? delete + create or update with old value and new value as params?

**Comment by Arsnael** [comment]
PR on tmail: https://github.com/linagora/tmail-backend/pull/391

Upsert method on James
JIRA: https://issues.apache.org/jira/browse/JAMES-3750
PR: https://github.com/apache/james-project/pull/965
