### ISSUE TITLE
Demo Contact autocomplete feature

### ISSUE THREAD

**Issue by vttranlina** [linagora/tmail-backend#399]

**Comment by vttranlina** [comment]
# Demo TmailContact/Autocomplete 

## 1. Prepare
- Start Tmail server
- Users is already: 
    - bob@domain.tld
    - andre@domain.tld
    - cedric@domain.tld


## 2. JMAP query TmailContact/Autocomplete

- 2.1 Contact list empty by default
    - bob uses JMAP to filter contacts by text keyword: "andre"
    - Jmap response list is empty

- 2.2 Contact will be added when sending email
    - Bob sends an email to Andre  (use SMTP)
    - await a few seconds (for background job)
    - Bob uses JMAP to filter contacts by text keyword: "andre"
    - Jmap response contains Andre's contact

- 2.3 Autocomplete filter logic
    - Bob sends an email to Cedric
    - await a few seconds to add Cedric's contact (the contact owner is Bob)
    - Change the text filter in JMAP and observe the results

## Ref 
- Jmap TMailContact/autocomplete rest example:
```bash
curl --location --request POST 'localhost:38659/jmap' \
--header 'Accept: application/json; jmapVersion=rfc-8621' \
--header 'Authorization: Basic Ym9iQGRvbWFpbi50bGQ6Ym9icGFzc3dvcmQ=' \
--data-raw '{
    "using": [
        "urn:ietf:params:jmap:core",
        "com:linagora:params:jmap:contact:autocomplete"
    ],
    "methodCalls": [
        [
            "TMailContact/autocomplete",
            {
                "accountId": "29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6",
                "filter": {
                    "text": "Andre1"
                }
            },
            "c1"
        ]
    ]
}'
```
Response example:
```json
{
    "sessionState": "2c9f1b12-b35a-43e6-9af2-0106fb53a943",
    "methodResponses": [
        [
            "TMailContact/autocomplete",
            {
                "accountId": "29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6",
                "list": [
                    {
                        "id": "1d684cf0-101b-300b-82c0-8e17f8d464bc",
                        "emailAddress": "andre@domain.tld",
                        "firstname": "Andre1",
                        "surname": ""
                    }
                ],
                "limit": 256
            },
            "c1"
        ]
    ]
}
```

**Comment by vttranlina** [comment]
Video demo: 
https://user-images.githubusercontent.com/81145350/163340287-a85c09bc-bd79-473d-b627-1632fb9de48f.mp4

**Comment by vttranlina** [comment]
## Video demo
https://user-images.githubusercontent.com/81145350/163342025-54382b30-b4e8-4509-a935-6bb4e6776073.mp4

Linshare: https://linshare-internal.linagora.com/#!/sharedspace/workgroups/b77d3d86-0569-411a-9050-fccb485709e2/James-team/485f5ea0-d060-48ac-9a7c-89fa46016b16/Sprint%2019

**Comment by Arsnael** [comment]
Nice demo!

**Comment by chibenwa** [comment]
Please paste a screenshot to gatling here too

**Comment by vttranlina** [comment]
Gatling screenshot result
![screencapture-file-home-tungtv-Downloads-tmailcontactautocompletesimulation-20220414043410205-index-html-2022-04-15-09_17_42](https://user-images.githubusercontent.com/81145350/163507456-c18bc7bb-ca63-42d5-a22e-c3e5c021e672.png)

![screencapture-file-home-tungtv-Downloads-tmailcontactautocompletesimulation-20220414043410205-req-retrieveaccount-26cf4-html-2022-04-15-09_18_00](https://user-images.githubusercontent.com/81145350/163507447-9710670c-7cf7-4f0d-a3f8-90e762c40b49.png)
