### ISSUE TITLE
Auto-complete should support query domain.tld

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/tmail-backend#400]
While doing the demo, Tung spotted a bug: with a contact's address `tung@domain.tld`, the auto-complete query `domain.tld` is not working.

Meanwhile, the case for `tung@linagora.com` and query `linagora.com` works normally.

This comes from the weird behavior of `uax_url_email` tokenizer we are using for `email` field:
![image.png](https://images.zenhubusercontent.com/5f7fe3b8b67a756e7c63d181/990e2d34-2548-419c-800b-ba3c39b9054b)

To avoid this weird behavior for other domains, we should use another tokenizer.

Solution:
- Provide a test reproduce this
- Switch `uax_url_email` to `keyword` tokenizer for `email` field.

**Comment by Arsnael** [comment]
Hmmmm... I get the point, i agree it's a valid point objectively speaking. But is it worth it?

Do we really want to show potentially a list of hundreds of people belonging to a domain? The cost can be potentially heavy?

**Comment by quantranhong1999** [comment]
> Do we really want to show potentially a list of hundreds of people belonging to a domain? The cost can be potentially heavy?

I think we already allow a range let's say default from 3 to 30 characters. And then whatever the user wants to query, we can not deny their need. 
The cost can be reduced by `limit` property or even on Frontend size?

**Comment by chibenwa** [comment]
IMO trying to rewrite `uax_url_email` is not necessarily meaningfull, my instinct would say: stay clear from this...

`tld` is likely not a registered top level domain...

**Comment by quantranhong1999** [comment]
> tld is likely not a registered top level domain...

Ok, that's why the `uax_url_email` tokenizer behaves like that. Let's skip this.
