### ISSUE TITLE
documentation help !

### ISSUE THREAD

**Issue by ditsly** [linagora/tmail-backend#401]
Hello there, 

thank you for these great features with this app, but actually, I can't find any video or documentation to learn me how to install it! also, I'm trying for 3 weeks but I can't find the solution to install it. 

please can you provide a video tutorial or something about installation?

**Comment by chibenwa** [comment]
Hello,

Thanks for your interest in our project.

Did you got a look at the doc folder? https://github.com/linagora/tmail-backend/tree/master/docs/modules/ROOT/pages

Running TMail should actually be quite easy: https://github.com/linagora/tmail-backend/blob/master/docs/modules/ROOT/pages/tmail-backend/run.adoc

Regards,

Benoit
