### ISSUE TITLE
Try out JRE 18 for TMail

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/tmail-backend#410]
Java 17 LTS comes with many enhancements and innovations that we can benefit from. E.g: Z Garbage Collector which is powerful, modern, and production-ready in JRE 17.

- [x] Upgrade TMail JRE (maven and docker image)
- [x] Make sure the build and the tests are passed
- [ ] Deploy and testing in preprod
( - [ ] Try out Z Garbage Collector (maybe in another ticket if needed) )

And maybe more things we can try to improve with JRE 17 if appropriate.

**Comment by Arsnael** [comment]
There should still be a way to run it on java11. Not that I don't want to upgrade, actually I would be happy with it, but the LNG prod VM is always a bit tricky and takes more time for an update like that IMO :)

**Comment by chibenwa** [comment]
Java 17 -> Java 18 JRE.

Java 18 ships MANY GC improvments especially on memory overhead.

**Comment by Arsnael** [comment]
Java18 is not LTS though... I'm not very keen on that

**Comment by chibenwa** [comment]
(answered on signal)

Released JREs are all stable even non LTS

it's TMail only ;-)

by just doing a Java 11 -> Java 18 JRE drop in replacement you get a 10% improvment on G1GC. Not to mention other enhancements (vectorization?)
