### ISSUE TITLE
JMAP specification for "Always request MDNs" for outgoing messages

### ISSUE THREAD

**Issue by Arsnael** [linagora/tmail-backend#411]
In Openpaas backend, there was an option to allow the user to precise to always send MDN when sending messages. The goal would be to have that in TMail backend now via JMAP.

You need to write the specification like any JMAP specification for always requesting MDNs on outgoing messages.

For this we can say:
- adding a empty capability `com:linagora:params:jmap:mdn:alwayssend`
- a new singleton object `TMailMDNAlwaysSend` (like for `VacationResponse`) with one field:
  - `MDNAlwaysSend`: boolean. if true, client should always send MDN with outgoing messages. Defaults to false.
- two methods:
  - `TMailMDNAlwaysSend/get`
  - `TMailMDNAlwaysSend/set`

**Comment by chibenwa** [comment]
How is this stored?

**Comment by Arsnael** [comment]
Not the job of the spec to say that IMO, that's described in the implementation ticket
