### ISSUE TITLE
Implement "always request MDNs" for outgoing messages

### ISSUE THREAD

**Issue by Arsnael** [linagora/tmail-backend#412]
You need to implement "always request MDNs" for outgoing messages based on the JMAP spec written in https://github.com/linagora/tmail-backend/issues/411 for memory and Cassandra.

A cassandra table for storing this could be like this:

```
TMailMDNAlwaysSend: 
  - username `PK` (string)
  - MDNAlwaysSend `Column` (boolean)
```

For example:

- /get
```
{
  "using": [
    "urn:ietf:params:jmap:core",
    "com:linagora:params:jmap:mdn:alwayssend"],
  "methodCalls": [[
    "TMailMDNAlwaysSend/get",
    {
      "accountId": "29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6",
      "ids": null
    },
    "c1"]]
}

Will return:

{
  "sessionState": "12345",
  "methodResponses": [[
    "TMailMDNAlwaysSend/get",
    {
      "accountId": "29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6",
      "state": "67890",
      "list": [
        {
          "id":"singleton",
          "MDNAlwaysSend": false
        }
      ],
      "notFound": []
    },
    "c1"]]
}
```

- /set
```
{
  "using": [
    "urn:ietf:params:jmap:core",
    "com:linagora:params:jmap:mdn:alwayssend"],
  "methodCalls": [
    ["TMailMDNAlwaysSend/set", {
      "accountId": "29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6",
      "update": {
        "singleton": {
          "MDNAlwaysSend": true
        }
      }
    }, "c1"]
  ]
}

Will return:

{
"sessionState": "12345",
  "methodResponses": [
    ["TMailMDNAlwaysSend/set", {
      "accountId": "29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6",
      "newState": "67890",
      "updated": {
        "singleton": {}
      }
    }, "c1"]]
}
```

**DoD**: mem and cassandra implems with integration tests

**Comment by quantranhong1999** [comment]
Other examples for this could be Filter/get Filter/set.
Should we support `ifInState`?

**Comment by Arsnael** [comment]
I said in the spec ticket that it is a singleton object, so very similar to VacationResponse (but Filter is one too)

> Should we support ifInState?

I don't think it's necessary on a singleton object honestly?

**Comment by quantranhong1999** [comment]
> I don't think it's necessary on a singleton object honestly?

I look at Filter/set test and see `ifInState`, not sure about this too but my feeling is no need.
BTW we may need to deal with the logic of how to `always request MDN when sending mail` (checking through AlwaysMDNs API).

**Comment by Arsnael** [comment]
VacationResponse does not have `ifInState`. It's a very simple singleton object with one field, Filter is much more complex...

> BTW we may need to deal with the logic of how to always request MDN when sending mail (checking through AlwaysMDNs API).

I disagree. I would think more like it's the job of the frontend. It gets the preference of the user for always request MDNs or not, and if yes, when sending the email the client can add a jmap method MDN/send (we already have this :) )
