### ISSUE TITLE
JMAP spec for forward

### ISSUE THREAD

**Issue by vttranlina** [linagora/tmail-backend#413]
Email forwarding is a way to set up alternative email addresses that forward emails to the other email address.

## Current flow
- TMail(front) -> OpenPass(back) -> James (via webadmin `ForwardRoutes` )
- ForwardRoutes will use the `RecipientRewriteTable` for forward

## JMAP flow (new flow)
- TMail(front) call directly to James by JMAP to store RRT
- Keep current logic `RecipientRewriteTable` for forward

- New JMAP capability: `com:linagora:params:jmap:mailforward`
- Provide two JMAP methods
    - Forwards/Get
    - Forwards/Set: ( create + delete are forbidden)

Local copy + no forwards are the default.
Forwards objects have the following field:

- localCopy (yes, no, boolean)
- addresses: Optional[List[String]] addresses to which the emails should be forwarded.

**Comment by Arsnael** [comment]
> TMailMailForward/Get, we needn't implement filter logic, just get all for simpler? (the result is small)

I would say yes. I would see this as a singleton object and the /set updates the all object (like for Filter)

> When creating a new mail forward configure, should we have a confirmation step? (Gmail sends a Confirmation code to forward email)

I don't think we need to... But I'm not completely sure TBH

**Comment by chibenwa** [comment]
Forwards/get + Forward/set

This should be a singleton object attached to the account (no need account id)

Forwards object have the following field:

 - localCopy (yes, no, boolean)
 - addresses: Optional[List[String]] addresses to which the emails should be forwarded.
 
 Forward set create + delete are forbidden. Local copy + no forwards is the default.
 
 We should require no extra data structure for this, we should solely use RRTs.

**Comment by chibenwa** [comment]
I would like us to stick to the existing OpenPaaS work.

**Comment by vttranlina** [comment]
Some note:
- `localCopy` is just a forwarding for themself. Example: localCopy=true, create one more RRT, with the destination being "owner@domain.org"

**Comment by chibenwa** [comment]
> Don't need accountId in the request

Sorry this might be a mistake from me, we would benefit from having the accountId just like Vacations... Sorry my fault.
