### ISSUE TITLE
Demo Sprint 19 result

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/tmail-backend#416]
## What we will demo:

- Contact auto-completion feature with LDAP synchronization

- Contact auto-completion feature with AMQP synchronization (optional)

- Improved IMAP Performance

#### Then
We can take TMail 0.5.0 IMAP performance as a comparison milestone (just relatively cause diff simulation and pods number).
![image.png](https://images.zenhubusercontent.com/5f7fe3b8b67a756e7c63d181/17b434cc-9d6c-4b2a-be96-da4b0436f16d)

#### Now
Our IMAP can handle up to 2000 req/s with a good response time.
![image.png](https://images.zenhubusercontent.com/5f7fe3b8b67a756e7c63d181/f66837f1-0b1c-4a4b-8c2f-0a5ad563bee3)

We can say more about the performance/metric tools if people are interested.

#### Demo Script
- Run an LSC script on preprod (quickly skip cause already ran it)
- Query a few web admin routes to see some domain contact information:
  - GET contacts of a domain (eg upn.integration-open-paas.org, parisnanterre.fr)
  - GET detail of a domain contact (e.g firstname1.surname1@upn.integration-open-paas.org, jumeyer@parisnanterre.fr)
- Login as user A (e.g firstname1.surname1@upn.integration-open-paas.org), query some Auto-complete script:
  - A can query successfully (eg with firstname19999, surname19999, firstname19999.surname19999@upn.integration-open-paas.org, firstname1999, upn.integration-open-paas.org,...).
  - A can only query contact in his domain (eg upn.integration-open-paas.org) and not other domains:
    - A try to query `parisnanterre.fr` domain contacts => return empty
 
#### Video

https://user-images.githubusercontent.com/55171818/166896644-54cdc846-a6c0-4f43-abe1-876ffd365d69.mp4

[Linshare](https://linshare-internal.linagora.com/#!/sharedspace/workgroups/b77d3d86-0569-411a-9050-fccb485709e2/James-team/283cfbc9-81cb-4399-8d21-889063362621/Sprint%2019%20(30_04-05_05_2022))
### Contact auto-completion feature with AMQP synchronization

I did not succeed deploy the TMail with AMQP synchronization change on preprod (have some issues with helm james). @ducnm0711 is busy and will not be able to help solving this soon.
Let's say we let this be demoed when we plug the real contact app? Otherwise another effort on this is welcome :')

**Comment by vttranlina** [comment]
> I did not succeed deploy the TMail with AMQP synchronization change on preprod (have some issues with helm james).

Your mean is to create a new rabbitmq? if Yes, It is unnecessary, we can re-use a current rabbitmq (for tmail)

>Let's say we let this be demoed when we plug the real contact app?
IMO, not need, we can use rabbitmq webadmin, and try to publish sample messages, then follow new contact has been indexed

**Comment by quantranhong1999** [comment]
> Your mean is to create a new rabbitmq? if Yes, It is unnecessary, we can re-use a current rabbitmq (for tmail)

![image.png](https://images.zenhubusercontent.com/5f7fe3b8b67a756e7c63d181/a72377b0-59f0-4e76-bfcf-c235b858abc9)
The problem as I said is about helm, not related to rabbitmq yet (I tried to point to the same rabbitmq anyway).

> IMO, not need, we can use rabbitmq webadmin, and try to publish sample messages, then follow new contact has been indexed

Can you help with a demo locally?

**Comment by vttranlina** [comment]
> Can you help with a demo locally?

Of course, let me record a video

**Comment by vttranlina** [comment]
# Contact auto-completion feature with AMQP synchronization

## 1. Prepare
- Users is already:
    - bob@domain.tld

- Rabbitmq publisher (publishing AQMP messages to contact synchronization)
    - Use webadmin rabbitmq tool

## 2. Demo
- Add a new contact AQMP-message
```json
{
  "type": "addition",
  "scope": "user",
  "owner" : "bob@domain.tld",
  "entry": {
    "address": "alice@domain.tld",
    "firstname": "Alice",
    "surname": "Watson"
  }
}
```

- Remove a contact AQMP-message

```json
{
  "type": "removal",
  "scope": "user",
  "owner" : "bob@domain.tld",
  "entry": {
    "address": "alice@domain.tld",
    "firstname": "Bob",
    "surname": "Parker"
  }
}
```

https://user-images.githubusercontent.com/81145350/166905379-8031fd7f-f2f0-4e1c-8ae4-482bbfb954c5.mp4

**Comment by Arsnael** [comment]
@quantranhong1999 why you didn't ask me then? You know I'm doing ok with Helm, I wrote the james chart one :P

Seeing your error my guess is it's like last time, Duc added some secrets manually with Lens quicky dirty, and it clashes with Helm now. I will take a look :)

**Comment by Arsnael** [comment]
After rewatching your demo @quantranhong1999 , don't we have a problem with the limit? we put a default limit to 256 but we return just 10 results max right? (as we don't want any scrolled search in es here). 

Maybe we should change the default max limit to 10 then?

**Comment by quantranhong1999** [comment]
> we put a default limit to 256 but we return just 10 results max right?

I think this solves your concern: https://github.com/linagora/tmail-backend/commit/5708874fa4e8266884c485abd96e3ee34fef3d00

> (as we don't want any scrolled search in es here)

I checked again, we are doing scroll search for web admin listing routes, not related to auto-complete JMAP.
