### ISSUE TITLE
Release TMail backend 0.6.0

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-backend#418]
-  [x] Update james-project master bramch
 -  [x] tag, changelog, software.linagora.com
 -  [x] QA on preprod - IMAP
 -  [x] Perf tests
 -  [x] op.lng.com deployment.

**Comment by Arsnael** [comment]
- Image 0.6.0 tagged, built, pushed on dockerhub
- PR helm-james: https://ci.linagora.com/linagora/lgs/openpaas/packaging/helm-charts/helm-james/-/merge_requests/69
- PR preprod: https://ci.linagora.com/linagora/lrs/saas/deployments/upn/upn-pre-production-emaily-applications/-/merge_requests/45
- 0.6.0 deployed and running on preprod

**Comment by Arsnael** [comment]
software-linagora-com: https://ci.linagora.com/linagora/lgs/software-linagora-com-website/-/merge_requests/37

**Comment by Arsnael** [comment]
# Performance simulations

Setup for every run: warmup with 500 users for 10 minutes, then inject 10k users for 15mins and let them run for 45mins on 2 james pods (alternatively imap and jmap)

## JMAP

### 0.5.0

![screenshot--2022.05.23-17_58_49.png](https://images.zenhubusercontent.com/5ef2b3b0a7d2c63f71b1e1f7/0e620ef2-f925-4d56-9601-0d56d8f7d66d)

### 0.6.0

![screenshot--2022.05.23-17_59_08.png](https://images.zenhubusercontent.com/5ef2b3b0a7d2c63f71b1e1f7/54d56c0d-294d-4f1c-a284-fc2eb5714fdc)

More or less the same. Except some errors in send messages with new release... Unlucky or is there something to dig potentially?

## IMAP

### 0.5.0

![screenshot--2022.05.23-17_54_21.png](https://images.zenhubusercontent.com/5ef2b3b0a7d2c63f71b1e1f7/679b27ce-f3b1-49bf-a4c7-80b077a170e7)

### 0.6.0

![screenshot--2022.05.23-17_54_49.png](https://images.zenhubusercontent.com/5ef2b3b0a7d2c63f71b1e1f7/27a02c18-1773-492f-8d23-c9efa604abdf)

A huge perf boost. Was expected with all the reactive and imap last enhancements

**Comment by chibenwa** [comment]
> More or less the same. Except some errors in send messages with new release... Unlucky or is there something to dig potentially?

Did you collect the logs?

Can we try `mailqueue.publish.confirm.enabled=false` ?

**Comment by Arsnael** [comment]
> Did you collect the logs?

No. Spent the day doing runs and I didn't see that detail at first, only when comparing the results.

> Can we try `mailqueue.publish.confirm.enabled=false` ?

If you want... does that make sense though? If it works without issues on 0.5.0 with no possibilities on disabling them, why not on 0.6.0 then?

**Comment by chibenwa** [comment]
> If you want... does that make sense though? If it works without issues on 0.5.0 with no possibilities on disabling them, why not on 0.6.0 then?

Can you please try?

I suspect channel pool changes to be better without publish confirms but worse with them.

They make the hell of a difference...

**Comment by Arsnael** [comment]
![screenshot--2022 05 24-14_00_22](https://user-images.githubusercontent.com/9005025/169968723-8d5440ee-4b11-4611-8e1c-49255688acd5.png)

Better indeed
