### ISSUE TITLE
Documentation for JMAP forwards

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-backend#419]
- [x] JMAP spec
 - [ ] Cool to get the tmail-flutter story
 - [x] Feature description
 - [x] ADR

**Comment by Arsnael** [comment]
Jmap spec and feature doc: https://github.com/linagora/tmail-backend/pull/429

**Comment by Arsnael** [comment]
ADR: https://github.com/linagora/james-project-private/pull/401

**Comment by Arsnael** [comment]
`Cool to get the tmail-flutter story` => what's that already? saying to mobile team look we have the jmap forwards feature implemented and here is the doc?

**Comment by chibenwa** [comment]
Yes Open a story ticket here, point them to the doc and share with them an OpenPaaS screenshot.

**Comment by Arsnael** [comment]
tmail-flutter story: https://github.com/linagora/tmail-flutter/issues/574
