### ISSUE TITLE
Implement JMAP Forward/Set

### ISSUE THREAD

**Issue by vttranlina** [linagora/tmail-backend#420]
Epic: https://github.com/linagora/tmail-backend/issues/413

## How
- Implement new JMAP Method  `Forward/Set` (based on https://jmap.io/spec-core.html#set)
- Capability: `com:linagora:params:jmap:forward`
- Example
```json
{
    "using": [
        "urn:ietf:params:jmap:core",
        "com:linagora:params:jmap:forward"
    ],
    "methodCalls": [
        [
            "Forward/set",
            {   
                "accountId": "ABC",
                "update": {
                    "singleton": {
                        "localCopy": true,
                         "forwards": [
                           "targetA@domain.org",
                           "targetB@domain.org"
                        ]
                     }
                }
            },
            "0"
        ]
    ]
}
```

## DOD
- JMAP Integration test

## Note
- "create" and "destroy" is forbidden

**Comment by chibenwa** [comment]
> Don't need accountId in the request

Sorry this might be a mistake from me, we would benefit from having the accountId just like Vacations... Sorry my fault.
