### ISSUE TITLE
Experiment Z Garbage Collector

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/tmail-backend#435]
Run a few performance test rounds (IMAP) for G1 (default) and Z, then compare.
May experiment with other GC parameters if appropriate.

**Comment by quantranhong1999** [comment]
At glance, Z GC seems not to bring much performance improvement for us.

### G1 GC
Performance (best of 2 try)
![image.png](https://images.zenhubusercontent.com/5f7fe3b8b67a756e7c63d181/94a4abf3-7cc7-48c0-8154-f9ae8680d1eb)

GC Viewer:
![image.png](https://images.zenhubusercontent.com/5f7fe3b8b67a756e7c63d181/49a29b5e-64fe-49be-a891-1e3c5783bc41)

With G1 GC, we do many short GC with each about 20ms which is what we expected.

### Z GC
JVM Options: 
```
- name: JAVA_TOOL_OPTIONS
              value: >-
                -Xms3g -Xmx3g -Xlog:gc*:file=/root/gc.log
                -XX:+UseZGC -XX:ParallelGCThreads=2
                -Djames.protocols.mdc.hostname=false
```

Performance (best of 2 try):
![image.png](https://images.zenhubusercontent.com/5f7fe3b8b67a756e7c63d181/d944acc2-5b79-4f67-b65a-2128f6310742)

The same I would say.

GC viewer:
![image.png](https://images.zenhubusercontent.com/5f7fe3b8b67a756e7c63d181/e0bec8be-3204-45bb-88da-ab74686101f1)

The total pause time is very short (0.02s), but the performance is not improved so I think the reason is to make Z GC really fully concurrency JVM shared more CPU dedicated to Z GC so despite much shorter stop the world time, it is less CPU time for application threads which makes performance is the same.

I tried to further optimized Z GC but did not get a successful result yet.  When adding `-XX:-UseNUMA -XX:ConcGCThreads=1` (https://wiki.openjdk.java.net/display/zgc/Main) the simulation is failed with a few thousands of failing requests. Here my guess is with these further options JVM takes even more CPU for GC so James is overloaded with the remaining application CPU.  Not sure yet, may need a few more experiments with these.

Also from what I read Z GC would benefit from having a bigger max heap size. Our heap is not big so that is maybe one of the reasons why we do not get much benefit from Z GC.

**Comment by quantranhong1999** [comment]
Tried to tune the Z GC but it does not help much.
- `-XX:UseNuma` option does not work (fail some random commands)
- `-XX:ConcGCThreads=1` option makes some search commands fail: https://pastebin.com/bdu5amap
  Error: `Trying to create too many scroll contexts. Must be less than or equal to: [500]`
  -> This could come from James is not stopped by GC anymore -> James now can send many scroll search queries concurrently to ES (instead of gradually, interruptedly before) which triggered the limit on ES
  -> Solved (partially?) by switching to Cassandra searching recently
- `-XX:+UseLargePages` does not help also

Not much settings left to help tuning this Z GC. My feeling is that we would not gain from using this Z GC.
There is just a curious thing left is that if Z GC help us have a better latency under a small/medium load (cause Z GC trade latency for throughput) but I guess we would not gain much either in that case.

**Comment by chibenwa** [comment]
Thanks for looking into this.
