### ISSUE TITLE
Healthcheck for tasks

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-backend#480]
## Configuration

**healthcheck.properties**

```
healthcheck.tasks.execution=TaskAName:2day,TaskBName:2mounth,taskCName:2week
```

If a successful task is located with the time period then the check is **green** :green_apple:.

If no successfull task is located with the time period then the check is **orange**.

Default value : empty

Default configuration: this property should be present with an explanation but commented with an exemple.

Don't forget to document this...

Performance considerations:
 - this healthcheck should only list task executions once
 - History cleanup for tasks might eventually be needed cf linagora/james-project#4620

Related links: https://www.mail-archive.com/server-dev@james.apache.org/msg72399.html

**Comment by quantranhong1999** [comment]
https://github.com/linagora/tmail-backend/pull/488
