### ISSUE TITLE
Release 0.6.3

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-backend#481]
- [x] Release tag
 - [x] Changelog
 - [x] Deploy on sandbox
 - [x] Performance tests
 - [x] Deploy on staging
 - [ ] Deploy on LNG

**Comment by quantranhong1999** [comment]
Change log: https://ci.linagora.com/linagora/lgs/software-linagora-com-website/-/merge_requests/40
Helm James: https://gitlab.com/linagora_private/saas/tools/helm-charts/helm-james/-/merge_requests/15
staging env: https://gitlab.com/linagora_private/saas/tmail/emaily-staging-apps/-/merge_requests/14
sandbox env: https://gitlab.com/linagora_private/saas/tmail/sandbox-emaily-apps/-/merge_requests/10

**Comment by Arsnael** [comment]
You could try to do a jmap rfc run without the changed params you did recently on the helm james conf. If it finishes, it means it's one of those. If not then it's more related to the release?

**Comment by chibenwa** [comment]
Flamme graph would be nice for IMAP too IMO

**Comment by Arsnael** [comment]
Hmm regarding IMAP being a bit slower... simple question first. Do you do a little warmup run first before doing the main one or not?

**Comment by quantranhong1999** [comment]
> Hmm regarding IMAP being a bit slower... simple question first. Do you do a little warmup run first before doing the main one or not?

Sure I do, for any case.

**Comment by Arsnael** [comment]
Alright, flame graph it is then :)

**Comment by quantranhong1999** [comment]
So with the same JMAP RFC simulation, TMail 0.6.2 was ok whereas TMail 0.6.3 (without changed configuration) hangs.

I suspect JMAP RFC 0.6.3 degraded a bit when handling many connections simultaneously (only a few hangs though ~ 10/6500 users).

I adapt the Gatling simulation to early quit for users who can not open a WebSocket connection/ has a premature close HTTP connection: https://github.com/linagora/james-gatling/pull/151

This could avoids those users from trying to do further actions and hung the simulation. I am not sure this could make the simulation 100% stable yet... at least better than all hang right now.

### JMAP-RFC result
![image](https://user-images.githubusercontent.com/55171818/194501971-6ef19c18-f4d6-4e97-b21a-53493a04c691.png)

Basically the same to me.

**Comment by quantranhong1999** [comment]
I re-test IMAP with a kinda unlimited 2000 concurrent req limit for IMAP -> the perf is the same. -> 200 is a appropriate value for our preprod env.
IMAP flame graph (5 minutes): [flame_graph.zip](https://github.com/linagora/tmail-backend/files/9733302/flame_graph.zip). We can have a look at this together next week.

**Comment by quantranhong1999** [comment]
### Some error logs collected

#### LDAP
```json
"level":"ERROR","thread":"blocking-call-wrapper-535","logger":"org.apache.james.user.ldap.ReadOnlyLDAPUser","message":"Unexpected error upon authentication for firstname1813.surname1813@upn.integration-open-paas.org","context":"default","exception":"com.unboundid.ldap.sdk.LDAPException: An error occurred while attempting to connect to server 51.91.141.10:389:  IOException(LDAPException(resultCode=82 (local error), errorMessage='A thread was interrupted while waiting for the connect thread to establish a connection to 51.91.141.10:389
```
Another one:
```json
"level":"ERROR","thread":"blocking-call-wrapper-536","logger":"org.apache.james.jmap.core.ProblemDetails","message":"Unexpected error upon API request","context":"default","exception":"org.apache.james.user.api.UsersRepositoryException: Unable check user existence from ldap\n\tat org.apache.james.user.ldap.ReadOnlyLDAPUsersDAO.getUserByName(ReadOnlyLDAPUsersDAO.java:285)\n\tat com.linagora.tmail.combined.identity.CombinedUserDAO.test(CombinedUserDAO.java:84)\n\tat com.linagora.tmail.combined.identity.CombinedUsersRepository.test(CombinedUsersRepository.java:20)\n\tat org.apache.james.jmap.http.BasicAuthenticationStrategy.$anonfun$isValid$1(BasicAuthenticationStrategy.scala:132)\n\tat org.apache.james.jmap.http.BasicAuthenticationStrategy.$anonfun$isValid$1$adapted(BasicAuthenticationStrategy.scala:132)\n\tat reactor.core.publisher.MonoCallable.call(MonoCallable.java:92)\n\tat reactor.core.publisher.FluxSubscribeOnCallable$CallableSubscribeOnSubscription.run(FluxSubscribeOnCallable.java:227)\n\tat reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)\n\tat reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)\n\tat java.base/java.util.concurrent.FutureTask.run(Unknown Source)\n\tat java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)\n\tat java.base/java.lang.Thread.run(Unknown Source)\nCaused by: com.unboundid.ldap.sdk.LDAPSearchException: Search processing was interrupted while waiting for a response from server 51.91.141.10:389.\n\tat com.unboundid.ldap.sdk.AbstractConnectionPool.search(AbstractConnectionPool.java:2160)\n\
```
These 2 errors only happen when running JMAP RFC with 10k users (we usually do this for 6.5k users). With many users we overload the LDAP -> some blocking thread hang (waiting for LDAP response) over reactor TTL (60s) and then be interrupted?

#### Cassandra timeout
```json
"level":"ERROR","thread":"s1-io-0","mdc":{"protocol":"IMAP","mailbox":"INBOX","selectedMailbox":"baf2cdb0-307a-11eb-ad60-d91e26006be3","ip":"10.2.2.0","action":"STATUS","sessionId":"SID-tkgtbjglvbwf","user":"firstname1000.surname1000@upn.integration-open-paas.org","parameters":"StatusDataItems{statusItems=[MESSAGES, RECENT, UID_NEXT, UNSEEN]}"},"logger":"org.apache.james.imap.processor.AbstractMailboxProcessor","message":"Unexpected error during IMAP processing","context":"default","exception":"com.datastax.oss.driver.api.core.servererrors.ReadTimeoutException: Cassandra timeout during read query at consistency QUORUM (2 responses were required but only 1 replica responded). In case this was generated during read repair, the consistency level is not representative of the actual consistency.\n"
```

A few IMAP STATUS commands fail because of this. Maybe because we overload Cassandra then it fails with requests requiring a high consistency level?

#### RabbitMQ

```json
"level":"ERROR","thread":"AMQP Connection 51.210.36.126:5672","logger":"com.rabbitmq.client.impl.ForgivingExceptionHandler","message":"An unexpected connection driver error occurred","context":"default","exception":"java.net.SocketTimeoutException: Timeout during Connection negotiation\n\tat com.rabbitmq.client.impl.AMQConnection.handleSocketTimeout(AMQConnection.java:835)\n\tat com.rabbitmq.client.impl.AMQConnection.readFrame(AMQConnection.java:747)\n\tat com.rabbitmq.client.impl.AMQConnection.access$300(AMQConnection.java:47)\n\tat com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:666)\n\tat java.base/java.lang.Thread.run(Unknown Source)\n
```

Likely a driver error more than James itself. Could because RabbitMQ overloaded?

#### Rspamd

```json
"level":"ERROR","thread":"spooler-388","logger":"org.apache.james.mailetcontainer.impl.ProcessorImpl","message":"Exception calling org.apache.james.rspamd.RspamdScanner: reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response\n
```

I observe this only happens when Rspamd is down or overloaded. Maybe we just need to make sure the mail processing still operates when Rspamd is unavailable. (or it is already?)

**Comment by chibenwa** [comment]
> LDAP issues

`JMAP RFC` calls uses basic auth: all JMAP requests hits the LDAP, which is somehow an unrealistic scenario.

Maybe we should have configuration within gatling-jmap on the authentication method?

 - [ ] Use basic-auth
 - [ ] Use X-User header (like with krakend)

Could be a start?

I can live with this flow for now but can you please create a ticket on `james-gatling` repo?

**Comment by chibenwa** [comment]
> Cassandra timeout
> A few IMAP STATUS commands fail because of this. Maybe because we overload Cassandra then it fails with requests requiring a high consistency level?

All our requests use QUORUM consistency level. If needed, I can re-explain in detail why. In short: good compromise between consistency and availabilty. That's somewhat of a standard practice in the industry.

Likely yes it shows Cassandra can be the bottleneck.

I would be interested to get the count of error too. Are we speaking of 10? 10.000?

Finally by offloading some of the searches to Cassandra we might load Cassandra a bit more than we should.

**Comment by chibenwa** [comment]
> RabbitMQ

What is suspicious is that it even tries to reconnect. What's the time of the log? Was it when re-deploying/scaling James?

I already noticed scaling/re-deploying james can knock out the RabbitMQ cluster.

**Comment by chibenwa** [comment]
> Rspamd

> rspamd.RspamdScanner: reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response\n

> I observe this only happens when Rspamd is down or overloaded. Maybe we just need to make sure the mail processing still operates when Rspamd is unavailable. (or it is already?)

Mailet configuration allows fine grain error management.

We should ensure all default configuration is written so that we ignore error of the `RspamdScanner` mailet.

Can you open a ticket on `linagora/james-project` for this?

**Comment by chibenwa** [comment]
Regarding Cassandra if this is https://github.com/linagora/tmail-backend/issues/481#issuecomment-1269856958 with 1 failed status then it do not seem too bad to me, likely we should avoid spending too much time on this.

**Comment by chibenwa** [comment]
Regarding Cassandra, search overrides for `searchUnseen`, `searchDeleted` might filter a lot of data when executed against Cassandra, and might in the end be more optimal executed against a search index...

**Comment by quantranhong1999** [comment]
> I would be interested to get the (IMAP STATUS) count of error too. Are we speaking of 10? 10.000?

just a few ~10

> What's the time of the (RabbitMQ) log? Was it when re-deploying/scaling James?

There are only 3 consecutive ones that I am not sure of the timing. Could be as you said.

Tickets:
- https://github.com/linagora/james-project/issues/4638
- https://github.com/linagora/james-gatling/issues/152
