### ISSUE TITLE
Delegation storage API: Cassandra implementation

### ISSUE THREAD

**Issue by Arsnael** [linagora/tmail-backend#49]
After #48, we need to do the Cassandra implementation of it.

DoD: Write a Cassandra implementation of it and make the contract test suite work with it

**Comment by chibenwa** [comment]
FYI I proposed an API as part of https://app.zenhub.com/workspaces/team-james-5873652b2a0b13cc0b8bbe63/issues/linagora/james-project-private/78#issuecomment-784719859

```
trait DelegationStore {
  def listDelegatedUsers(username: Username): SFlux[Username]
  def addDelegatedUser(accessor: Username, accessee: Username): SMono[Unit]
  def removeDelegatedUser(accessor: Username, accessee: Username): SMono[Unit]
  def isDelegated(accessor: Username, accessee: Username): SMono[Boolean]
}
```

Here are some remaining questions:
 - Where (which maven project) do we locate this?
 - What is the table design (Primary Key, Clustering Key, Clustering column)? And their types? It is unclear reading the ticket...
