### ISSUE TITLE
[Firebase] add capability object

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-backend#491]
Add the `com:linagora:params:jmap:firebase:push` capability in the jmap session object. The object is empty

**Comment by Arsnael** [comment]
Should show or not depending if we have a firebase conf in tmail.
We can introduce some pojo conf and a module chooser for firebase
`firebase.properties` -> enabled=true (or false)

**Comment by quantranhong1999** [comment]
https://github.com/linagora/tmail-backend/pull/513
