### ISSUE TITLE
[FireBase] Integration test

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-backend#492]
## Use cases

```
Bob registers a client with firebase with FirebaseRegistration/set create
When Bob receives a message on his mailbox
Then he should receive a state change notification from firebase
```

```
Bob registers a client with firebase with FirebaseRegistration/set create
When Bob receives a message on his mailbox 8 days later after his subscription expired
Then he should not receive the notification from firebase
```

```
Bob registers a client with firebase with FirebaseRegistration/set create
And he destroys it with FirebaseRegistration/set destroy
When Bob receives a message on his mailbox
Then he should not receive the notification from firebase
```

```
Bob registers a client with firebase with FirebaseRegistration/set create
And 3 days pass and Bob extends its subscription with FirebaseRegistration/set update
When Bob receives a message on his mailbox 5 days later
Then he should still receive a state change notification from firebase
```

```
Bob registers a client A with firebase with FirebaseRegistration/set create
And he registers a client B with firebase with FirebaseRegistration/set create
When Bob receives a message on his mailbox
Then he should still receive a state change notification from firebase on client A and client B
```

**Notes**:
- if we have the firebase mock server, use it, if not, go on by using mocks on client

**Comment by Arsnael** [comment]
Trying to wrap my head around this one... Forgot what was said last time too. How do we test our implem with Firebase? I don't think we will create an app just for that right?

**Comment by chibenwa** [comment]
> I don't think we will create an app just for that right?

mocks on the firebase client?

**Comment by vttranlina** [comment]
It look like that we want:
https://firebase.google.com/docs/firestore/client/libraries#google_cloud_client_libraries
https://www.youtube.com/watch?v=Mcsp59_2E7E

But we need a real a firebase account

**Comment by chibenwa** [comment]
tmail.linagora@gmail.com ask Benoit for the password

**Comment by Arsnael** [comment]
> mocks on the firebase client?

So used on you saying I hate mocks now that I don't even think about this solution anymore :P

**Comment by quantranhong1999** [comment]
The Firebase java client hardcodes the FCM URL and FCM does not provide any API to check the message count. It will be likely impossible to validate that the FCM server received `FirebaseClient`' request. So... we may actually need to mock `FirebaseClient` as Benoit said.

If one wants literal responses from FCM, we can use built-in `GOOGLE_APPLICATION_CREDENTIALS` environment variable:
```
export GOOGLE_APPLICATION_CREDENTIALS="/home/user/Downloads/service-account-file.json"
```
and only volume that secret JSON file to CI/ dev machines.
However, still, the call validation trouble and this just add too much build complexity IMO.

**Comment by chibenwa** [comment]
That's exactly where mocks shines!

The problem with mocks is getting confused between hammer and screwdriver :-)

**Comment by quantranhong1999** [comment]
https://github.com/linagora/tmail-backend/pull/527
