### ISSUE TITLE
[Firebase] Cassandra for Firebase subscription storage

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-backend#494]
## Why 
We need Cassandra's implementation for `Firebase subscription storage`.  

## Requires
- https://app.zenhub.com/workspace/o/linagora/tmail-backend/issues/493

## How
Do basically the same as `CassandraPushSubscriptionRepository`.

- Table structure

```

PK user TEXT
CK device_id TEXT
C id UUID
C expired TIMESTAMP
C types frozen SET of TEXT
C token TEXT
```

## Dod 
Pass contract tests.

**Comment by vttranlina** [comment]
`C highPriority boolean`
String type is better?

**Comment by chibenwa** [comment]
> String type is better?|

Why ?

**Comment by vttranlina** [comment]
> > String type is better?|
> 
> Why ?

I see on firebase document, priority is a number, it can be 1,2,3,4,5.
Or we can more string level: low, normal, high
https://firebase.google.com/docs/cloud-messaging/concept-options#setting-the-priority-of-a-message

**Comment by chibenwa** [comment]
Ok for `int` on my side

**Comment by quantranhong1999** [comment]
https://github.com/linagora/tmail-backend/pull/517
