### ISSUE TITLE
Integration tests for account delegation

### ISSUE THREAD

**Issue by Arsnael** [linagora/tmail-backend#50]
### Objective

With AccountDelegationAPI (Memory/Cassandra) working, we can now add support for delegation where an user can act as another user using their accountId.

### How

Write additional test cases for all funtionalities that has the ability to support account delegation (mailbox, email, download...).

### DoD

All of the above test cases being able to run successfully.

**Comment by chibenwa** [comment]
Can we list what needs to be tested?

 - [ ] As a deleguee I can execute API methods using the accountId of the other user (list mailboxes is OK, manual QA for others...)
 - [ ] As a deleguee I can upload stuff  using the accountId of the other user
 - [ ] As a deleguee I can download stuff  using the accountId of the other user
 - [ ] As a deleguee I receive (websocket) notifications for the other user
 - [ ] As a deleguee I receive (eventSource) notifications for the other user
 - [ ] As a deleguee I can seethe delegated account in my session object

**Comment by vttranlina** [comment]
All checklist completed!
I think we can close it?
