### ISSUE TITLE
FirebaseClient

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-backend#500]
## Why
We need a client to push changes from James to the Firebase cloud messaging

## How 

- Write an `FCMConfiguration`: We will need a configuration file to store firebase credentials for server usage + project name,...
  Firebase provides some authentication mechanisms (https://firebase.google.com/docs/admin/setup#initialize-sdk):
   - Use a private key (JSON) file
   - Use an OAuth 2.0 refresh token

- Add firebase-admin SDK dependency:
  ```
    <dependency>
        <groupId>com.google.firebase</groupId>
        <artifactId>firebase-admin</artifactId>
        <version>9.0.0</version>
    </dependency>
  ```
- Write a FirebasePushClient utilize the library to send the message to FCM (https://firebase.google.com/docs/cloud-messaging/send-message):
  ```scala
    case class FirebasePushRequest(stateChangesMap: Map[String, String], token: List[String])

    def push(request: FirebasePushRequest): Publisher[Unit]
  ```

 No need to serialize `FirebasePushRequest` to JSON (taken care of by the library).

## DoD
- Implement client
- Test (1 of these): 
  - Directly to FCM: [create project Test TMail on FCM](https://firebase.google.com/docs/admin/setup#set-up-project-and-service-account) and fire test directly to FCM
  => This could be more precise but create dependency on external resources for builds, and testing credentials exposing issue.
  - Fire to mock servers: https://github.com/anaryshkin/fcm-mock-server, https://github.com/kmakiela/fcm-mock-server
  => Could not describe fully FCM behaviors, however, builds do not depend on external resources.

I would prefer firing at real FCM cause the available mock FCM servers do not seem to have proven usage.

**Comment by vttranlina** [comment]
FCM Mock server in another ticket https://github.com/linagora/tmail-backend/issues/507

**Comment by Arsnael** [comment]
Manual tests with FCM as well

**Comment by quantranhong1999** [comment]
https://github.com/linagora/tmail-backend/pull/519

**Comment by quantranhong1999** [comment]
https://github.com/linagora/tmail-backend/pull/519
