### ISSUE TITLE
FirebasePushListener

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-backend#501]
## Why
We need a listener to push the state changes to FCM.

## How
Do basically the same as `PushListener`: listen to stateChange event and push them to FCM using `FirebaseClient`.

`For users / deployments that are privacy sensitive, we should be able to disable PUSH to FCM`.
=> We could make this `FirebasePushListener` optional along with FirebaseModuleChooser.

## DoD
- Test: mock client to verify it is called.

**Comment by quantranhong1999** [comment]
This Listener should be resilient to FCM errors: https://firebase.google.com/docs/cloud-messaging/send-message?authuser=0#admin

E.g `messaging/registration-token-not-registered`: `The client app was automatically unregistered. This can happen if the user uninstalls the application...`
Then we should remove the FirebaseRegistration of that device.

**Comment by vttranlina** [comment]
Note: guice module depend on firebase disable/enable configuration

**Comment by quantranhong1999** [comment]
https://github.com/linagora/tmail-backend/pull/521
