### ISSUE TITLE
[FireBase] Tunning for priorities

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-backend#502]
If the StateChange contains `EmailDelivery` type => high priority

If the StateChange do not contain `EmailDelivery` => normal priority

CF WebPush

```
  private def urgency(stateChange: StateChange): PushUrgency =
    if (stateChange.changes
      .values
      .flatMap(_.changes.keys)
      .toList
      .contains(EmailDeliveryTypeName)) {
      High
    } else {
      Low
    }
```

**Comment by quantranhong1999** [comment]
Some findings regarding this topic:
- We can specify NORMAL/HIGH priority for Android whilst only NORMAL for iOS: https://firebase.google.com/docs/cloud-messaging/concept-options#setting-the-priority-of-a-message

**Comment by vttranlina** [comment]
if the tunning is the firebase site, we just add `webpush.headers.Urgency` in the request to firebase
the priority level will be stored in the database ( Firebase subscription storage) and the client can change it via jmap FirebaseSubscription/set

**Comment by vttranlina** [comment]
Should we do it on tmail site? eg: create two channels (high/normal), with each priority, the WebPushEvent will be sent to HighQueue or NormalQueue

**Comment by quantranhong1999** [comment]
> if the tunning is the firebase site, we just add `webpush.headers.Urgency` in the request to firebase

I think this `webpush.headers.Urgency` is only for firebase -> another web push gateway -> devices. We will directly use the flow: firebase -> devices (iOS/android).

**Comment by quantranhong1999** [comment]
> `webpush.headers.Urgency` is only for firebase -> another web push gateway -> devices.

Reread the material again, actually, FCM' web push directly pushes to web browsers. So yeah we can tuning this `webpush.headers.Urgency` for web devices also.

**Comment by quantranhong1999** [comment]
https://github.com/linagora/tmail-backend/pull/521/commits/c4bf343b955d0d89ac52d98e41be811fabaeff24
