### ISSUE TITLE
Updaate SHA-1 and tag a 0.6.4-rc1

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-backend#504]
Rationals: flutter team shall be playing with Identity sort order, Quotas.

Once done deploy it on preprod.

Cc @hoangdat

**Comment by Arsnael** [comment]
Deployed on preprod...

**Comment by Arsnael** [comment]
https://gitlab.com/linagora_private/saas/tmail/sandbox-emaily-apps/-/merge_requests/11
https://gitlab.com/linagora_private/saas/tmail/emaily-staging-apps/-/merge_requests/16
