### ISSUE TITLE
[Firebase] FCM Mock server

### ISSUE THREAD

**Issue by vttranlina** [linagora/tmail-backend#507]
Fire to mock servers: https://github.com/anaryshkin/fcm-mock-server, https://github.com/kmakiela/fcm-mock-server
=> Could not describe fully FCM behaviors, however, builds do not depend on external resources.

**Comment by vttranlina** [comment]
> https://github.com/kmakiela/fcm-mock-server

last update at 3 years ago. I can't http request after start the docker.

> https://github.com/anaryshkin/fcm-mock-server

It work, but it just a mock server (receive request). We can do the same with mock-server (the library already in james,  but write more code.).

_______________

We can't modify the endpoint of FCM server when use firebase client library.
```
        <dependency>
            <groupId>com.google.firebase</groupId>
            <artifactId>firebase-admin</artifactId>
            <version>9.1.0</version>
        </dependency>
```
So, the fcm-mock-server do not make sense. 

Should we use HTTPClient (without firebase-admin)?

**Comment by chibenwa** [comment]
Imo no. Using the official client is safer, less prone to issues/ more robust to change.

Imo we can close this ticket.

Thanks for taking a deeper look at it.
