### ISSUE TITLE
JMAP endpoint should support being called with accountIds of delegated accounts

### ISSUE THREAD

**Issue by vttranlina** [linagora/tmail-backend#530]
This is the same with James https://github.com/linagora/james-project/issues/4679
but integrated for tmail-backend

 - [x] Firebase
 - [x] As a delegate I should not be able to manage PGP public key (`KeystoreSetMethod`). Get is OK.
 - [x] `LongLivedToken*tMethod` should be rejected for delegates
 - [x] JMAP Forward method: I think only the base user should be allowed to do this....

**Comment by vttranlina** [comment]
pr https://github.com/linagora/tmail-backend/pull/545

**Comment by vttranlina** [comment]
**JMAP Forward method:**
Should We forward an email to authorized accounts when delegated?

**Comment by chibenwa** [comment]
JMAP Forward method: I think only the base user should be allowed to do this....

**Comment by vttranlina** [comment]
pr 2: https://github.com/linagora/tmail-backend/pull/549
