### ISSUE TITLE
Autocomplete should not index duplicated domain/user contact

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/tmail-backend#541]
On `tmail.linagora.com`, when using autocomplete, I get two contacts with the same mail address:
![image](https://user-images.githubusercontent.com/55171818/210733969-2c51e631-8544-499d-a158-aa652c4afe79.png)

Jmap autocomplete response:
```json
{
	"sessionState": "2c9f1b12-b35a-43e6-9af2-0106fb53a943",
	"methodResponses": [
		["TMailContact/autocomplete", {
			"accountId": "8e1534a48ceb6a660b23b18d0de5fba066b2179de5872d4426f90a2cc931095d",
			"list": [{
				"id": "a5f670c5-d5e0-3b22-8197-02a9c37cad27",
				"emailAddress": "hqtran@linagora.com",
				"firstname": "Hong Quan TRAN",
				"surname": ""
			}, {
				"id": "a5f670c5-d5e0-3b22-8197-02a9c37cad27",
				"emailAddress": "hqtran@linagora.com",
				"firstname": "Hong Quan",
				"surname": "TRAN"
			}]
		}, "c0"]
	]
}
```

Seems one from domain contacts and one from user contacts.

We should avoid this duplication therefore need to investigate.

**Comment by chibenwa** [comment]
Filtering could also be done at read time to remove duplicates.

**Comment by quantranhong1999** [comment]
https://github.com/linagora/tmail-backend/pull/543
