### ISSUE TITLE
[EPIC] Preprovision a default identity

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-backend#554]
### Current behavior

Mails are sent using `From: <user@domain.com>`

Missing display name is uggly.

### Expected result

As a user my default identity **MUST** include reasonable default display name `From: Display Name <user@domain.com>`

### Possible technical solution

Default display name can be recovered from the LDAP.

We could....
 - Add a WebAdmin API allowing listing one user identity.
 - Add a WebAdmin API allowing creating / editing the user default identity
 - Create a LSC cron job that modifies the user default identity to add the LDAP display name if none is available.
 
### Original bug report

https://github.com/linagora/tmail-flutter/issues/1430 Cc @guimard

**Comment by quantranhong1999** [comment]
I just check our contract tests, I believe users can modify their default identities.
cf https://github.com/linagora/tmail-flutter/issues/1430#issuecomment-1429069375

While it is convenient that the server could pre-provision display name for user default identity, this is less prioritized now I guess?

**Comment by chibenwa** [comment]
No IMO we should be able to provide top notch user experience without the user to even know what is an identity

**Comment by quantranhong1999** [comment]
I propose the task split:
- Add a WebAdmin API allowing listing user default identity
- Add a WebAdmin API allowing editing the user default identity (User always has at least 1 default identity, so I think we don't need creating API?)
- Update the TMail image to have the latest web admin identity APIs
- Develop an LSC script that modifies the user default identity to add the LDAP display name if none is available
- Create an LSC cron job for user default identity's display name synchronization

**Comment by chibenwa** [comment]
> Update the TMail image to have the latest web admin identity APIs 

RC tag as part of a release?

**Comment by chibenwa** [comment]
> Develop an LSC script that modifies the user default identity to add the LDAP display name if none is available

Develop an LSC script that modifies the user default identity to create a new identity with the LDAP display name if no mayDelete=true identity is available
