### ISSUE TITLE
[EPIC] JMAP extension in Team-Mail to parse ICS

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/tmail-backend#558]
1. JMAP Event/parse should allow the TMail fronts to parse an ICS attachment into a structured JSON representing and event.

They should be able to use it to display all bluebar related data

QUESTION does the jmap spec already have what we want? https://jmap.io/spec-calendars.html#creating-an-event `CalendarEvent/parse` ?

**Comment by quantranhong1999** [comment]
Tasks split:

- JMAP specs for calendar event parsing extension
- Extract parsing calendar event method using `ical4j` (from `ICalendarParser` mailet) to a common utilize class, and unit test it
- JMAP implementation

**Comment by quantranhong1999** [comment]
Working on the parsed event structure:

  - Event name (SUMMARY): name of the event. E.g `Gatling: break LemonLDAP !`
  - Event discription (DESCRIPTION): e.g `Let's write some basic OIDC benchmarks to break Lemon on preproduction for Twake SaaS.`
  - Organizer:
    - common name of organizer (CN)
    - email of organizer (MAILTO)
  - Start date (DTSTART) with timezone support: e.g `20170111T090000Z`, `TZID=Asia/Ho_Chi_Minh:20230209T120000`
  - End date (DTEND) with timezone support: e.g `20170111T090000Z`, `TZID=Asia/Ho_Chi_Minh:20230209T120000`
  - Duration (DURATION): e.g `PT1H30M`
  - ATTENDEES: Attendee[]
    While Attendee object contains:
    - name (CN)
    - mail (MAILTO)
    - participation status (PARTSTAT): NEEDS-ACTION/ACCEPT/...
    - CUTYPE ?
    - RSVP (request response to the event)?
  - Location (LOCATION)?
  - Video conference link (custom OpenPaaS calendar header `X-OPENPAAS-VIDEOCONFERENCE`)
  --> Or just return `X-PROPERTY` with all custom headers and let the FE handles them.

**Comment by chibenwa** [comment]
We are missing the request field. Important to know what is being done.... I will create related issues nheeeee....
