### ISSUE TITLE
JMAP specs for calendar event parsing extension

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/tmail-backend#561]
## Why
We want to display an event's information like the blue bar of OpenPaaS inbox.

We would implement a JMAP extension parsing calendar events (.ics), so the client-side can get event information to display as a blue bar.

We need to write a specification for that extension.

## How

I've attached a draft/of suggestions about how the extension could look.

Request:
```
{
	"using": [
		"urn:ietf:params:jmap:core",
		"com:linagora:params:calendar:event"
	],
	"methodCalls": [
		[
			"CalendarEvent/parse",
			{
				"accountId": "29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6",
				"blobIds": ["blobIdParsable", "blobIdNotParsable", "blobIdNotFound"]
			},
			"c1"
		]
	]
}
```

While parsing the `.ics`
```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Sabre//Sabre VObject 4.1.3//EN
CALSCALE:GREGORIAN
METHOD:REQUEST
BEGIN:VTIMEZONE
TZID:Asia/Ho_Chi_Minh
BEGIN:STANDARD
TZOFFSETFROM:+0700
TZOFFSETTO:+0700
TZNAME:ICT
DTSTART:19700101T000000
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
UID:e8f219b4-30bc-42d3-871d-277b65d89d1a
TRANSP:OPAQUE
DTSTART;TZID=Asia/Ho_Chi_Minh:20230209T100000
DTEND;TZID=Asia/Ho_Chi_Minh:20230209T120000
CLASS:PUBLIC
X-OPENPAAS-VIDEOCONFERENCE:https://jitsi.linagora.com/abcd
X-OPENPAAS-CUSTOM-HEADER1:whatever
SUMMARY:Gatling: break LemonLDAP !
DESCRIPTION:Let's write some basic OIDC benchmarks to break Lemon on prepro
 duction for Twake SaaS.
LOCATION:5 Dien Bien Phu, Ha Noi
ORGANIZER;CN=Benoît TELLIER:mailto:btellier@linagora.com
DTSTAMP:20230206T091728Z
ATTENDEE;PARTSTAT=NEEDS-ACTION;RSVP=TRUE;ROLE=REQ-PARTICIPANT;CUTYPE=INDIVI
 DUAL;CN=Van Tung TRAN:mailto:vttran@linagora.com
ATTENDEE;PARTSTAT=ACCEPTED;RSVP=FALSE;ROLE=CHAIR;CUTYPE=INDIVIDUAL;CN=Beno
 ît TELLIER:mailto:btellier@linagora.com
SEQUENCE:0
END:VEVENT
END:VCALENDAR
```

Response should look like:
```
{
	"sessionState": "2c9f1b12-b35a-43e6-9af2-0106fb53a943",
	"methodResponses": [
		[
			"CalendarEvent/parse",
			{
				"accountId": "29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6",
				"notFound": ["blobIdNotFound"],
				"notParsable": ["blobIdNotParsable"],
				"parsed": {
					"blobIdParsable": {
						"title": "Gatling: break LemonLDAP!",
						"description": "Let's write some basic OIDC benchmarks to break Lemon on preproduction for Twake SaaS.",
						"start": "2023-02-09T10:00:00",
						"duration": "PT2H0M0S",
						"end": "2023-02-09T12:00:00",
						"timeZone": "Asia/Ho_Chi_Minh",
						"location": "5 Dien Bien Phu, Ha Noi",
						"organizer": {
							"name": "Benoît TELLIER",
							"mailto": "btellier@linagora.com"
						},
						"participants": [{
								"name": "Benoît TELLIER",
								"mailto": "btellier@linagora.com",
								"kind": "individual",
								"role": "chair",
								"participationStatus": "accepted",
								"expectReply": false
							},
							{
								"name": "Van Tung TRAN",
								"mailto": "vttran@linagora.com",
								"kind": "individual",
								"role": "requested-participant",
								"participationStatus": "needs-action",
								"expectReply": true
							}
						],
						"extensionFields": {
							"X-OPENPAAS-VIDEOCONFERENCE": "https://jitsi.linagora.com/abcd",
							"X-OPENPAAS-CUSTOM-HEADER1": "whatever"
						}
					}
				}
			},
			"c1"
		]
	]
}
```

While:
- `title`: title of the event ~ `SUMMARY` (iCalendar)
- `description`: description of the event ~ `DESCRIPTION`
- `start`: Start time of the event ~ `DTSTART`
- `end`: End time of the event ~ `DTEND`
- `duration`: duration of the event ~ `DURATION`
- `timeZone`: time zone of the start/end time ~ `TZID`
- `location`: location of the event ~ `LOCATION`
- `organizer`: the organizer of the event, contains name (`CN`) and mail (`mailto`)
- `participants`: a collection of attendees (`ATTENDEE`)
   Each participant contains information:
   - `name`: name of the participant
   - `mailto`: mail address of the participant
   - `kind`: "CUTYPE", to indicate the type of calendar user
   - `role`:  "ROLE", for the intended role that the attendee will have in the calendar component
   - `participationStatus`: "PARTSTAT", for the status of the attendee's participation
   - `expectReply`:  Boolean. "RSVP", for indicating whether the favor of a reply is requested
- `extensionFields`: contains custom event headers.

## DoD
Get full consensus on TMail team.

## References
- iCalendar message RFC: https://www.rfc-editor.org/rfc/rfc5545
- MDN/parse specs: https://datatracker.ietf.org/doc/html/rfc9007#name-parsing-a-received-mdn
- JMAP `CalendarEvent/set` spec: https://jmap.io/spec-calendars.html#creating-an-event

**Comment by chibenwa** [comment]
DOD share this use case and need within the IETF

**Comment by vttranlina** [comment]
PR https://github.com/linagora/tmail-backend/pull/582

**Comment by chibenwa** [comment]
Don't forget to send a mail to IETF mailing list ( @Arsnael  maybe? )

**Comment by Arsnael** [comment]
> Don't forget to send a mail to IETF mailing list ( @Arsnael maybe? )

Not in the state it is in currently I'm afraid :) (see comments) Or not on my behalf then
