### ISSUE TITLE
[EPIC] Leave a team mailbox

### ISSUE THREAD

**Issue by Arsnael** [linagora/tmail-backend#562]
A user should be able to leave a team mailbox that he is part of without having to ask an admin to do such an action for him.

## Tasks

- https://github.com/linagora/tmail-backend/issues/567
- https://github.com/linagora/tmail-backend/issues/568

**Comment by chibenwa** [comment]
> The session used in the method is already a system session with the "team mailbox user" (team-mailbox@domain). And because with JMAP we already check that the accountId corresponds to the user, then there should be no risk of removing other users of a team mailbox than yourself right?

Right

> Question about delegation: should delegated people be able to remove a delegated account from a team mailbox or not?

Good question. IMO NO. Right management should belong to the owner I imagine.

**Comment by quantranhong1999** [comment]
Not related to this but I found 2 delegation words from RFC document that could help we are clearer saying about delegation entities:
- `delegatee`: a person to whom something is delegate
- `delegator`: someone who [delegates](https://dictionary.cambridge.org/vi/dictionary/english/delegate) (= gives) [part](https://dictionary.cambridge.org/vi/dictionary/english/part) of [their](https://dictionary.cambridge.org/vi/dictionary/english/their) [job](https://dictionary.cambridge.org/vi/dictionary/english/job), [duties](https://dictionary.cambridge.org/vi/dictionary/english/duty), etc. to someone [else](https://dictionary.cambridge.org/vi/dictionary/english/else) to do for them

**Comment by chibenwa** [comment]
> Not related to this but I found 2 delegation words from RFC document that could help we are clearer saying about delegation entities

Thanks for sharing. Is `delegatee` english ?

**Comment by Arsnael** [comment]
- Need dedicated team mailbox capability
- TeamMailboxes/RevokeAccess method
- should be name of mailbox as param and not mailbox id

**Comment by Arsnael** [comment]
should document the spec extension
