### ISSUE TITLE
[PREPROD] Can not create identity with team mailbox address

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/tmail-backend#573]
GIVEN user 29 has access to `hiring@upn.integration-open-paas.org` team mailbox
WHEN user 29 creates an identity with "from" `hiring@upn.integration-open-paas.org`
THEN he should succeed.

However, on preprod, we fail:
Request:
```json
{
	"using": [
		"urn:ietf:params:jmap:core",
		"urn:ietf:params:jmap:submission"
	],
	"methodCalls": [
		[
			"Identity/set",
			{
				"accountId": "9039d9068b20a681e63de6e52f0476b1d10efbc82153a690eb92dcb040517b90",
				"create": {
					"0e2eca50-b19e-11ed-a171-8f28c36cfddc": {
						"name": "test",
						"email": "hiring@upn.integration-open-paas.org",
						"bcc": [],
						"replyTo": [],
						"textSignature": "",
						"htmlSignature": "",
						"sortOrder": 100
					}
				}
			},
			"c0"
		]
	]
}
```

Response:
```json
{
	"sessionState": "2c9f1b12-b35a-43e6-9af2-0106fb53a943",
	"methodResponses": [
		["Identity/set", {
			"accountId": "9039d9068b20a681e63de6e52f0476b1d10efbc82153a690eb92dcb040517b90",
			"newState": "2c9f1b12-b35a-43e6-9af2-0106fb53a943",
			"notCreated": {
				"f35371a0-b19c-11ed-a171-8f28c36cfddc": {
					"type": "forbiddenFrom",
					"description": "Can not send from hiring@upn.integration-open-paas.org"
				}
			}
		}, "c0"]
	]
}
```

Add shares capability does not make this work.

We should have TMailCanSendFrom handles this case, but it seems not the case on preprod.

**Comment by chibenwa** [comment]
Can we write a test reproducing this in `TeamMailboxesContract` ? I do not see Identity/set creates in there...

**Comment by Arsnael** [comment]
Wait I'm confused here... Why a user part of a team mailbox should be able to create an identity for it? so any users accessing a team mailbox can create an identity to that last one? Isn't that a bit easy? A normal can't create and administrate a team mailbox in the first place, I would find it strange that he can add identities to it

**Comment by Arsnael** [comment]
Every user should have the identity of the team mailbox, so they can send mails as if they were the team mailbox, is that what you mean here?

**Comment by chibenwa** [comment]
And every user should be able to create identities referencing this Team Mailbox.

**Comment by quantranhong1999** [comment]
At first, reproducing with Identity/set in IT does not succeed (IT passes)

- Double checked if user 29 is in the team mailbox via webadmin
- Identity/get for user 29 do return server identity of `hiring@upn.integration-open-paas.org`, which means TMailCanSendFrom do list the team mailbox addresses

TODO: investigate more

**Comment by chibenwa** [comment]
> At first, reproducing with Identity/set in IT does not succeed (IT passes)

That's still a valuable test, don't hesitate to contribute it...

**Comment by quantranhong1999** [comment]
https://github.com/linagora/tmail-backend/pull/574

tested on preprod


![Image](https://user-images.githubusercontent.com/55171818/220600397-17867595-8f36-40e7-88c6-8a1c9873ced8.png)
