### ISSUE TITLE
Linagora application discovery

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-backend#588]
## What ?

Enable mobile devices to locate other Linagora application servers in order to include their features.

Usage: seemless integration. (that's different from the Application grid!)

Eg: LinShare API URL, Twake API URL, LinTO API URL + accessToken...

## How

```
GET {jmapEndpoint}/.well-known/linagora-ecosystem

{
    "linshareApiUrl": "https://linshare.linagora.com/linshare/webservice",
    "linToApi": "https://linto.ai/demo"
    'linToApiKey": "72389r268935623"
    "twakeApiUrl": "https://api.twake.app"
}
```

We assume SSO between services.

Front can use this to integrate components with 3rd party linagora apps.

The use of a distinct URL allows to have this working easily on non tmail servers.

Load the content from configuration:

`linagora-ecosystem.properties`:

```
linshareApiUrl=https://linshare.linagora.com/linshare/webservice
linToApi=https://linto.ai/demo
linToApiKey=72389r268935623
twakeApiUrl=https://api.twake.app
```

**Comment by quantranhong1999** [comment]
https://github.com/linagora/tmail-backend/pull/621
