### ISSUE TITLE
JMAP CalendarEvent/parse recurence

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-backend#592]
CF https://www.rfc-editor.org/rfc/rfc8984.html#name-recurrence-properties

I think the rfc8894 structure regarding event recurrence is good enough.

## Spec
Recurrence rules could have the following structure:

**frequency**: "String" (mandatory)
      This is the time span covered by each iteration of this recurrence
      rule (see Section 4.3.3.1 for full semantics).  This MUST be one
      of the following values:

      *  "yearly"

      *  "monthly"

      *  "weekly"

      *  "daily"

      *  "hourly"

      *  "minutely"

      *  "secondly"

      This is the FREQ part from iCalendar, converted to lowercase.

   **interval**: "UnsignedInt" (optional, default: 1)
      This is the interval of iteration periods at which the recurrence
      repeats.  If included, it MUST be an integer >= 1.

      This is the INTERVAL part from iCalendar.

   **rscale**: "String" (optional, default: "gregorian")
      This is the calendar system in which this recurrence rule
      operates, in lowercase.  This MUST be either a CLDR-registered
      calendar system name [CLDR] or a vendor-specific value (see
      Section 3.3).

      This is the RSCALE part from iCalendar RSCALE [RFC7529], converted
      to lowercase.

   **skip**: "String" (optional, default: "omit")
      This is the behavior to use when the expansion of the recurrence
      produces invalid dates.  This property only has an effect if the
      frequency is "yearly" or "monthly".  It MUST be one of the
      following values:

      *  "omit"

      *  "backward"

      *  "forward"

      This is the SKIP part from iCalendar RSCALE [RFC7529], converted
      to lowercase.

   **firstDayOfWeek**: "String" (optional, default: "mo")
      This is the day on which the week is considered to start,
      represented as a lowercase, abbreviated, and two-letter English
      day of the week.  If included, it MUST be one of the following
      values:

      *  "mo"

      *  "tu"

      *  "we"

      *  "th"

      *  "fr"

      *  "sa"

      *  "su"

      This is the WKST part from iCalendar.

   **byDay**: "NDay[]" (optional)
      These are days of the week on which to repeat.  An "NDay" object
      has the following properties:

      @type: "String" (mandatory)
         This specifies the type of this object.  This MUST be "NDay".

      day: "String" (mandatory)
         This is a day of the week on which to repeat; the allowed
         values are the same as for the "firstDayOfWeek" recurrenceRule
         property.

         This is the day of the week of the BYDAY part in iCalendar,
         converted to lowercase.

      nthOfPeriod: "Int" (optional)
         If present, rather than representing every occurrence of the
         weekday defined in the "day" property, it represents only a
         specific instance within the recurrence period.  The value can
         be positive or negative but MUST NOT be zero.  A negative
         integer means the nth-last occurrence within that period (i.e.,
         -1 is the last occurrence, -2 the one before that, etc.).

         This is the ordinal part of the BYDAY value in iCalendar (e.g.,
         1 or -3).

   **byMonthDay**: "Int[]" (optional)
      These are the days of the month on which to repeat.  Valid values
      are between 1 and the maximum number of days any month may have in
      the calendar given by the "rscale" property and the negative
      values of these numbers.  For example, in the Gregorian calendar,
      valid values are 1 to 31 and -31 to -1.  Negative values offset
      from the end of the month.  The array MUST have at least one entry
      if included.

      This is the BYMONTHDAY part in iCalendar.

   **byMonth**: "String[]" (optional)
      These are the months in which to repeat.  Each entry is a string
      representation of a number, starting from "1" for the first month
      in the calendar (e.g., "1" means January with the Gregorian
      calendar), with an optional "L" suffix (see [RFC7529]) for leap
      months (this MUST be uppercase, e.g., "3L").  The array MUST have
      at least one entry if included.

      This is the BYMONTH part from iCalendar.

   **byYearDay**: "Int[]" (optional)
      These are the days of the year on which to repeat.  Valid values
      are between 1 and the maximum number of days any year may have in
      the calendar given by the "rscale" property and the negative
      values of these numbers.  For example, in the Gregorian calendar,
      valid values are 1 to 366 and -366 to -1.  Negative values offset
      from the end of the year.  The array MUST have at least one entry
      if included.

      This is the BYYEARDAY part from iCalendar.

   **byWeekNo**: "Int[]" (optional)
      These are the weeks of the year in which to repeat.  Valid values
      are between 1 and the maximum number of weeks any year may have in
      the calendar given by the "rscale" property and the negative
      values of these numbers.  For example, in the Gregorian calendar,
      valid values are 1 to 53 and -53 to -1.  The array MUST have at
      least one entry if included.

      This is the BYWEEKNO part from iCalendar.

   **byHour**: "UnsignedInt[]" (optional)
      These are the hours of the day in which to repeat.  Valid values
      are 0 to 23.  The array MUST have at least one entry if included.
      This is the BYHOUR part from iCalendar.

   **byMinute**: "UnsignedInt[]" (optional)
      These are the minutes of the hour in which to repeat.  Valid
      values are 0 to 59.  The array MUST have at least one entry if
      included.

      This is the BYMINUTE part from iCalendar.

   **bySecond**: "UnsignedInt[]" (optional)
      These are the seconds of the minute in which to repeat.  Valid
      values are 0 to 60.  The array MUST have at least one entry if
      included.

      This is the BYSECOND part from iCalendar.

   **bySetPosition**: "Int[]" (optional)
      These are the occurrences within the recurrence interval to
      include in the final results.  Negative values offset from the end
      of the list of occurrences.  The array MUST have at least one
      entry if included.  This is the BYSETPOS part from iCalendar.

   **count**: "UnsignedInt" (optional)
      These are the number of occurrences at which to range-bound the
      recurrence.  This MUST NOT be included if an "until" property is
      specified.

      This is the COUNT part from iCalendar.

   **until**: "LocalDateTime" (optional)
      These are the date-time at which to finish recurring.  The last
      occurrence is on or before this date-time.  This MUST NOT be
      included if a "count" property is specified.  Note that if not
      specified otherwise for a specific JSCalendar object, this date is
      to be interpreted in the time zone specified in the JSCalendar
      object's "timeZone" property.

      This is the UNTIL part from iCalendar.

## Example:
GIVEN ics file:
```
RRULE:FREQ=WEEKLY;BYDAY=WE;UNTIL=20170111T090000Z
```

Return:
```json
{
	"recurrenceRules": [{
		"frequency": "weekly",
		"until": "2017-01-11T16:00:002017-01-11T16:00:00",
		"byDay": ["we"]
	}]
}
```

## DoD
- Add this piece in EventCalendar/parse spec.
- Implementation + test

**Comment by vttranlina** [comment]
pr https://github.com/linagora/tmail-backend/pull/620
