### ISSUE TITLE
[Bug] Change username mapping is not deleted when remove user by webadmin

### ISSUE THREAD

**Issue by vttranlina** [linagora/tmail-backend#606]
- Alice change username to Bob
- Webadmin remove Alice + Bob
- Webadmin create Alice
error: 

```
{
    "statusCode": 409,
    "type": "WrongState",
    "message": "'alice@localhost' already have associated mappings: forward:bob@localhost",
    "details": "'alice@localhost' already have associated mappings: forward:bob@localhost"
}
```

**Comment by quantranhong1999** [comment]
I am not sure but I think the rationale is James does not support a proper user deletion yet. Likely today when deleting a user, we just delete the entry from the user repository while do not delete the related data yet.

**Comment by chibenwa** [comment]
Correct.

We would likely need to get an extension mechanism to allow doing this (delete user data)

Please note that deleting a user without deleting his data is valuable (desactivate a user)

**Comment by chibenwa** [comment]
IMO can close this.
