### ISSUE TITLE
[Bug] - Migrate change username will be aborted when newUser already has an inbox

### ISSUE THREAD

**Issue by vttranlina** [linagora/tmail-backend#607]
- Bob already has an inbox mailbox (no messages)
- Alice change her username to Bob by webadmin
- Get task status, the result is ABORTED

**Comment by quantranhong1999** [comment]
Is this more like `linagora/james-project` issue?

**Comment by chibenwa** [comment]
Correct. In this case if the target mailbox already exist, we likely should move the content from the old mailbox to the new.

**Comment by vttranlina** [comment]
What should we do if Bob has old mailboxes, messages, subscriptions... (before migration)?

(1). Migrate BOB mailbox1 -> mailbox1.ARCHIVE 
- Continue Migrate ALICE -> BOB as normal

(2). Keep all old BOB mailbox data (messages, subscriptions...)
- Migrate Alice -> Bob 

(3). Delete all old BOB mailbox data (messages, subscriptions...)
- - Migrate Alice -> Bob

**Comment by Arsnael** [comment]
I think option 3 is definitely not what we want to do

I would say option 2?

**Comment by vttranlina** [comment]
To implement option 2, 
The `doRenameMailbox` method is quite complex. Difficult to handle `MailboxExistsException` in it...

**Comment by quantranhong1999** [comment]
How about option 2, let say BOB has mailbox X existed
- Rename `Bob X mailbox` -> `Bob X-migrating mailbox`
- Rename `Alice mailbox X` -> `Bob mailbox X`
- Copy messages in `Bob X-migrating mailbox` to `Bob mailbox X`, and then delete `Bob X-migrating mailbox`?

**Comment by vttranlina** [comment]
pr https://github.com/apache/james-project/pull/1492
