### ISSUE TITLE
Add LSC in tmail/backend demo

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-backend#623]
Feature:

 - [x] Identity synchronisation
 - [x] Auto-complete

Add a step in `dev.sh` that runs the two LSC scripts using docker commands.

Once merged notify @tissarni  for integration in the Twake Workplace

**Comment by quantranhong1999** [comment]
https://github.com/linagora/tmail-backend/pull/619#issuecomment-1487976784
