### ISSUE TITLE
[EPIC] JMAP extension for the deleted message vault

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-backend#628]
## What?

Allows a user to restore deleted messages.

We will write a JMAP extension allowing a user to restore deleted messages. (Similar to https://james.apache.org/server/manage-webadmin.html#Restore_Deleted_Messages )

Limitation: it should not be possible to restore more than `5` (configurable) messages at the same time - applied as a limit - only `5` first only are restored. If too much messages are present, the first `5` messages will be returned.

## Why?

Data retrieval is a nice to have feature.

## TODO

 - [ ] ADR
 - [ ] JMAP extension specification
 - [ ] Task split

**Comment by Arsnael** [comment]
Tasks:

- ADR
- JMAP specification
- JMAP implementation + Unit tests
- Guice bindings + Integration tests

**Comment by vttranlina** [comment]
Before split the task for `JMAP implementation + Unit tests`, I has a question: https://github.com/linagora/tmail-backend/issues/674#issuecomment-1541337140
