### ISSUE TITLE
[EPIC] Setting extension for TeamMail

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-backend#630]
## Why

Enable a client to store per-user setting on the backend side.

Capability name: `com:linagora:params:setting` will unlock the `Settings` object (singleton), and with it the `Settings/get` and `Settings/set` methods.

Settings is a free floating `String[String]` map being set by the client. Our extension should include a registry of known usage from TeamMail mobile app, and usage.

## Use cases

 - Import my attachments into TDrive
 - (Allow data collection for the knowledge graph) CF https://github.com/linagora/james-project-private/issues/562
 - Automation: archival, cleanup trash and spam
 - Always ask for read receipts
 - Timezone
 - Language
 - Appearance?
 - Enable PUSH notifications. (Can allow a user to fully forbid his data to transit through FCM...)...)
 - Spam banner warning
 - Email deletion warning
 - attachment reminder warning
 - Likely much much more...
 
## Example
 
```
{
  "sessionState": "${SESSION_STATE.value}",
  "methodResponses": [[
    "Settigns/get",
    {
      "accountId": "29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6",
      "state": "${INSTANCE.value}",
      "list": [
        {
          "id":"singleton",
          "tdrive.attachment.import.enabled": "true",
          "knowledgegraph.collection.enabled": "true",
          "firebase.enabled": "true",
          "timezone": "UTC+7",
          "trash.cleanup.enabled": "true",
          "trash.cleanup.period": "weekly",
          "spam.cleanup.enabled": "true",
          "spam.cleanup.period": "monthly",
          "inbox.archival.enabled": "true",
          "inbox.archival.period": "monthly",
          "inbox.archival.format": "yearly",
          "appearance.theme": "dark",
          "language": "fr",
          "read.receipts.always": "false",
          "warnings.spam.banner": "true",
          "warnings.attachment.reminder": "false",
          "warnings.email.deletion": "true"
        }
      ],
      "notFound": []
    },
    "c1"]]
}
```

### Cassandra storage

PK: username

C: Map[String, String]

**Comment by quantranhong1999** [comment]
- ADR  
  - Document the Settings JMAP API
  - Setting storage API + test contract + memory implementation + memory tests
  - Cassandra implemenation of the Setting storage API
  - advertise `com:linagora:params:setting` capability
  - Implement Settings/get
  - Implement Settings/set (full reset)
  - Implement Settings/set (delta: add /remove single value)
  - Push for Settings
  - Setting to enable Push for firebase

**Comment by chibenwa** [comment]
Please team:

 - ASAP: register your names on tickets you would groom (2 each).

For next week grooming n*2:

 -> Draft an ADR
 -> Draft a spec
 -> Groom your tickets nheeee

**Comment by quantranhong1999** [comment]
> -> Draft an ADR
-> Draft a spec

I just created these two tickets (without content yet) with high priority in TODO column, so the team does not forget.

**Comment by Arsnael** [comment]
I would change `com:linagora:params:setting` to `com:linagora:params:jmap:settings`

**Comment by Arsnael** [comment]
cc @hoangdat @dieptran88
