### ISSUE TITLE
[EPIC] Automations

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-backend#631]
Automations are a CRON that assist user in managing his emails. This includes `Automated INBOX archival`, `Spam cleanup` and `Trash cleanup` for now. CF front story: https://github.com/linagora/tmail-flutter/issues/1326

Design a `Task` scheduled with a `nightly cron` for aplying those settings.

**Comment by Arsnael** [comment]
Food for thoughts, quickly how I would see this in steps:

## Backend settings to enable trash cleanup

```
"trash.cleanup.enabled": "true",
"trash.cleanup.period": "weekly",
```
=> setting implem on tmail-backend + doc

## Settings to enable spam cleanup

```
"spam.cleanup.enabled": "true",
"spam.cleanup.period": "monthly",
```
=> setting implem on tmail-backend + doc

## Settings to enable inbox archival

```
"inbox.archival.enabled": "true",
"inbox.archival.period": "monthly",
"inbox.archival.format": "yearly",
```
=> setting implem on tmail-backend + doc

## Webadmin task for trash cleanup

webadmin task that would list users, check if they have the setting `trash.cleanup.enabled` to true (I think if missing we don't cleanup?) and do cleanup messages in trash older than the configured period.

=> `-XPOST http://ip:port/mailboxes?task=CleanupTrash` ?

+ webadmin doc

## Webadmin task for spam cleanup

webadmin task that would list users, check if they have the setting `spam.cleanup.enabled` to true (I think if missing we don't cleanup?) and do cleanup messages in spam older than the configured period.

=> `-XPOST http://ip:port/mailboxes?task=CleanupSpam` ?

+ webadmin doc

## Webadmin task for inbox archival

webadmin task that would list users, check if they have the setting `inbox.archival.enabled` to true (I think if missing we don't archive?) and do archive messages in inbox older than the configured period under the configured format.

=> `-XPOST http://ip:port/mailboxes?task=ArchiveInbox` ?

+ webadmin doc

## [Preprod] setup cronjobs

Add cronjobs in helm charts and deploy. To do after completion and release  of tasks above + sync with frontend team

## [Prod] setup cronjobs

Add cronjobs in prod. To do after completion and release  of tasks above + sync with frontend team

**Comment by quantranhong1999** [comment]
I thought basically as same as you.

Maybe just a concern point on the route path. `/mailboxes` is already taken by `MailboxesRoutes` on James. I am not sure we can write another web admin route (on TMail) with the same basic path.

**Comment by Arsnael** [comment]
Oh no pretty sure we can, just add some bindings, most of the tasks are depending on that route actually if you look at webadmin doc :) 

I remember we did some work so people could add custom tasks to it..?

**Comment by quantranhong1999** [comment]
I mean another issue e.g.:
- `MailboxesRoutes` with basic path `/mailboxes` on James
- `CronjobMailboxRoutes` with basic path `/mailboxes` on TMail

Then one of the two routes would be selected by Spark and the other would be skipped.

I remember we encounter the same issue before.

**Comment by chibenwa** [comment]
EASY: Tmail can inject mailbox tasks in James <3

**Comment by Arsnael** [comment]
Yes we can inject them, remember was a refactoring a while ago

**Comment by vttranlina** [comment]
> `-XPOST http://ip:port/mailboxes?task=CleanupTrash`

We should have one more param for filtering by `period`, if not we don't know which user needs to run
ex 
`task=CleanupTrash&period=weekly`

**Comment by vttranlina** [comment]
Will we use the JmapSettings (that we implemented in the previous sprint) to store the settings?

**Comment by Arsnael** [comment]
Yes the period will be fetched from the settings

**Comment by vttranlina** [comment]
> Yes the period will be fetched from the settings so not necessary to have a query param for it IMO

I think the cron would call to task via web-admin:

User1: `"trash.cleanup.period": "weekly"`
User2: `"trash.cleanup.period": "monthly"`

cron 1 (weekly) -> `?task=CleanupTrash`
cron 2 (monthly) -> `?task=CleanupTrash`

how the `cron1` can fetch only user1 if without period?

**Comment by Arsnael** [comment]
No you just have one cron...

As said above, I think the task would just list all users, check their settings if the trash cleanup is enabled for that user, then check the period, and cleanup mail older than the period. No need to make it more complex than that :) 

If you start having a cron for every period for every type of settings, it's infernal, if you had an other period later, you need to create an other cron... It becomes quickly a nightmare to manage. Let's keep it simple, one generic global task => 1 cron :)

**Comment by vttranlina** [comment]
Edge case when archive:
- The first time 
- Change weekly -> monthly
What should we do? cc @chibenwa

**Comment by vttranlina** [comment]
We don't need to do something in Backend settings. The setting will be done via JMAP Method.

**Comment by chibenwa** [comment]
> Change weekly -> monthly
> What should we do? cc @chibenwa

Just start archiving with the new folder pattern.

Do not change already archived emails ^^

**Comment by Arsnael** [comment]
That's what we likely thought as well, just wanted to confirm thanks :)

**Comment by Arsnael** [comment]
Tasks:

- https://github.com/linagora/tmail-backend/issues/821
- https://github.com/linagora/tmail-backend/issues/822
- https://github.com/linagora/tmail-backend/issues/823
- https://github.com/linagora/james-project-private/issues/714
- https://github.com/linagora/james-project-private/issues/713
