### ISSUE TITLE
Add APISIX in the demo OIDC docker compose on TMail

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/tmail-backend#638]
## Why
  The final goal is to replace KrakenD in the TMAIL OIDC demo with APISIX.
  We can start by duplicate another API Gateway for James (APISIX) in the demo, and remove KrakenD in the end when APISIX features are fully setup.

  ## How
  Add APISIX (standalone mode?) in the TMail OIDC demo, make sure it is up, running and usable.

  ## DoD
  APISIX is running and usable.

**Comment by vttranlina** [comment]
Resolve https://github.com/linagora/tmail-backend/pull/652
