### ISSUE TITLE
Add OPTIONS routes to APISIX

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/tmail-backend#639]
## Why
We need to apply APISIX's cors plugin for our routes, just like what we did with KrakenD.
  
## How
- Refer to old KrakenD configuration regarding CORS
- Setup APISIX cors plugin in our TMail OIDC demo https://apisix.apache.org/docs/apisix/plugins/cors/

## DoD
TMail OIDC demo: (when OPTIONS + GET) CORS headers info from JMAP service is retain.

**Comment by quantranhong1999** [comment]
Question: Why do we need the CORS plugin when APISIX already returns the CORS information from James JMAP?

E.g OPTIONS for `/jmap/session`:
![Image](https://user-images.githubusercontent.com/55171818/230586553-b50171dd-df93-4871-ba4a-e4b92cb73755.png)

GET for `/jmap/sesson`:

![Image](https://user-images.githubusercontent.com/55171818/230586653-cea43eb3-2995-43f0-9147-ac1dd3003b90.png)

**Comment by Arsnael** [comment]
Maybe no need then ! I think Krakend was just blocking CORS calls, so we had to explicitly use the CORS plugin, despite james managing them for JMAP. 

If APISIX allows us to call the OPTIONS endpoint then yes we might not need it. Thanks for checking it :)

**Comment by Arsnael** [comment]
Just add OPTIONS method to the endpoints in APISIX conf, TMail can handle OPTIONS. No need for CORS plugin

**Comment by quantranhong1999** [comment]
https://github.com/linagora/tmail-backend/pull/661
