### ISSUE TITLE
Add OIDC jmap endpoints + SSO

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/tmail-backend#640]
## Why
  We need to be able to access JMAP endpoints via APISIX, with credentials authenticated by OIDC LemonLDAP

  ## How
  - Develop an AuthenticationStrategy that parses username from the `X-Userinfo` header (from APISIX) e.g XUserInfoAuthenticationStrategy + Unit test
    Example of a decoded X-Userinfo (got from APISIX + LemonLDAP using jwks validation):
```json
    {
      "sid": "kYAxA79LR+AE9Chbss+EKC2wLEuYw8BmQ28Skx5FQDA",
      "iss": "http://sso.example.com",
      "sub": "james-user@tmail.com",
      "iat": 1680855991,
      "exp": 1680859591,
      "scope": "openid",
      "aud": [
        "james"
      ],
      "client_id": "james",
      "jti": "18b666335b4e93c6192dbb5e818f0a03f82df0dc48be4e68db3101ea20d8b960"
    }
```

  - Configure `XUserInfoAuthenticationStrategy` in demo's jmap.properties
  - Create routes in APISIX that map to JMAP endpoints. E.g `/jmap/session`, `/jmap`,...
  - Configure OIDC token validation for APISIX using the openid-connect plugin
    E.g plugin conf:
```json
    {
      "_meta": {
        "disable": false
      },
      "bearer_only": true,
      "client_id": "james",
      "client_secret": "james",
      "discovery": "http://sso.example.com/.well-known/openid-configuration",
      "use_jwks": true
    }
```

  ## DoD
  JMAP endpoints are accessible via APISIX, with SSO using LemonLDAP

**Comment by vttranlina** [comment]
> Develop an AuthenticationStrategy that parses username from the X-Userinfo header (from APISIX) e.g

Should we add Header Key  in the properties configuration file?
Eg: `userinfo.header.key =  X-Userinfo`

**Comment by Arsnael** [comment]
Token introspection way

**Comment by vttranlina** [comment]
pr https://github.com/linagora/tmail-backend/pull/655
