### ISSUE TITLE
[APISIX] Helm chart 

### ISSUE THREAD

**Issue by vttranlina** [linagora/tmail-backend#642]
## Why

We need to deploy APISIX on k8s preprod, sandbox. 
Helm chart for Apisix will do this

## How 

Ref: Krakend helm chart: https://gitlab.com/linagora_private/saas/tools/helm-charts/helm-krakend

## Dod

Deploy on preprod, sandbox

**Comment by Arsnael** [comment]
Actually after trying a couple of stuff, the FAQ: https://apisix.apache.org/docs/helm-chart/FAQ/

The apisix helm chart doesn't really allow to start in standalone, they advice to just do our own helm chart. But with the skeleton given shouldn't be too hard to get it up and running.

Or maybe we don't want standalone for helm chart actually, we want etcd alongside apisix?

**Comment by Arsnael** [comment]
Hmmm for the WIP => https://gitlab.com/linagora_private/saas/tmail/emaily-staging-apps/-/merge_requests/41

I have issues...

Clearly mounting and applying the apisix.yaml file in the conf is useless. Tried but yes, I think it's only possible to define the routes via conf in standalone mode. However here we want to be able to scale up Apisix if needed, so we need traditional deployment mode with etcd.

I'm not completely sure but I think maybe the apisix ingress controller helm chart could help: https://apisix.apache.org/docs/ingress-controller/getting-started/ . It seems we can define routes with it... Need to test as it seems rather obscure to me now.

An alternative could be to have a container launching a bash script with curl commands towards admin apisix to create the routes but it does not sound really great to me.

I will check the apisix ingress controller

**Comment by Arsnael** [comment]
Notes : 
- will need the custom image for SLO at some point
- should implement admin creds as secret and not keep default values

**Comment by Arsnael** [comment]
WIP -> https://gitlab.com/linagora_private/saas/tmail/emaily-staging-apps/-/merge_requests/41#note_1386103651

**Comment by Arsnael** [comment]
Work here is enough after those get merged. For the rest: https://github.com/linagora/james-project-private/issues/638
