### ISSUE TITLE
[APISIX] Add circuit breaker plugin

### ISSUE THREAD

**Issue by Arsnael** [linagora/tmail-backend#643]
We need to add the circuit breaker plugin for APISIX, like we have for Krakend.

You can check the Krakend conf and the doc of the apisix plugin here: https://apisix.apache.org/docs/apisix/plugins/api-breaker/

DoD: Setup circuit breaker for jmap routes, then put try to generate errors from JMAP server by sending lots of requests at once until the circuit breaker goes into effect

**Comment by vttranlina** [comment]
pr https://github.com/linagora/tmail-backend/pull/662
