### ISSUE TITLE
[APISIX] Add basic auth jmap endpoints with helm apisix conf

### ISSUE THREAD

**Issue by vttranlina** [linagora/tmail-backend#645]
## Why

We need to add the config to accept basic auth for jmap when request via Apisix, like we have for Krakend.

## How 

We need config headers_to_pass `Authentication` in apisix, and forward it to tmail_backend

- Ref: Krakend current config https://github.com/linagora/tmail-backend/blob/bfb39efcae39b22ea19e8fac0c9a161ea6afba14/demo/krakend/krakend.json#L92

## DoD
User can request to jmap endpoint (via Apisix) by basic authentication and get jmap result

Endpoint list:
- /jmap
- /jmap/session
- /.well-known/jmap
- /.well-known/webfinger
- /download 
- /upload

**Comment by Arsnael** [comment]
Missing linagora ecosystem route

Could maybe add them with the docker-compose too?

**Comment by quantranhong1999** [comment]
https://github.com/linagora/tmail-backend/pull/665
