### ISSUE TITLE
[APISIX] Add websocket endpoint with plugin

### ISSUE THREAD

**Issue by Arsnael** [linagora/tmail-backend#646]
In APISIX configuration, add the endpoint `/jmap/ws` for websocket with using the websocket plugin : https://apisix.apache.org/docs/dashboard/IMPORT_OPENAPI_USER_GUIDE/#extended-fields => `x-apisix-enable_websocket`

DoD : Can open a websocket connection to TMail through APISIX

**Comment by Arsnael** [comment]
Maybe can just declare a TCP endpoint for this and might work out of the box.... Need to try

**Comment by quantranhong1999** [comment]
https://github.com/linagora/tmail-backend/pull/663
