### ISSUE TITLE
[APISIX] Add TCP proxy for replacing haproxy with IMAP protocol

### ISSUE THREAD

**Issue by Arsnael** [linagora/tmail-backend#648]
Use the tcp proxy from apisix to set up connection with imap protocol on TMail : https://apisix.apache.org/docs/apisix/stream-proxy/

Maybe can you the keepalive_pool to set the idle timeout to 30mins: https://apisix.apache.org/blog/2021/07/28/release-apache-apisix-2.8/#new-feature-independent-keepalive-connection-pool

DoD: Can access IMAP protocol via APISIX with an idle timeout of 30mins

**Comment by chibenwa** [comment]
What is the added value of proxying IMAP with APISIX?

What features would we succeed to activate for IMAP? (rate limiting, flow control, etc...)

**Comment by quantranhong1999** [comment]
> Can access IMAP protocol via APISIX with an idle timeout of 30mins

How can we test that exactly? Opening a telnet connection and observing if it is not closed for at least 30m?

**Comment by chibenwa** [comment]
> How can we test that exactly? Opening a telnet connection and observing if it is not closed for at least 30m?

For instance, yes

**Comment by Arsnael** [comment]
I would be wary to check on the k8s part as well, to see if it allows us to bypass ovh fixed timeout idle limit or not

**Comment by quantranhong1999** [comment]
> I would be wary to check on the k8s part as well, to see if it allows us to bypass ovh fixed timeout idle limit or not

If you want to test this as part of the helm work: https://github.com/linagora/tmail-backend/pull/670

I think it is fine, just like the haproxy we used.

But I think the PO is more interested in the possible added plugins, otherwise, it is not worth switching from haproxy -> APISIX TCP proxy.

**Comment by Arsnael** [comment]
> But I think the PO is more interested in the possible added plugins, otherwise, it is not worth switching from haproxy -> APISIX TCP proxy.

Well we need both actually... If you can use the plugins but there is issues with the timeout it's a nogo too, as we want to respect the RFC as well around that :)
