### ISSUE TITLE
[JMAP] CalendarEvent/parse changes

### ISSUE THREAD

**Issue by Arsnael** [linagora/tmail-backend#650]
There has been a return on the jmap ML when exposing to the IETF JMAP group our work regarding the CalendarEvent/parse method: https://mailarchive.ietf.org/arch/msg/jmap/flHvSs97AKbggOVW1aCNSSIw6Ro/

It seems fastmail is having something similar internally so there seems to be a common interest here on the matter

Need to rework a bit the spec:
- use nominations that are more jmap spec compliant -> for example `blobIds: [Id]` should be `blobIds: Id[]` 
- support `properties` argument in the request
- the `parsed` field in the response should be `parsed: Id[CalendarEvent[]]`. Modify the code and the spec to match this
- a document exists already to convert from iCalendar properties to JsCalendar event properties. Use this instead of having our own way of converting: https://www.ietf.org/archive/id/draft-ietf-calext-jscalendar-icalendar-07.html

Final note: I would suggest to wait longer though before doing this to see if we get more feedback or not!

**Comment by Arsnael** [comment]
Neil suggesting to have the result type being JSCalendar rather than a CalendarEvent as well

**Comment by quantranhong1999** [comment]
code changes part: https://github.com/linagora/tmail-backend/pull/654

**Comment by chibenwa** [comment]
Please build a memory docker image to comunicate to the mobile team.

**Comment by Arsnael** [comment]
No need, work just got merged, the CI will build it. Just tell them to fetch from memory-branch-master tag from tomorrow
