### ISSUE TITLE
[Team-Mailboxes] Missing folder in team-mailboxes

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-backend#657]
## Today

Two system folder per team-mailbox: Inbox, Sent

## Expectations

`Inbox`, `Draft`, `Outbox`, `Sent`, `Trash`

**Comment by chibenwa** [comment]
CF https://github.com/linagora/tmail-flutter/issues/1769

**Comment by Arsnael** [comment]
The number of system mailboxes asked here and on the flutter ticket is different. 

Do we add Spam and Archive or not?

**Comment by chibenwa** [comment]
> Do we add Spam and Archive or not?

IMO no

**Comment by vttranlina** [comment]
pr https://github.com/linagora/tmail-backend/pull/659
