### ISSUE TITLE
[APISIX] Docker hub for linagora apisix javaplugin

### ISSUE THREAD

**Issue by vttranlina** [linagora/tmail-backend#669]
## Why?

https://github.com/linagora/tmail-backend/pull/664#discussion_r1180094768

## How 

Image: `linagora/apisix:3.2.0-debian-javaplugin`
Dockerfile: https://github.com/linagora/tmail-backend/blob/master/demo/apisix/Dockerfile

**Comment by chibenwa** [comment]
[linagora/apisix:3.2.0-debian-javaplugin](https://hub.docker.com/layers/linagora/apisix/3.2.0-debian-javaplugin/images/sha256-23215d85816e6ba1c806530f500c3bb8e760e0dcaebe26184884fd59ddcf733f?context=explore)
