### ISSUE TITLE
[Deleted Message Vault] JMAP specification

### ISSUE THREAD

**Issue by vttranlina** [linagora/tmail-backend#674]
## Why 

Epic: https://github.com/linagora/tmail-backend/issues/628

## How 
Location: https://github.com/linagora/tmail-backend/tree/master/docs/modules/ROOT/pages/tmail-backend/jmap-extensions

- Define the capability. 
   - Suggestion: `com:linagora:params:messages:vault`
- JMAP method 
   - Following the JMAP io: https://jmap.io/spec.html

**Comment by vttranlina** [comment]
Q: The restore is synchronize or async? If it is async, should we need one JMAP method to query the task result?

**Comment by vttranlina** [comment]
TODO
- [ ] Is JMAP Tasks related? https://jmap.io/spec-tasks.html

**Comment by Arsnael** [comment]
Synced I believe. A user sends a request via the jmap method, he would expect to get the mails recovered within the response. The async tasks are for webadmin usage

**Comment by Arsnael** [comment]
Example of a request / response? What would be the method name?

**Comment by chibenwa** [comment]
IMO we do not need to be synchronous.

We can just say "planned".

**Comment by chibenwa** [comment]
> Hmmm do we have a special mailbox then where we put those messages when treating the task?

Restored messages (what the task does by default).

> And if for some reason it fails... how is the user supposed to know?

If you return the taskId then the frontend can poll to see if the task is done or not or needs to be canceled....

**Comment by Arsnael** [comment]
> If you return the taskId then the frontend can poll to see if the task is done or not or needs to be canceled....

I'm not convinced that the client app should be able to access our webadmin like that, isn't that a bit concerning security wise?

**Comment by chibenwa** [comment]
```
["EmailRecoveryAction/set",
  {
    "create": {
        "clietid0":  {
          "deletedBefore": "UTC_DATE_A",
          "deletedAfter": "UTC_DATE_B",
          "receivedBefore": "UTC_DATE_C",
          "receivedAfter": "UTC_DATE_C",
          "hasAttachment": "true",
          "suject": "Simple topic",
          "sender": "bob@domain.tld",
          "receivers": "alice@domain.tld"
         }
      }
   },
   "#0"
]

Would return:

["EmailRecoveryAction/set",
  {
    "created" {
        "idclient0": { "id": "jamesTaskId" }
      },
      "notCreated: []
   },
   "#0"
]


["EmailRecoveryAction/get",
  {
    "ids": ["jamesTaskId"]
   },
   "#0"
]

Would return:

["EmailRecoveryAction/get",
  {
    "list": [{
        "id: "jamesTaskId",
        "status": "completed|waiting|canceled|inProgress"
    }],
    notFound: []
   },
   "#0"
]


["EmailRecoveryAction/set",
  {
    "cancel": ["jamesTaskId"]
   },
   "#0"
]

Would return:

Would return:

["EmailRecoveryAction/set",
  {
    "canceled" : ["jamesTaskId" ],
    "notCancelled": []
   },
   "#0"
]
```

For security reasons `EmailRecoveryAction/set cancel` and `EmailRecoveryAction/get` would need to validate that the task is a deleted message vault task of this user before proceeding to ANY action.

**Comment by Arsnael** [comment]
Further splitting would be required then. Thanks for the clarification :)
