### ISSUE TITLE
[Deleted Message Vault] [ADR] JMAP for deleted message vault

### ISSUE THREAD

**Issue by vttranlina** [linagora/tmail-backend#675]
## Why

Explain why we implement  the JMAP extension allowing a user to restore deleted messages
rf: https://james.apache.org/server/manage-webadmin.html#Restore_Deleted_Messages

Location: https://github.com/linagora/james-project-private/tree/master/adr

**Comment by Arsnael** [comment]
- want to have jmap because is the way to interact with mail server from mail app
- functional requirements include cancellation and progress
- technical requirements: want it to be async
- alternatives : Openpaas -> doing proxy api on top of webadmin for this
