### ISSUE TITLE
[Deleted message vault] Guice bindings + Integration tests

### ISSUE THREAD

**Issue by Arsnael** [linagora/tmail-backend#679]
Add the bindings of the new jmap method to Guice so we can use it with the different flavors of Tmail

Rewriting existing webadmin integration test for jmap method

DoD: Integration tests

**Comment by chibenwa** [comment]
CF server/protocols/webadmin-integration-test/webadmin-integration-test-common/src/main/java/org/apache/james/webadmin/integration/vault/DeletedMessageVaultIntegrationTest.java

**Comment by vttranlina** [comment]
PR https://github.com/linagora/tmail-backend/pull/699
