### ISSUE TITLE
[Deleted message vault] EmailRecoveryAction/get

### ISSUE THREAD

**Issue by Arsnael** [linagora/tmail-backend#680]
Implement the JMAP method for EmailRecoveryAction/get defined in https://github.com/linagora/tmail-backend/issues/674.

Note that for security reasons, we need to verify that the task is a deleted message vault task before returning the status of it. Return an error otherwise.

DoD: Implementation + Unit tests.

**Comment by quantranhong1999** [comment]
We may need to change the EmailRecoveryAction/get proposed.

https://github.com/linagora/tmail-backend/blob/c2590caccf3b4fb1649659e857408c954216f7b3/docs/modules/ROOT/pages/tmail-backend/jmap-extensions/deletedMessagesVault.adoc#emailrecoveryaction

For the query part (deletedBefore, deletedAfter...), we do not really store the submitted query in DB, except as TaskDTO via the Task queue which would be deleted after the message is consumed.
Getting the query part after submitting ATM would be tricky IMO.

So I propose more viable EmailRecoveryAction/get:
```
["EmailRecoveryAction/get",
	{
		"ids": ["2034-495-05857-57abcd-0876664"]
	},
	"#0"
]
```

response:
```
    ["EmailRecoveryAction/get",
    	{
    		"list": [{
    			"id": "2034-495-05857-57abcd-0876664",
    			"successfulRestoreCount": 99,
    			"errorRestoreCount": 1,
    			"status": "inProgress"
    		}],
    		"notFound": []
    	}, "#0"
    ]
```

Your opinion on this?

**Comment by chibenwa** [comment]
> we do not really store the submitted query in DB

IMO it would be easy to add it to the task details? 

But also OK with the proposed modifications BTW

**Comment by quantranhong1999** [comment]
> IMO it would be easy to add it to the task details?

Yes. But I feel this would not really be worth the additional while we could do smth simpler and still informative enough to users IMO.

**Comment by chibenwa** [comment]
Ok to me.

Please PR the spec first.

**Comment by quantranhong1999** [comment]
https://github.com/linagora/tmail-backend/pull/690

**Comment by Arsnael** [comment]
Ok to me as well :)
