### ISSUE TITLE
[Deleted message vault] EmailRecoveryAction/set update

### ISSUE THREAD

**Issue by Arsnael** [linagora/tmail-backend#681]
Implement the JMAP method for EmailRecoveryAction/set update defined in https://github.com/linagora/tmail-backend/issues/674.

Note that for security reasons, we need to verify that the task is a deleted message vault task before returning the status of it. Return an error otherwise.

Need to make sure we can only cancel a task that is waiting or in progress status. Might need to override deleted message vault to test it

DoD: Implementation + unit tests.

**Comment by vttranlina** [comment]
pr https://github.com/linagora/tmail-backend/pull/693
