### ISSUE TITLE
RabbitMQ: monitor consumer crash

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-backend#701]
### Description 

On production, the consumer of some queues stops.
Messages accumulates in the queue, effectively harming delivery

We wish to embed in TMail a mechanism to restart consumers if there is none of them.

### Fix

Run a check every minutes using `RabbitMQManagementAPI::queueDetails` on each critical queue (listed below).

If one of the queues have 0 consumers, emit a log and call `ReconnectionHandler`s to restart queue consumption.

Important queues:

 -  JamesMailQueue-workqueue-spool
 -  JamesMailQueue-workqueue-outgoing
 -  mailboxEvent-workQueue-org.apache.james.events.GroupRegistrationHandler$GroupRegistrationHandlerGroup
 -  jmapEvent-workQueue-org.apache.james.events.GroupRegistrationHandler$GroupRegistrationHandlerGroup

Have a configuration in rabbitmq.properties allowing disabling this behaviour.

We try it in TMail first then if it is working well we can generalize it.

**Comment by quantranhong1999** [comment]
https://github.com/linagora/tmail-backend/pull/705
