### ISSUE TITLE
JMAP specs for Labels

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/tmail-backend#702]
## Why
Write specifications for JMAP Label extensions that allows users to manipulate his mails by labels.

## How
Suggestions:
- New capability object `com:linagora:params:jmap:labels`. This object could be empty.

- `Label` object properties:
  - id: id, server-set
  - displayName: String.  Display name of the Label on UI. E.g `Custom Tag 1`.
  - keyword: String, server-set. Case-insensitive. e.g `custom_tag_1`  (or a hash value of the displayName)
  - color: Color|null

  The `Color` data type need to be a hex code. E.g: #000000 (black)

- `Label/get` example

  Request:
  ```json
  {
    "using": ["urn:ietf:params:jmap:core", "com:linagora:params:jmap:labels"],
    "methodCalls": [
      [
        "Label/get",
        {
          "accountId": "29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6",
          "ids": ["123456", "notFound"]
        },
        "c1"
      ]
    ]
  }
  ```

  Response:
  ```json
  {
    "sessionState": "2c9f1b12-b35a-43e6-9af2-0106fb53a943",
    "methodResponses": [
      [
        "Label/get",
        {
          "accountId": "29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6",
          "state": "2c9f1b12-b35a-43e6-9af2-0106fb53a943",
          "list": [{
            "id": "123456",
            "displayName": "Custom Tag 1",
            "keyword": "custom_tag_1",
            "color": "#000000"
          }],
          "notFound": [
            "notFound"
          ]
        },
        "c1"
      ]
    ]
  }
  ```
  Then client can search emails of the Label `Custom Tag 1` by keyword `custom_tag_1`.

  Notes: should support ids: null to get all Labels.

- `Label/set` example:

  Request:
  ```json
  {
    "using": ["urn:ietf:params:jmap:core", "com:linagora:params:jmap:labels"],
    "methodCalls": [
      [
        "Label/set", {
          "accountId": "29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6",
          "create": {
            "4f29": {
              "displayName": "Important",
              "color": "#00ccdd"
            }
          }
        }, "0"
      ]
    ]
  }
  ```

  Response:
  ```json
  {
    "sessionState": "2c9f1b12-b35a-43e6-9af2-0106fb53a943",
    "methodResponses": [
      ["Label/set", {
        "accountId": "29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6",
        "newState": "2c9f1b12-b35a-43e6-9af2-0106fb53a943",
        "created": {
          "4f29": {
            "id": "123456",
            "keyword": "important"
          }
        }
      }, "0"]
    ]
  }
  ```

  Notes: We only support updating color. We do not support destroy?
  (IMO if we do not do inter-operability with IMAP we should support destroy label. And we should support update label display name).

- `Label/changes` example

  Request:
  ```json
  {
    "using": ["urn:ietf:params:jmap:core", "com:linagora:params:jmap:labels"],
    "methodCalls": [
      [
        "Label/changes",
        {
          "accountId": "29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6",
          "sinceState": "2c9f1b12-b35a-43e6-9af2-0106fb53a943"
        },
        "c1"
      ]
    ]
  }
  ```

  Response:
  ```json
  {
    "sessionState": "2c9f1b12-b35a-43e6-9af2-0106fb53a943",
    "methodResponses": [
      ["Label/changes", {
        "accountId": "29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6",
        "oldState": "2c9f1b12-b35a-43e6-9af2-0106fb53a943",
        "hasMoreChanges": false,
        "created": ["123456"],
        "updated": ["654321"],
        "destroyed": []
      }, "c1"]
    ]
  }
  ```

## DoD
Team consensus.

**Comment by Arsnael** [comment]
> I propose a bit of change compared to the last meeting:
> 
> * We should add `displayName` field to the `Label` object (for UI to display the label, otherwise only the keyword (which is case-insensitive and does not support space character) is ugly)

Seeing how TB is not really nice regarding interoperability (as you experimented), I think this proposal is fair. 
Question though: how is the mailbox listener supposed to handle the case of a keyword created by TB for the display name? Is it empty and we let the front decide what to do in this case? (displaying keyword instead, with possibility for user to edit it for example?) 

> * Client may not need to care to set keyword corresponding to a Label for simpler UX (therefore `keyword` is server-set)

Might be ok and make things simpler. Could maybe do like TB? keyword -> label name sanitized with dashes for spaces, all in minor cases, etc

> * Client should be able to update the label name, and label color.

Would make sense with above statements yes

> * Client should be able to destroy a label.

That I'm not convinced... Might create potentially issues with IMAP? Deleting the jmap label will not delete the keyword, might confuse the user if he uses both and could bring some strange use cases

**Comment by quantranhong1999** [comment]
> That I'm not convinced... Might create potentially issues with IMAP? Deleting the jmap label will not delete the keyword, might confuse the user if he uses both and could bring some strange use cases

We could write a LabelDestroyListener to remove the keyword maybe?

**Comment by Arsnael** [comment]
I meant I'm not sure how imap clients like TB would react in this case. Maybe would try to sync and recreate it on james side? Or maybe not... I would say let's keep it simple for now?

**Comment by Arsnael** [comment]
Ah extra note when rereading the examples: 

I don't think we need the capability `urn:ietf:params:jmap:mail` for label methods :)

**Comment by quantranhong1999** [comment]
https://github.com/linagora/tmail-backend/pull/712
