### ISSUE TITLE
LabelRepository interface + memory implementation

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/tmail-backend#703]
## Why
We need a interface to interact with the storage layer for managing Labels.
And a simple memory implementation for it.

## How
- Interface `LabelRepository` (could be a trait as well):

```java
record Label(LabelId id, DisplayName displayName, Keyword keyword, Optional<Color> color);
record LabelCreationRequest(DisplayName displayName, Optional<Color> color);

interface LabelRepository {
    Publisher<Label> addLabel(User user, LabelCreationRequest label);

    Publisher<Label> addLabels(User user, Collection<LabelCreationRequest> labels);

    Publisher<Void> updateLabel(User user, LabelId id, Optional<DisplayName> newDisplayName, Optional<Color> newColor);

    Publisher<Label>  listLabels(User user);
    
    Publisher<Void> deleteLabel(User user, LabelId id);

}
```

Then write a memory impl for it + contract test for the APIs.

## DoD
Contract tests.

## Notes
keyword should be unique per user IMO.

**Comment by vttranlina** [comment]
```
 Mono<Label> addLabel(User user, LabelCreationRequest label);

 Flux<Label> addLabels(User user, Collection<LabelCreationRequest> labels);
```
or: 
```
Flux<Label> addLabels(User user, LabelCreationRequest... labels);
```

**Comment by vttranlina** [comment]
```
    Mono<Void> updateLabel(User user, LabelId id, DisplayName newDisplayName, Optional<Color> newColor);
```
`newDisplayName` is required for each update request?

**Comment by quantranhong1999** [comment]
> `newDisplayName` is required for each update request?

No. Likely can make it Optional there.

**Comment by quantranhong1999** [comment]
> Flux<Label> addLabels(User user, LabelCreationRequest... labels);

Yes. But actually, I have concerns about the ordering of creation requests using the Flux API (normally we use just Mono?).
e.g Label/set create request:
```json
	"create": {
		"creationId1": {
			...
		},
		"creationId2": {
			...
		},
		"creationId3": {
			...
		}
	}
```

We need to make sure the response keeps the mapping:
```json
	"created": {
		"creationId1": {
			"id": "1"
		},
		"creationId2": {
			"id": "2"
		},
		"creationId3": {
			"id": "3"
		}
	}
```

**Comment by vttranlina** [comment]
>  I have concerns about the ordering of creation requests

We we need to order while it is a map, with key (creationId1, creationId2, creationId3)? 

> using the Flux API (normally we use just Mono?).

Not get all your points, the API concatMap is oke?

**Comment by quantranhong1999** [comment]
WIP: https://github.com/linagora/tmail-backend/pull/721

interface first so it wont block anyone.
