### ISSUE TITLE
Label/set create JMAP method

### ISSUE THREAD

**Issue by Arsnael** [linagora/tmail-backend#708]
Implement the /set create JMAP method defined in https://github.com/linagora/tmail-backend/issues/702

Request:
  ```json
  {
    "using": ["urn:ietf:params:jmap:core", "com:linagora:params:jmap:labels"],
    "methodCalls": [
      [
        "Label/set", {
          "accountId": "29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6",
          "create": {
            "4f29": {
              "displayName": "Important",
              "color": "#00ccdd"
            }
          }
        }, "0"
      ]
    ]
  }
  ```

  Response:
  ```json
  {
    "sessionState": "2c9f1b12-b35a-43e6-9af2-0106fb53a943",
    "methodResponses": [
      ["Label/set", {
        "accountId": "29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6",
        "newState": "2c9f1b12-b35a-43e6-9af2-0106fb53a943",
        "created": {
          "4f29": {
            "id": "123456",
            "keyword": "important"
          }
        }
      }, "0"]
    ]
  }
  ```

Note: 
- keyword is server-set
- delegates should be able to create labels on the delegator account

DoD: Integration tests

**Comment by vttranlina** [comment]
What is `keyword` if `displayName` = "Trần Văn Tùng"? 

if `keyword` is a hash result of `displayName`, it looks not friendly. And less interaction with Thunderbird (in case matching  keyword)

**Comment by quantranhong1999** [comment]
> And less interaction with Thunderbird (in case matching keyword)

If you create a keyword (with whatever value) by JMAP, Thunderbird just does not show that keyword (likely no mapping to its display name on Thunderbird).

**Comment by vttranlina** [comment]
> What is `keyword` if `displayName` = "Trần Văn Tùng"?
> 
> if `keyword` is a hash result of `displayName`, it looks not friendly. And less interaction with Thunderbird (in case matching keyword)

removeAccents is good 
```
java.text.Normalizer.normalize("Tùng Trần Văn āăąēîïĩíĝġńñšŝśûůŷ", Normalizer.Form.NFKD)
            .replaceAll("[^\\p{ASCII}]", "")
            .replaceAll(" ", "_")
            .toLowerCase();
// result = tung_tran_van_aaaeiiiiggnnsssuuy
```

**Comment by vttranlina** [comment]
> If you create a keyword (with whatever value) by JMAP, Thunderbird just does not show that keyword (likely no mapping to its display name on Thunderbird).

In case a keyword with the value exists in Thunderbird. Thunderbird will show it.

**Comment by vttranlina** [comment]
Note: delegates should be able to create labels on the delegator account

**Comment by Arsnael** [comment]
https://github.com/linagora/tmail-backend/pull/726
