### ISSUE TITLE
Implement LabelChangeRepository + memory impl + contract test

### ISSUE THREAD

**Issue by vttranlina** [linagora/tmail-backend#714]
## Why
To store the Label change 

## How

```scala
trait LabelChangeRepository {
  def save(labelChange: LabelChange): Publisher[Void]

  def getSinceState(accountId: AccountId, state: State, maxIdsToReturn: Option[Limit]): Publisher[LabelChange]

  def getLatestState(accountId: AccountId): Publisher[State]
 // for delegate account
  def getLatestStateWithDelegation(accountId: AccountId): Publisher[State]
  def getSinceStateWithDelegation(accountId: AccountId, state: State, maxIdsToReturn: Option[Limit]): Publisher[LabelChange]
}

case class LabelChange(accountId: AccountId,
                       created: Set[LabelId],
                       updated: Set[LabelId] = Set(),
                       destroyed: Set[LabelId] = Set(),
                       newState: State,
                       hasMoreChanges: Boolean) extends JmapChange
```

Ref: MailboxChange, EmailChange

## Dod
- Memory impl + contract test

**Comment by vttranlina** [comment]
Should we care an `isDelegated: Boolean` for LabelChange?

**Comment by Arsnael** [comment]
I don't get why we need an extra LabelChangeRepository for the /changes operation? Why not adding needed methods in LabelRepository?

**Comment by vttranlina** [comment]
> I don't get why we need an extra LabelChangeRepository for the /changes operation? Why not adding needed methods in LabelRepository?

with `LabelRepository` how we can query by sinceState, detect created, updated?

**Comment by Arsnael** [comment]
Indeed, had thought a bit fast here before getting a meeting. You are right actually sorry :)

**Comment by vttranlina** [comment]
pr https://github.com/linagora/tmail-backend/pull/729
