### ISSUE TITLE
Implement Cassandra impl for LabelChangeRepository 

### ISSUE THREAD

**Issue by vttranlina** [linagora/tmail-backend#715]
Based on interface https://github.com/linagora/tmail-backend/issues/714

- Cassandra table:
```
- PK: ACCOUNT_ID (TEXT)
- CK: STATE (TIMEUUID)
- CREATED: frozenSetOf(TIMEUUID)
- UPDATED: frozenSetOf(TIMEUUID)
- DESTROYED: frozenSetOf(TIMEUUID)
- DATE: (ZONED_DATE_TIME)
```

- Create a LabelChangeRepositoryDAO for CRUD above table
- LabelChangeRepository uses DAO for business logic

**Comment by quantranhong1999** [comment]
could be a pair with @thanhbv200585

**Comment by chibenwa** [comment]
IS_COUNT_CHANGE: BOOLEAN -> not needed

deleted? updated?

**Comment by vttranlina** [comment]
TODO note: https://github.com/linagora/tmail-backend/pull/733#discussion_r1234712322
