### ISSUE TITLE
Populate changes to LabelChangeRepository in Label/set

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/tmail-backend#718]

**Comment by quantranhong1999** [comment]
Rethink about this: because we need to populate the Label changes to FCM also, so maybe we should do this asynchronously?

**Comment by chibenwa** [comment]
No not really you do not need to modify LabelChangeRepository asynchronously, you just need to publish your StateChange to Jmap event bus once it happens...

**Comment by chibenwa** [comment]
Ensure that Label/set oldState + newState is up to date

Postentally LabelChangeRepository just presists StateChanges for the Label entity

**Comment by vttranlina** [comment]
PR: https://github.com/linagora/tmail-backend/pull/733
