### ISSUE TITLE
Build should be strict about Scala imports ordering in the code

### ISSUE THREAD

**Issue by Arsnael** [linagora/tmail-backend#738]
For now, we do not have strict rules with Scala regarding import orders. Not everybody has the same layout and it potentially reduces readability in PRs on code change if somebody got a different import layout than the initial code.

We should be more strict on import ordering, like we do with Java.

Proposed layout:

```
base package imports
___blank line___
java
___blank line___
all other imports
___blank line___
scala
```

Should modify the scalafix maven plugin to do a strict check on import and fail the build if that last one isn't respected.

**Comment by chibenwa** [comment]
Please open a JIRA ticket on ASF side to track this.

**Comment by vttranlina** [comment]
JIRA ticket: https://issues.apache.org/jira/browse/JAMES-3917

**Comment by vttranlina** [comment]
PR: https://github.com/apache/james-project/pull/1604

TODO: 
- [ ]  Adapt int tmail-backend

**Comment by vttranlina** [comment]
tmail-backend pr https://github.com/linagora/tmail-backend/pull/749
