### ISSUE TITLE
Modularize TypeState

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-backend#74]
When writing JMAP extension, I should be able to add my owns TypeStates

 - [ ] `TypeState` should not be a sealed trait, just a trait
 - [ ] Each `Capability` provides a list of TypeState it does handle
 - [ ] A TypeStateRegistry is being injected the set of TypeStates and can be used to parse them.

## Definition of done

Being able to register specifically for filters updates:

```
{"@type": "WebSocketPushEnable","dataTypes" : ["Filters"]}
```

**Comment by quantranhong1999** [comment]
Not sure what I have to do, so here i what I think I have to do. Please have a look:
- In james-project 
  - modify TypeName from seal trait => trait
- In openpaas-james:
  - create some custom type name such as FilterTypeName:
``` 
object TypeStateRegistry {
  val ALLCUSTOM: Set[TypeName] = Set(FilterTypeName)

  def parse(string: String): Either[String, TypeName] = string match {
    case FilterTypeName.asString => Right(FilterTypeName)
    case _ => Left(s"Unknown typeName $string")
  }
}

case object FilterTypeName extends TypeName {
  override val asString: String = "Filter"
}
```
   - create a CustomStateChangeEvent, CustomStateChangeListener and CustomStateChangeListenerTest
   Or I should change this directly in james-project?

**Comment by chibenwa** [comment]
Option 1 is waaaaay better Quan:

 - modify TypeName from seal trait => trait
 - modify TypeName::parse. 
 
 We of course as you say need to modularize type name parsing:
 - Each type name would provide it's parser
 - a TypeNameParsers class being injected a `java.util.Set[TypeNameParsers]` would then go through the TpeNameParser until one works.
 
That way we can inject our owns.

We will need tests on James side however.

> create a CustomStateChangeEvent, CustomStateChangeListener and CustomStateChangeListenerTest
Or I should change this directly in james-project?

So much duplication! Let's not do that ;-)

**Comment by chibenwa** [comment]
Done
