### ISSUE TITLE
Auto-complete for team mailboxes

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-backend#741]
### Description of the bug

Today given I write for the first time a mail for cosoft-barcamp@linagora.com team mailbox, then no auto-completion result is proposed.

### Reproduction Steps

Send a mail to a team mailbox

### Expected result

I expect a search result to be proposed for existing team mailboxes.

Simply add the team mailbox into domain contacts after creation.

### Context

tmail.linagora.com

**Comment by quantranhong1999** [comment]
https://github.com/linagora/tmail-backend/pull/748
