### ISSUE TITLE
JMAP filtering: combine rule conditions

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-backend#757]
Following https://github.com/linagora/james-project/issues/4811 , adapt the JMAP RFC-8621 TMail filter API accordingly.

Preserve retro-compatibility:
 - Accept Filters/set at the old format
 - If a single condition is present, flatten it so that it appears at the old format.

**Comment by hungphan227** [comment]
I have created PR https://github.com/linagora/tmail-backend/pull/763. Please review
