### ISSUE TITLE
Auto-complete weird results 

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-backend#758]
### Description of the bug

![Screenshot from 2023-07-11 00-37-21](https://github.com/linagora/tmail-backend/assets/6928740/4b2cd687-d05c-4862-9065-05dd74fe770a)

Auto-complete: domain part matches localpart...

## Fix nb 1

Advice: If a `@` is mentionned only match on email field in https://github.com/linagora/tmail-backend/blob/750dceba9efe59541c6cd2798d789b0424f943f2/tmail-backend/jmap/extensions-es-v6/src/main/java/com/linagora/tmail/james/jmap/ES6EmailAddressContactSearchEngine.java#L132 ?

## Fix nb 2

https://github.com/linagora/tmail-flutter/issues/2024#issuecomment-1630030198

If the user input matches `.*@.*\..*` ie contains `@` then contains `.` THEN completion input should be prefixed by user input.

EG

I type: `btellier@linagora.c` then autocomplete result `btellier@linagora.com` is shown but not `whatever@linagora.com` (not prefixed by the search input).

## Definition of done

 - unit tests for fix nb 1 and 2 in the autocompleEngine contract
 - So patched for both ES6 and OpenSearch

**Comment by vttranlina** [comment]
About "Fix nb2"

I checked the current code and it works as expected. (we don't need to change anything)
I added a test case for that. 
https://github.com/linagora/tmail-backend/pull/767
