### ISSUE TITLE
OutOfMemoryError when run EnforceRateLimitingPlanTest

### ISSUE THREAD

**Issue by vttranlina** [linagora/tmail-backend#761]
### Description of the bug

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "lettuce-eventExecutorLoop***

### Reproduction Steps

Run  repeat until failure  `EnforceRateLimitingPlanTest`  (with my PC, it will throw when tests passed repeat at 2xx)

### Additional information

- Memory Heap dump file: 
https://tdrive.linagora.com/shared/111111114AxHLNjGvEGJpA/drive/2rCqjwQPJJivJWemudbsoj/t/26373379ca85b4a6ffdb71a425ad6dd3243c2bba

- Test run log
[test-run.log](https://github.com/linagora/tmail-backend/files/12065962/test-run.log)

- Another log: 
```
10:49:24.018 [ERROR] i.n.u.HashedWheelTimer - You are creating too many HashedWheelTimer instances. HashedWheelTimer is a shared resource that must be reused across the JVM, so that only a few instances are created.
java.lang.OutOfMemoryError: Java heap space
```

- Redis log: (0 clients connected)
```
2023-07-17T03:57:37.173041142Z 1:M 17 Jul 2023 03:57:37.172 . 0 clients connected (0 replicas), 862312 bytes in use
2023-07-17T03:57:42.185684229Z 1:M 17 Jul 2023 03:57:42.185 . 0 clients connected (0 replicas), 862312 bytes in use
```

- The Default IDE setting when run Junit: xms=512Mb xmx=1024Mb

**Comment by vttranlina** [comment]
MyIDE
![image](https://github.com/linagora/tmail-backend/assets/81145350/9629cbf9-963b-4b89-8aef-3a17ac71c400)

**Comment by vttranlina** [comment]
I guess it relates to `io.lettuce.core.resource.ClientResources`, which has not been closed correctly
So I tried to modify `org.apache.james.rate.limiter.redis.RedisRateLimiterFactory` is bellow
but I can't get better

```scala
class RedisRateLimiterFactory @Inject()(redisConfiguration: RedisRateLimiterConfiguration) extends RateLimiterFactory {

  var resources: ClientResources = _
  val rateLimitjFactory: AbstractRequestRateLimiterFactory[RedisSlidingWindowRequestRateLimiter] =
    if (redisConfiguration.isCluster) {
      val resourceBuilder = ClientResources.builder()
        .threadFactoryProvider(poolName => NamedThreadFactory.withName(s"redis-driver-$poolName"))
      redisConfiguration.ioThreads.foreach(value => resourceBuilder.ioThreadPoolSize(value))
      redisConfiguration.workerThreads.foreach(value =>resourceBuilder.computationThreadPoolSize(value))
      new RedisClusterRateLimiterFactory(RedisClusterClient.create(resourceBuilder.build(),
        redisConfiguration.redisURI.value.asJava))
    } else {
      val resourceBuilder = ClientResources.builder()
        .threadFactoryProvider(poolName => NamedThreadFactory.withName(s"redis-driver-$poolName"))
      redisConfiguration.ioThreads.foreach(value => resourceBuilder.ioThreadPoolSize(value))
      redisConfiguration.workerThreads.foreach(value => resourceBuilder.computationThreadPoolSize(value))
      resources = resourceBuilder.build();

      new RedisSingleInstanceRateLimitjFactory(RedisClient.create(resources, redisConfiguration.redisURI.value.last))
    }

  def preDestroy(): Unit = {
    resources.shutdown()
  }
```

**Comment by quantranhong1999** [comment]
May help to get some insights from the heap dump: https://heaphero.io/heap-report-wc.jsp?p=RThCZ0lOakJ3K2dCd3FiSEc4VEhscytQdnNlRUVoSExkWjdwdlY1T01IUzlVR1JsaGU4dFpzUGtZc1BFdE5vSnQ0SXNuNkNaMzhOdWM2N2hzdVBTZFE9PQ==

`5,094 instances of "io.netty.buffer.PoolThreadCache", loaded by "jdk.internal.loader.ClassLoaders$AppClassLoader @ 0xc0b26618" occupy 705,688,952 (66.28%) bytes`

My guess: We initiate multiple times the lettuce driver in tests, and in somehow the driver is not freed after each test.
```
@BeforeEach
redisRateLimiterFactory = new RedisRateLimiterFactory(RedisRateLimiterConfiguration.from(redis.redisURI().toString, isCluster = false))
```

Not a big deal in tests IMO.
But in production `RedisRateLimiterFactory` should be in SINGLETON scope IMO.

**Comment by vttranlina** [comment]
local issue
