### ISSUE TITLE
Enable Quota RFC-9245 compatibility mode.

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-backend#765]
Add by default the corresponding system property

**Comment by chibenwa** [comment]
CF https://github.com/linagora/james-project/issues/4814

**Comment by quantranhong1999** [comment]
https://github.com/linagora/tmail-backend/pull/768

**Comment by quantranhong1999** [comment]
https://ci.linagora.com/linagora/lrs/saas/tools/helm-charts/tmail-backend/-/merge_requests/7

**Comment by Arsnael** [comment]
Approved and merged. Need to deploy I guess and check with frontend :)

**Comment by quantranhong1999** [comment]
> Need to deploy I guess and check with frontend

No need to deploy this IMO. The current version 0.7.0 rc1 on preprod only contains the JMAP Quota draft (long time no release).
This change would be auto-deployed upon the new release.

> Also need to tell frontend team they can move on jmap quota refactoring if successful

I already give them https://github.com/linagora/james-project/issues/4814#issuecomment-1632192946
