### ISSUE TITLE
Investigate the performance test issue

### ISSUE THREAD

**Issue by vttranlina** [linagora/tmail-backend#769]
- The performance test with image `linagora/tmail-backend:distributed-branch-master` has a lot of KO errors. 
While the image `distributed-0.7.0-rc1` is ok with the same scenario

```
> emailQuery: Failed to build request: No attribute named 'inbox    154 (18.85%)
ID' is defined 
> jsonPath($.methodResponses[1][1].created).find.exists, found n    100 (12.24%)
othing
> jsonPath($.methodResponses[0][1].list[*]).find.exists, found n     99 (12.12%)
othing
> emailGet: Failed to build request: No attribute named 'emailId     98 (12.00%)
s' is defined 
> jsonPath($.methodResponses[0][1].state).find.exists, found not     78 ( 9.55%)
hing
> mailboxChanges: Failed to build request: No attribute named 'm     41 ( 5.02%)
ailboxState' is defined 
> jsonPath($.methodResponses[0][1].created).find.exists, found n     28 ( 3.43%)
othing
> jsonPath($.methodResponses[0][1].ids[*]).findAll.exists, found     28 ( 3.43%)
 nothing
> emailQuery: Failed to build request: No attribute named 'accou     26 ( 3.18%)
ntId' is defined 
> markAsSeen: Failed to build request: No attribute named 'email     24 ( 2.94%)
Ids' is defined 
> emailQuery: Failed to build request: No attribute named 'rando     20 ( 2.45%)
mMailbox' is defined 
> jsonPath($.methodResponses[0][1].newState).find.exists, found      18 ( 2.20%)
nothing
> emailGet: Failed to build request: No attribute named 'account     16 ( 1.96%)
Id' is defined 
> jsonPath($.methodResponses[0][1].list[?(@.role == 'inbox')].id     14 ( 1.71%)
).find.exists, found nothing
> submitEmails: Failed to build request: No attribute named 'dra     13 ( 1.59%)
ftMailboxId' is defined 
> getMailboxes: Failed to build request: No attribute named 'acc     11 ( 1.35%)
ountId' is defined 
> status.find.is(200), but actually found 500                        10 ( 1.22%)
> emailGetState: Failed to build request: No attribute named 'ac     10 ( 1.22%)
countId' is defined 
> mailboxChanges: Failed to build request: No attribute named 'a      6 ( 0.73%)
ccountId' is defined 
> emailChanges: Failed to build request: No attribute named 'acc      6 ( 0.73%)
ountId' is defined 
> markAsFlagged: Failed to build request: No attribute named 'em      4 ( 0.49%)
ailIds' is defined 
> markAsAnswered: Failed to build request: No attribute named 'e      4 ( 0.49%)
mailIds' is defined 
> markAsSeen: Failed to build request: No attribute named 'accou      3 ( 0.37%)
ntId' is defined 
> emailChanges: Failed to build request: No attribute named 'ema      3 ( 0.37%)
ilState' is defined 
> submitEmails: Failed to build request: No attribute named 'acc      3 ( 0.37%)
ountId' is defined 
```

## Scenario
- 1 pod
```
export DURATION=15
export USER_COUNT=5000
```
- Env: sandbox
gatling:testOnly org.apache.james.gatling.simulation.jmap.rfc8621.PushPlatformValidationSimulation

**Comment by quantranhong1999** [comment]
any error logs? May come from libraries upgrade you are testing?

**Comment by vttranlina** [comment]
> May come from libraries upgrade you are testing?

KO with `linagora/tmail-backend:distributed-branch-master`

**Comment by vttranlina** [comment]
> linagora/tmail-backend:distributed-branch-master

DIGEST:sha256:4bc2ed08c05e4fca272108ccbdc7a1553c985c0dab6aa00b7eaeb0f0af8e5a64
https://registry.hub.docker.com/layers/linagora/tmail-backend/distributed-branch-master/images/sha256-4bc2ed08c05e4fca272108ccbdc7a1553c985c0dab6aa00b7eaeb0f0af8e5a64?context=explore

**Comment by vttranlina** [comment]
> any error logs? 

https://grafana.stg.lin-saas.com/d/logs-saas-emaily-staging/application-logs?orgId=1&var-datasource=logs-saas-emaily-staging&var-app=sandbox%2Ftmail&var-search=ERROR&from=1690477200000&to=1690563599000

Almost is cassandra `DriverTimeoutException`

**Comment by quantranhong1999** [comment]
> > linagora/tmail-backend:distributed-branch-master
> 
> DIGEST:sha256:4bc2ed08c05e4fca272108ccbdc7a1553c985c0dab6aa00b7eaeb0f0af8e5a64 https://registry.hub.docker.com/layers/linagora/tmail-backend/distributed-branch-master/images/sha256-4bc2ed08c05e4fca272108ccbdc7a1553c985c0dab6aa00b7eaeb0f0af8e5a64?context=explore

No I mean Git commit. The master branch docker image would easily be overridden upon a new commit being merged on master.

**Comment by vttranlina** [comment]
> No I mean Git commit. The master branch docker image would easily be overridden upon a new commit being merged on master.

**Comment by vttranlina** [comment]
Git commit: c97a59142a368657d12e821664b82cdebe86759d

**Comment by vttranlina** [comment]
resolve https://github.com/apache/james-project/pull/1659
