### ISSUE TITLE
API to update attendance

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-backend#776]
Write a `AttendanceStatusUpdate/send` API

Takes a guid of the event + all info needed to compose the update ics. 

Sends an update ics by mail to the organiser.

Cc @Arsnael @hoangdat

**Comment by chibenwa** [comment]
Todo api proposal...

**Comment by Arsnael** [comment]
Gonna have to be a bit more precise first... JMAP method I would guess, correct?

First look it looks potentially complex (getting infos of the event to recreate an ics on our own with just updating a status attendance) for not adding (IMO) much value to TMail.

Do you need to only update the status attendance of somebody to the creator of the event only, or all participants as well?

Is it expected to have an option to turn this off for a user?

And who is asking for that? Is that really necessary? How "urgent" is this?

**Comment by quantranhong1999** [comment]
Are we wanting the email notification feature (when someone accepts/rejects an event) as the same as OpenPaaS Calendar, but for TMail itself?

But what I do not get is that: normally users should already have the option to accept/reject the event right in the mail, with the call to the original Calendar. -> Then why do we need this feature for TMail?

**Comment by chibenwa** [comment]
Edit: mobile team found a hack: locate buttons in the emai body and duplicate them.

Should be good enough for now.
