### ISSUE TITLE
Settings: User rename + User deletion

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/tmail-backend#780]
- Upon changing username: we should migrate their settings
- Upon user deletion: we should delete their settings

DoD: Unit tests + Integration tests + documentation

**Comment by VarunEnishetty** [comment]
@quantranhong1999 , I would like to work on this issue.
Can you please assign this task to me.

**Comment by chibenwa** [comment]
@VarunEnishetty sure.

It depends on the settings API, we will ping you when it is available and provide more info might you need it.

**Comment by VarunEnishetty** [comment]
@chibenwa sure, thanks

**Comment by quantranhong1999** [comment]
Hi @VarunEnishetty, the settings API is ready: https://github.com/linagora/tmail-backend/pull/790

You can start the work on this ticket if you want. If you need any guidance, do not hesitate to ask :-)

**Comment by quantranhong1999** [comment]
Hi @VarunEnishetty, any progress on this?

Just so you know, this task belongs to our current sprint. If you do not have any feedback this week, we may need to tackle it ourselves.

**Comment by VarunEnishetty** [comment]
Hi @quantranhong1999,
Sadly, I couldn't make much progress on this ticket yet due to other commitments. Please let me know if I can still proceed further with this ticket.

**Comment by quantranhong1999** [comment]
> Sadly, I couldn't make much progress on this ticket yet due to other commitments. Please let me know if I can still proceed further with this ticket.

No problem. You still can start this ticket if you want. Do not hesitate to ask questions or open a draft PR so we can better help you :)

**Comment by VarunEnishetty** [comment]
@quantranhong1999 , Followed steps from README to build the project and observed compilation errors for James-project module and couldn't find any troubleshooting steps.
Attaching logs for reference. Could you please assist me in resolving this issue
[consoleoutput.log](https://github.com/linagora/tmail-backend/files/12541870/consoleoutput.log)

**Comment by quantranhong1999** [comment]
> Attaching logs for reference. Could you please assist me in resolving this issue
[consoleoutput.log](https://github.com/linagora/tmail-backend/files/12541870/consoleoutput.log)

Did you compile our project using Java 17 (required)? Anyway your error seems you can not get/download the `artemis-commons-2.29.0.jar` properly. Maybe network issue?

**Comment by quantranhong1999** [comment]
For the user data deletion part, we are likely missing an API rf: https://github.com/linagora/tmail-backend/issues/785#issuecomment-1709406857.

We would need to implement this API hereby.

**Comment by quantranhong1999** [comment]
> We would need to implement this API hereby.

I help you a bit by adding the needed API: https://github.com/linagora/tmail-backend/pull/810

**Comment by quantranhong1999** [comment]
Hi @VarunEnishetty, our sprint is ending in the coming days so our team will need to tackle this ticket before the deadline.

I hope it does not prevent you from contributing to our project (maybe in other tickets) :-)

**Comment by quantranhong1999** [comment]
https://github.com/linagora/tmail-backend/pull/812
