### ISSUE TITLE
 Capability object for JMAP Setting extension

### ISSUE THREAD

**Issue by vttranlina** [linagora/tmail-backend#783]
## Epic 
https://github.com/linagora/tmail-backend/issues/630

Define the new capability "com:linagora:params:jmap:settings"

```
val LINAGORA_SETTING_EXTENSION: CapabilityIdentifier = "com:linagora:params:jmap:settings"
```
and guice binding it to `CapabilityFactory`

## DOD
- Write the integration test. We can add a new test in `LinagoraEchoMethodContract`

**Comment by vttranlina** [comment]
Example `Capability object for JMAP CalendarEvent/parse extension` https://github.com/linagora/tmail-backend/pull/580/files

**Comment by Arsnael** [comment]
cf https://github.com/linagora/tmail-backend/pull/793
