### ISSUE TITLE
Implement JMAP method Settings/set partial update

### ISSUE THREAD

**Issue by Arsnael** [linagora/tmail-backend#784]
After implementing #782, implement the /set partial update method (delat: add/remove single values)

**Request**

```
{
  "using": ["urn:ietf:params:jmap:core", "com:linagora:params:jmap:settings"],
  "methodCalls": [
    [
      "Settings/set",
      {
        "accountId": "29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6",
        "update": {
          "singleton": {
            "settings/language": "en",
            "settings/timezone": null
          }
        }
      },
      "c1"
    ]
}
```

**Response**

```
{
  "sessionState": "abcdefghij",
  "methodResponses": [
    ["Settings/set",
    {
      "accountId": "123",
      "oldState": "1",
      "newState": "1",
      "updated": {"singleton":{}}
    },
    "c1"]
}
```

**Notes**

* The json path for partial update is respecting the following format`settings/{my_conf}`
* Setting a value to null removes it from the Settings singleton object if it was previously present

**DoD**

Implementation + integration tests

**Comment by vttranlina** [comment]
`"settings/timezone": null` will remove the setting of `settings/timezone`? 
How we can different cases "null" and absent json property

**Comment by Arsnael** [comment]
That's how it's defined in the JMAP core specs

If you want a concrete example, https://jmap.io/spec-mail.html#emailsubmissionset => example section for emailsubmission/set:

```
[...]
"onSuccessUpdateEmail": {
    "#k1490": {
      "mailboxIds/7cb4e8ee-df87-4757-b9c4-2ea1ca41b38e": null,
      "mailboxIds/73dbcb4b-bffc-48bd-8c2a-a2e91ca672f6": true,
      "keywords/$draft": null
    }
  }
```

**Comment by Arsnael** [comment]
null means you dont define anything, it's as good as something being omitted, in JMAP

**Comment by quantranhong1999** [comment]
Question: We (at least until now) do not ban slash `/` usage in the configuration key. So how can we differentiate if e.g. `settings/whatever` is actually a configuration key or it is a partial update key?

**Comment by quantranhong1999** [comment]
Sorry, I did not read the spec yet but expect a quick answer from ones who know.
WHat do we do if a request has both full update and partial update entries?

```json
{
	"using": ["urn:ietf:params:jmap:core", "com:linagora:params:jmap:settings"],
	"methodCalls": [
		[
			"Settings/set",
			{
				"accountId": "29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6",
				"update": {
					"singleton": {
                                                // full update
						"settings": {
							"tdrive.attachment.import.enabled": "true",
							"firebase.enabled": "true",
							"timezone": "UTC+7",
							"appearance.theme": "dark",
							"language": "fr",
							"read.receipts.always": "false"
						},
                                                // partial update
						"settings/language": "en",
						"settings/timezone": null
					}
				}
			},
			"c1"
		]
	]
}
```

**Comment by Arsnael** [comment]
> Question: We (at least until now) do not ban slash `/` usage in the configuration key. So how can we differentiate if e.g. `settings/whatever` is actually a configuration key or it is a partial update key?

Maybe the fact that it starts by `settings/` ?

> WHat do we do if a request has both full update and partial update entries?

Good question... I believe https://jmap.io/spec-core.html#set has maybe the answer:

`There MUST NOT be two patches in the PatchObject where the pointer of one is the prefix of the pointer of the other, e.g., “alerts/1/offset” and “alerts”.`

I would say should be rejected.

Also for @vttranlina , on the same section, regarding null value set:

`If null, set to the default value if specified for this property; otherwise, remove the property from the patched object. If the key is not present in the parent, this a no-op.`

**Comment by chibenwa** [comment]
Forbid the use of `/` in `SettingsKey`

**Comment by vttranlina** [comment]
pr: https://github.com/linagora/tmail-backend/pull/808
