### ISSUE TITLE
Push for Settings

### ISSUE THREAD

**Issue by hungphan227** [linagora/tmail-backend#787]
**Original ticket:** https://github.com/linagora/tmail-backend/issues/630

**WHY**

Upon setting update, we need to push the change event to FCM

**HOW**

create SettingTypeName object (extend TypeName), push the event StateChangeEvent to the event bus after updating setting

**DoD**: pass contract test

Notes: need Settings/set method available.

**Comment by quantranhong1999** [comment]
add Setting Type -> push StateChangeEvent for Setting type.

**Comment by quantranhong1999** [comment]
https://github.com/linagora/tmail-backend/pull/809
