### ISSUE TITLE
Investigate why domain linagora.com is listed in URIBL.com black

### ISSUE THREAD

**Issue by vttranlina** [linagora/tmail-backend#802]
## How to re-produce
- Run the `RspamdScannerIntegrationContract` with domain `linagora.com`

Then the response from rspamd

```
        "URIBL_BLACK": {
            "name": "URIBL_BLACK",
            "score": 7.500000,
            "metric_score": 7.500000,
            "description": "A domain in the message is listed in URIBL.com black",
            "options": [
                "linagora.com:helo"
            ]
        },
        "MW_SURBL_MULTI": {
            "name": "MW_SURBL_MULTI",
            "score": 0.0,
            "metric_score": 5.500000,
            "description": "A domain in the message is listed in SURBL as malware",
            "options": [
                "linagora.com:helo"
            ]
        }
```

**Comment by Arsnael** [comment]
You talking about our testing suite here correct? Maybe I would check what are the blacklist files integrated (if any) with the version of rspamd we use for tests (maybe at that point in time we were blacklisted?). I don't think it fetches the latest ones available... 

Not impossible the conf might be a bit wrong on prod as well. I'm far from being a sys admin expert, just made it work, not sure it was the best way though.

**Comment by vttranlina** [comment]
> You talking about our testing suite here correct? 

yes, I detected it when running testing suite, But now I'm not sure it is just a temporary error or not, or it is just a local error.

**Comment by vttranlina** [comment]
@quantranhong1999  checked on the SURBL, URIBL homepage, it normal
![image](https://github.com/linagora/tmail-backend/assets/81145350/a2c8e450-dab6-42ba-a852-01b0ab8981c1)
![image](https://github.com/linagora/tmail-backend/assets/81145350/64da4f00-9fcd-406b-9529-fe525f18415c)

**Comment by Arsnael** [comment]
> > You talking about our testing suite here correct?
> 
> yes, I detected it when running testing suite, But now I'm not sure it is just a temporary error or not, or it is just a local error.

I mean we saw it in prod logs with benoit last thursday as well, but it was during a certain time window, then after that rspamd wasn't complaining anymore, and it wasn't blacklisted when we checked too. So I'm not too sure either.

**Comment by vttranlina** [comment]
I tried to update image to [3.6-r1-alpine3.18.3-r0](https://hub.docker.com/layers/a16bitsysop/rspamd/3.6-r1-alpine3.18.3-r0/images/sha256-878772518e9cf586fd73971adc387f6ec10b9f9215366e78b63cf281d46e9356?context=explore), but it was not fixed, 
Not understand the how rspamd work with surbl, uribl 
I will back later

____
Bonus: In case we want to disable surbl, uribl (for test?)
Create the `/etc/rspamd/local.d/surbl.conf`

```
rules {
    "SURBL_MULTI"{
    enabled = false;
    },
    "URIBL_MULTI"{
    enabled = false;
    },
}
```

**Comment by Arsnael** [comment]
> Bonus: In case we want to disable surbl, uribl (for test?)

We don't really use linagora.com addresses for tests so I don't really see the point.

I'm not sure why we get shortly blacklisted sometimes, but an action could do is : https://github.com/linagora/james-project-private/issues/703

**Comment by quantranhong1999** [comment]
We still should check this issue and try to get rid of the linagora domain out of the blacklist (if needed) IMO. Otherwise, other mail solutions using that blacklist/Rspamd could block our linagora mails.

**Comment by chibenwa** [comment]
Topic handled by IT:

It's a mis-configuration of SMTP 2 GO. Apparently failures are transiant...
