### ISSUE TITLE
Grooming sprint 33

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/tmail-backend#816]

**Comment by Arsnael** [comment]
Content for next sprint:

- [[EPIC] Automations](https://github.com/linagora/tmail-backend/issues/631) 
- [Audit trail pour Apache JAMES](https://github.com/linagora/james-project/issues/4866)
- https://github.com/linagora/james-project/issues?q=is%3Aopen+is%3Aissue+label%3Acassandra
- https://github.com/linagora/james-project/issues/4873

**Comment by quantranhong1999** [comment]
Q: Should team members groom https://github.com/linagora/james-project/issues/4874?

**Comment by Arsnael** [comment]
Sure
