### ISSUE TITLE
Webadmin task for trash cleanup

### ISSUE THREAD

**Issue by Arsnael** [linagora/tmail-backend#821]
This would be useful to allow our frontend client to propose to users the feature of enabling automatic cleanup of their trash mailbox.

The frontend would use the JMAP settings feature to store trash cleanup settings on tmail backend following this format:

```
"trash.cleanup.enabled": "true", 
"trash.cleanup.period": "weekly"
```

The period can be weekly or monthly.

The webadmin task would:
- list all users
- filter on the ones that have the trash cleanup enabled via their jmap settings
- delete messages that are older than the defined period in the user's trash mailbox

If the settings are missing, we consider the feature being disabled.

Inject the task in the mailboxes path. The webadmin api call should look like something like this:

`POST http://ip:port/mailboxes?task=CleanupTrash`

**DoD**: Integration tests + webadmin doc + add in documented settings keys in jmap settings doc

**Comment by hungphan227** [comment]
Draft PR for basic structure https://github.com/linagora/tmail-backend/pull/829

**Comment by hungphan227** [comment]
PR https://github.com/linagora/tmail-backend/pull/829

**Comment by hungphan227** [comment]
@Rene could you show me the location of documents?

**Comment by Arsnael** [comment]
@hungphan227 

- webadmin doc: docs/modules/ROOT/pages/tmail-backend/webadmin.adoc
- jmap settings doc: docs/modules/ROOT/pages/tmail-backend/jmap-extensions/jmapSettings.adoc (last section `Documented setting keys`)
