### ISSUE TITLE
Webadmin task for inbox archival

### ISSUE THREAD

**Issue by Arsnael** [linagora/tmail-backend#823]
This would be useful to allow our frontend client to propose to users the feature of enabling automatic archival of their inbox.

The frontend would use the JMAP settings feature to store inbox archival settings on tmail backend following this format:

```
"inbox.archival.enabled": "true",
"inbox.archival.period": "monthly",
"inbox.archival.format": "yearly"
```

The period can be yearly or monthly.

The archival format will represent the structure of Archive folder. It can be:
- `single`: Everything is archived under one folder, the `Archive` one
- `yearly`: everything will be archived in subfolders representing years, eg 2021, 2022, 2023, ...
- `monthly`: the structure will be subfolders of years, like above, and in those year subfolders, there would be month subfolders.

For a more visual example on the front, cf https://github.com/linagora/tmail-flutter/issues/1326

The webadmin task would:
- list all users
- filter on the ones that have the inbox archival enabled via their jmap settings
- archive messages that are older than the defined period in the user's inbox following the specified format

If the settings are missing, we consider the feature being disabled.

Inject the task in the mailboxes path. The webadmin api call should look like something like this:

`POST http://ip:port/mailboxes?task=ArchiveInbox`

_Note_: if there is a change of format for archival in the settings, we only apply it for new messages to archive. Previously archived email do not change.

**DoD**: Integration tests + webadmin doc + add in documented settings keys in jmap settings doc

**Comment by quantranhong1999** [comment]
WIP: https://github.com/linagora/tmail-backend/pull/838
