### ISSUE TITLE
DAV bridge for the bluebar

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-backend#831]
## What

Today the TMail <=> Calendar link relies on OpenPaaS

We could implement a DAV bridge, impersonating use to add his events into calendar / contact. This would remove the "openPaaS" requirement for connecting TMail to calendar.

In a nutshell:
![dav-bridge drawio](https://github.com/linagora/tmail-backend/assets/6928740/6d455b4a-475a-43af-8053-e19685e21056)

**Comment by Arsnael** [comment]
Is that the job of the team now to work on calendar topics..?

**Comment by chibenwa** [comment]
For now it is some possible work for TwakeWorkPlace M1 milestone, yes, as it unlock other calendars than OpenPaaS.
