### ISSUE TITLE
Show the log of the request state whenever backend push to FCM

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-backend#832]
### Description of the bug
At the moment, frontend's user sometimes lost the notifications, maybe the problem come from some reasons
- rate limit of FCM.
- front-end notification handling.

As a front-end user, I want to see the log of the request when ever back-end call to FCM.
Information in the log: `sender's account id`, `receiver's account id`, and `message id`.

**Comment by hoangdat** [comment]
cc @chibenwa @Arsnael

**Comment by hoangdat** [comment]
Can you help us priority this issue?

**Comment by vttranlina** [comment]
> As a front-end user, I want to see the log of the request when ever back-end call to FCM.

It is a log in back-end side? And the frontend will access to grafana for see log?

**Comment by hoangdat** [comment]
> It is a log in back-end side? And the frontend will access to grafana for see log? @hoangdat

yes, when we debug the problem.

**Comment by Arsnael** [comment]
@hoangdat not a priority atm as we are note in advance on our sprint. Will see later

**Comment by vttranlina** [comment]
It looks more complicated than I think
We can only log the target AccountId, and UUIDState after FCM push is completed.
The `FirebasePushListener` and `MailboxChangeListener` are separate, and async. Can not log exactly the full your required info after pushing FCM

// 
Un related but how about FCM audit logging? https://firebase.google.com/support/guides/cloud-audit-logging/firebase-cloud-messaging

**Comment by hoangdat** [comment]
Thank you, I will check it

**Comment by hoangdat** [comment]
Hi team, we tried FCM audit logging, but it took too much effort on GCP things (too complicated to me), so please help Flutter team with the very simple log from back-end side.
Log for the case success and failure FCM request with the `state id` and `token`(I mean device token)

**Comment by Arsnael** [comment]
Not sure what that could bring... honestly  sometimes (but not always) I see notifications from my browser, saying something updated in the tmail background. Thinking likely FCM, but... I dont get any update, it feels like the app maybe receives notifications, but does nothing regarding it?

Prod, v0.10.4, Brave browser

**Comment by Arsnael** [comment]
Team is fully busy atm as well, and as Tung stated above, it's more complex as everything is async

**Comment by hoangdat** [comment]
I started to monitor the app from Tue -> now. Util 12.00PM Thursday, I can not receive any notification, both in mobile, browser. I'm considering more from the logic of handling expired time in `FCMRegistration` method. We have any way to dig more details on these things in Back-end side. This is kind of integration function, Front-end <-> Back-end <-> FCM <-> Front-end. If we can not debug the connection between them, we can not find the root cause.

**Comment by Arsnael** [comment]
I propose next week you set up at the office to sit down with Quan or Tung (with my foot I can't atm sorry) and maybe get Dat Vu invoilved too. It looks like a complex topic where we don't really know if we have an issue on backend or frontend or both with FCM, and we agreed in those cases we should take the time sitting together between both teams, as obviously throwing the ball back and forth between us is not working.

Agreed?

**Comment by hoangdat** [comment]
Totally agree.

**Comment by hoangdat** [comment]
Hi Back-end team, I found a problem:

### Desc:

1. I have an expired FCM registration with `deviceClientX`, I tried to use `FirebaseRegistration/get` to see the list of registration, but not found this in the response.
2. In this case, front-end will try to register new registration with `FirebaseRegistration/set` with the same `deviceClientX` but the response is
```
            "FirebaseRegistration/set",
            {
                "notCreated": {
                    "dab246": {
                        "type": "invalidArguments",
                        "description": "`deviceClientX` deviceClientId must be unique",
                        "properties": [
                            "deviceClientId"
                        ]
                    }
                }
            },
            "c1"
```

### Question:
- Why back-end don't "kill" the expired registration?

**Comment by vttranlina** [comment]
@backend team
We have an unfriendly design here, 
- list FCM subscription: don't return expired record
- destroy method: require `FirebaseSubscriptionId`  (NOT require deviceClientId)

If the client mobile doesn't store `FirebaseSubscriptionId`,  when they want to remove one, they can't

=> IMO we should return a list containing "expired" subscription

**Comment by Arsnael** [comment]
Happy to see that both teams sat together and found a related issue :) 

Or we could put a logic in place to delete on our side those expired subscriptions. Like if some arguments are not unique (like the device above), we check if it belongs to a subscription that is expired, if yes, we delete that sub, and we retry the initial request? If not (active sub) of course then we return an error.

I think it make sense because of our documentation actually on this: https://github.com/linagora/tmail-backend/blob/master/docs/modules/ROOT/pages/tmail-backend/jmap-extensions/pushWithFirebase.adoc

```
expires: UTCDate|null The time this push subscription expires. If specified, the JMAP server MUST NOT make further
requests to this resource after this time. It MAY automatically destroy the push subscription at or after this time.
```

**Comment by chibenwa** [comment]
> Or we could put a logic in place to delete on our side those expired subscriptions. 

+1

Silently deleting expired registration whenever meaningful should be ok.

Please team also look if James's WebPush is affected by a similar issue.

**Comment by quantranhong1999** [comment]
To summarize the little debug session, I propose 2 actions on the backend side:

- `FirebaseSubscription/get` should return expired subscriptions.
   -> So clients can list, extend the expires, or destroy the expired subscription if they want. Today there is no way client can control that cf: https://github.com/linagora/tmail-backend/issues/832#issuecomment-1842032222
   **Priority: high**. 
   It should fix the issue: https://github.com/linagora/tmail-backend/issues/832#issuecomment-1842021986

- Backend should clean expired subscriptions.
  **Priority: low**. 
  IMO this is a bonus as we keep the subscription table clean of dangling subscriptions.

TODO: create tickets.

**Comment by Arsnael** [comment]
Well it depends if we expect tmail front to manage its list of expired subscriptions or not :)

**Comment by quantranhong1999** [comment]
> Well it depends if we expect tmail front to manage its list of expired subscriptions or not :)

@hoangdat which way do you prefer? 

1. `/get` return expired subscriptions, and client `/set update` to extend the expired subscription.
2. `/get` does not return expired subscriptions, and client just `/set create` a new subscription with the same `deviceClientId`.

**Comment by hoangdat** [comment]
Hi @quantranhong1999, 
1 is ok for me.

**Comment by Arsnael** [comment]
@hoangdat I think @quantranhong1999 took the time to deploy that in staging. Did you take the time to check it yet?

**Comment by quantranhong1999** [comment]
> @hoangdat I think @quantranhong1999 took the time to deploy that in staging. Did you take the time to check it yet?

On that, we postponed the log need and focused on fixing other poping up issues first.

(the log could be deployed anytime though, whenever @hoangdat requires :-) )

**Comment by Arsnael** [comment]
> (the log could be deployed anytime though, whenever @hoangdat requires :-) )

Well yes pretty sure I saw it merged :)

**Comment by quantranhong1999** [comment]
> Well yes pretty sure I saw it merged :)

Not really for the FCM log. I just checked master. I did not fire a PR for that because it is more for debugging and should not always log the FCM push on prod (could be heavy), no?

**Comment by Arsnael** [comment]
I meant for the get returning expired subs :)

**Comment by hoangdat** [comment]
Yeah, I tried to test it, but the platform not really stable to test it some days ago. So not really to verify it.

**Comment by Arsnael** [comment]
Dont hesitate to get support from the back then. Sometimes multiple persons deploy different things at different time, for testing different stuff as well. Been chaotic lately.

If thursday you or dat vu have time, happy to have someone from the back sitting with you to help you check this if you need
