### ISSUE TITLE
[POSTGRES] Experiment r2dbc-pool library

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/tmail-backend#849]
https://github.com/r2dbc/r2dbc-pool

Connection Pooling for Reactive Relational Database Connectivity library.

Let's experiment with this lib to see if we can avoid inventing a Postgres connection pool ourselves.

**Comment by vttranlina** [comment]
reference [AbstractRoutingConnectionFactory](https://github.com/spring-projects/spring-data-r2dbc/blob/7ec3d28b17ef4c4a6c77b355c777cccf9519cb10/src/main/java/org/springframework/data/r2dbc/connectionfactory/lookup/AbstractRoutingConnectionFactory.java) in Spring r2dbc for routing tenant to connection. 
One difference is the number of tenants is fixed when initialing app

**Comment by vttranlina** [comment]
pr for comment https://github.com/apache/james-project/pull/1757

**Comment by vttranlina** [comment]
Postgres document 
```
The default is typically 100 connections, but might be less if your kernel settings will not support it (as determined during initdb). This parameter can only be set at server start.
```
=> My mind is pool size should be less than < 100. 

My concerns:
- If we "fixed" 1 domain has (0-1) connection -> Is it good for case concurrent users with the same domain?
- For each query to database, we need: (set session role attribute) -> (business query) -> (unset role when release connection)
So, we need 3 queries, it looks like not optimize

**Comment by chibenwa** [comment]
IMO let's start with `If we "fixed" 1 domain has (0-1) connection`

We could come up with other implementation of PGConProvider later.

**Comment by quantranhong1999** [comment]
> If we can go to 100+ tenant we are already ok for a bit of time.

100 maximum connections for Postgres can be configured. E.g. with a big Postgres we can configure it to 1000.

**Comment by chibenwa** [comment]
With which impact on performance?

**Comment by vttranlina** [comment]
My naive performance test on my laptop,
That is easy to set max_connection = 1000 


![Image](https://github.com/linagora/tmail-backend/assets/81145350/3de4b366-c7a1-4a3b-a17c-728d9a84a1f4)

Transaction per second was not big changed when changing from 1000 connections -> 100
