### ISSUE TITLE
[PRA] Starting without OpenSearch

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-backend#863]
https://issues.apache.org/jira/browse/JAMES-3959

**Comment by chibenwa** [comment]
CF https://github.com/linagora/james-project/issues/4922

**Comment by quantranhong1999** [comment]
No description for this.

I guess at least we need to integrate the work on OpenSearch into TMail.

How about backport for ElasticSearch, do we need that?

**Comment by quantranhong1999** [comment]
I was about to take this task. But Benoit assigned it, forget about this :p

**Comment by Arsnael** [comment]
> No description for this.

The description is in the JIRA linked above :)

**Comment by chibenwa** [comment]
Won't do as we do plan to DROP es-v6 support.

I'd rather work on making this happen...
