### ISSUE TITLE
Remove ES V 6 support

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-backend#864]
Remove all code related to ES-V6...

**Comment by Arsnael** [comment]
https://github.com/linagora/tmail-backend/pull/876

**Comment by chibenwa** [comment]
You gonna do the same with jmap-draft, do you?

**Comment by Arsnael** [comment]
Well I could :)

**Comment by vttranlina** [comment]
> You gonna do the same with jmap-draft, do you?

do it in James-project, right?

**Comment by chibenwa** [comment]
> do it in James-project, right?

Yes but likely beginning of January

**Comment by Arsnael** [comment]
Yes let's wait to remove openpaas inbox first
