### ISSUE TITLE
Email/query: Wrong response when sort by `From`

### ISSUE THREAD

**Issue by hieutbui** [linagora/tmail-backend#865]
### Description of the bug

- I found some weird response when send `Email/query` request with `sort` by property `from`.

##### Request
---
```
"sort": [
    {
    "isAscending": true,
    "property": "from"
    }
],
```

##### Response
---
- `Email/query` response in c0:

| id                                     | from.name |
| -------------------------------------- | --------- |
| "553745d0-7fe8-11ee-996f-0918932b7b81" | antoine   |
| "8e3f2560-7fe7-11ee-985b-438f415b959c" | David     |
| "df66c010-7fe7-11ee-996f-0918932b7b81" | Christin  |
| "234eefa0-7fe8-11ee-985b-438f415b959c" | Feddie    |
| "8fcc3890-7fe8-11ee-985b-438f415b959c" | Betrick   |
| "b4012c20-7fe8-11ee-996f-0918932b7b81" | Edgar     |

- `Email/get` response in c1:

| id                                     | from.name |
| -------------------------------------- | --------- |
| "b4012c20-7fe8-11ee-996f-0918932b7b81" | Edgar     |
| "553745d0-7fe8-11ee-996f-0918932b7b81" | antoine   |
| "df66c010-7fe7-11ee-996f-0918932b7b81" | Chirstin  |
| "234eefa0-7fe8-11ee-985b-438f415b959c" | Feddie    |
| "8fcc3890-7fe8-11ee-985b-438f415b959c" | Betrick   |
| "8e3f2560-7fe7-11ee-985b-438f415b959c" | David     |

##### Request
---
```
"sort": [
    {
    "isAscending": false,
    "property": "from"
    }
],
```
##### Response
---
- `Email/query` response in c0:

| id                                     | from.name |
| -------------------------------------- | --------- |
| "553745d0-7fe8-11ee-996f-0918932b7b81" | antoine   |
| "df66c010-7fe7-11ee-996f-0918932b7b81" | Chrinstin |
| "8e3f2560-7fe7-11ee-985b-438f415b959c" | David     |
| "234eefa0-7fe8-11ee-985b-438f415b959c" | Feddie    |
| "8fcc3890-7fe8-11ee-985b-438f415b959c" | Betrick   |
| "b4012c20-7fe8-11ee-996f-0918932b7b81" | Edgar     |

- `Email/get` response in c1:

| id                                     | from.name |
| -------------------------------------- | --------- |
| "b4012c20-7fe8-11ee-996f-0918932b7b81" | Edgar     |
| "553745d0-7fe8-11ee-996f-0918932b7b81" | antoine   |
| "df66c010-7fe7-11ee-996f-0918932b7b81" | Christin  |
| "234eefa0-7fe8-11ee-985b-438f415b959c" | Feddie    |
| "8fcc3890-7fe8-11ee-985b-438f415b959c" | Betrick   |
| "8e3f2560-7fe7-11ee-985b-438f415b959c" | David     |

### Reproduction Steps

- Send a request with `sort.property` is "from" and `sort.isAscending` is true or false

#### Sort by `From` with `Ascending`

| id                                     | from.name |
| -------------------------------------- | --------- |
| "553745d0-7fe8-11ee-996f-0918932b7b81" | antoine   |
| "8fcc3890-7fe8-11ee-985b-438f415b959c" | Betrick   |
| "df66c010-7fe7-11ee-996f-0918932b7b81" | Christin  |
| "8e3f2560-7fe7-11ee-985b-438f415b959c" | David     |
| "b4012c20-7fe8-11ee-996f-0918932b7b81" | Edgar     |
| "234eefa0-7fe8-11ee-985b-438f415b959c" | Feddie    |

#### Sort by `From` with `Descending`

| id                                     | from.name |
| -------------------------------------- | --------- |
| "234eefa0-7fe8-11ee-985b-438f415b959c" | Feddie    |
| "b4012c20-7fe8-11ee-996f-0918932b7b81" | Edgar     |
| "8e3f2560-7fe7-11ee-985b-438f415b959c" | David     |
| "df66c010-7fe7-11ee-996f-0918932b7b81" | Christin  |
| "8fcc3890-7fe8-11ee-985b-438f415b959c" | Betrick   |
| "553745d0-7fe8-11ee-996f-0918932b7b81" | antoine   |

### Context

- OS: Windows, Android
- Environment: Preprod server, jmap.linagora.com

### Additional information

- Full request and response file: [Sorting.md](https://github.com/linagora/tmail-backend/files/13388441/Sorting.md)
- Quick look in the UI:

https://github.com/linagora/tmail-backend/assets/80142234/844839ac-aa26-47f7-98e7-388a0d589e92

- To get what I am trying to do in the UI, Please check it:
https://github.com/linagora/tmail-flutter/pull/2322
https://github.com/linagora/tmail-flutter/pull/2318

**Comment by hieutbui** [comment]
@chibenwa @Arsnael I have some problems with the Email/query. Please check it!

**Comment by chibenwa** [comment]
What at the mail addresses?

**Comment by hieutbui** [comment]
> What at the mail addresses?

For case I mentioned, emailAddress are the same: firstname99.surname99@upn.integration-open-paas.org

**Comment by Arsnael** [comment]
Isn't that example a bit biased? In your video I can see that all those mails come from the same email address... with different names?

But yes we sort on the mail address, good point it's not fully compliant.

@chibenwa include in next sprint or not?

**Comment by chibenwa** [comment]
> @chibenwa include in next sprint or not?

I can take that one...

**Comment by chibenwa** [comment]
JIRA https://issues.apache.org/jira/browse/JAMES-3963 (catchall for search related topics)

**Comment by Arsnael** [comment]
apache: https://github.com/apache/james-project/pull/1811 (merged)

Need tmail-backend backport

**Comment by chibenwa** [comment]
> Need tmail-backend backport

I hesitate about that @Arsnael . It's a readindexing. So demands efforts.
Not really useful if we trash ESv6...

**Comment by Arsnael** [comment]
A upgrade james sha-1 on tmail then at least :)
