### ISSUE TITLE
Release tmail-backend 0.8.1

### ISSUE THREAD

**Issue by Arsnael** [linagora/tmail-backend#868]
- [x] Tag release 0.8.1-rc2 (needs a James sha-1 submodule upgrade first)
- [x] changelog
- [x] Upgrade rabbitmq on preprod to 3.12.10-management
- [x] deploy sandbox
- [x] perf tests
- [x] deploy preprod
- [x] QA tests
- [x] Tag final release 0.8.1
- [x] Update CNB prod deployment 
- [x] Update notion pages for tmail-backend release log and features tracking (https://www.notion.so/linagora/Back-end-s-release-note-cb529c89d588492aac5ba1f76c0cd494 and https://www.notion.so/linagora/Backend-features-support-2e077cb3f00443c9a8154f0fdc954daf)
- [x] Upgrade rabbitmq on prod to 3.12.10-management (?)
- [x] deploy prod

**Comment by Arsnael** [comment]
changelog: https://ci.linagora.com/linagora/lgs/software-linagora-com-website/-/merge_requests/48

NOTE: Might need to check https://github.com/linagora/james-project-private/issues/744 first before continuing this release process

**Comment by Arsnael** [comment]
preprod: https://ci.linagora.com/linagora/lrs/saas/deployments/tmail/emaily-staging-apps/-/merge_requests/24
CNB prod: https://ci.linagora.com/linagora/lrs/saas/deployments/cnb/cnb-prd-apps/-/merge_requests/3

sandbox: bunch of things were forgotten with sandbox (like ldap change conf). Need time to fix everything

**Comment by Arsnael** [comment]
sandbox: https://ci.linagora.com/linagora/lrs/saas/deployments/tmail/sandbox-emaily-apps/-/merge_requests/12

Fixed the ldap issues, deployed, it runs back to normal now

**Comment by Arsnael** [comment]
# Performance tests

## IMAP

### 0.8.0

![Image](https://github.com/linagora/tmail-backend/assets/9005025/cc3abf0e-394d-4d7b-bec5-f25004340419)

### 0.8.1

![Image](https://github.com/linagora/tmail-backend/assets/9005025/5d9891f0-e841-4b55-bad5-3265002f8baf)

Much better for some reason, dont believe we changed much things on imap though

## JMAP

Good to note that at first on a run with 6k users (like we did for previous release), got loads of websocket timeout when hitting 6k. However when trying again previous release, same issue. I guess related to ovh then. I redid runs with previous release and this one for jmap with 5k users

### 0.8.0

![Image](https://github.com/linagora/tmail-backend/assets/9005025/72a4a369-0afc-4928-9760-87b87467d17d)

### 0.8.1

![Image](https://github.com/linagora/tmail-backend/assets/9005025/e161f90e-c10f-4efe-bd2e-390ae97bcf7f)

Not much difference here, similar perfs.

**Comment by Arsnael** [comment]
Updated changelog

**Comment by Arsnael** [comment]
Updated notion pages

Asked QA to test new release on staging

**Comment by Arsnael** [comment]
On halt for now. Maybe fix for smtp smuggling vulnerability wasn't enough, @chibenwa will take the time to check it deeper. Might need an other cycle, 0.8.1-rc3 (but with little activity these days on master branch, changes should be minimal)

**Comment by chibenwa** [comment]
FYI I opened https://github.com/apache/james-project/pull/1890 on James side...

**Comment by Arsnael** [comment]
jmx auth and smtp smuggling have been fixed and merged on master (thank you @chibenwa ). I will resume the release with a new cycle

**Comment by Arsnael** [comment]
Tag 0.8.1-rc3 done

Deployed on tenant-upn: https://ci.linagora.com/linagora/lrs/saas/deployments/tmail/emaily-staging-apps/-/merge_requests/25
Deployed on sandbox: https://ci.linagora.com/linagora/lrs/saas/deployments/tmail/sandbox-emaily-apps/-/merge_requests/13

Will not redo perf tests as it's mainly just small jmx and smtp smuggling vulnerability fixes compared to previous one.
