### ISSUE TITLE
Backend should clean expired subscriptions

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/tmail-backend#871]
## Why

Sometimes, client does not manage to destroy expired FCM subscriptions. e.g. TMail frontend currently does not destroy subscriptions upon app uninstaller -> the subscription would expire eventually and keep being dangling in TMail backend database forever.

We should better clean expired FCM subscriptions. It is aligned with the JMAP specs: `It MAY automatically destroy the push subscription at or after this time.`

## How

IMO we can write a task `CleanExpiredFCMSubscriptions` and set up a cron job for it. 
That should be the cleanest way but take some cost to develop.

Otherwise, we can just scan and delete user's expired subscription whenever meaningful e.g. when Pushing notifications for User X, we can filter and delete the expired subscription. But this way can not clean subscriptions for inactive users.

## Notes
Do this for James's PushSubscription as well (may in other ticket).

**Comment by quantranhong1999** [comment]
> IMO we can write a task CleanExpiredFCMSubscriptions and set up a cron job for it.
That should be the cleanest way but take some cost to develop.

Clean this at James' startup (like what we did with Redis cleanup) may be better.

**Comment by chibenwa** [comment]
How about piggy backing sanitizing upon reads, which would be eventually consistent without a potentially expensive task to run?

**Comment by quantranhong1999** [comment]
> How about piggy backing sanitizing upon reads, which would be eventually consistent without a potentially expensive task to run?

From what I wrote in the ticket: `But this way can not clean subscriptions for inactive users.`
Yes, it should eventually clean up when those inactive users come back. But we are not 100% sure about that. Maybe some users create a bunch of subscriptions and don't come back.

**Comment by quantranhong1999** [comment]
https://github.com/linagora/tmail-backend/pull/1028

**Comment by chibenwa** [comment]
> But this way can not clean subscriptions for inactive users.

Is this an issue?

**Comment by chibenwa** [comment]
Also if I do not reboot james the cleanup at startup is not being run.

**Comment by chibenwa** [comment]
(it was ok for redis as rogue subscriptions as those were caused by James turning off...

**Comment by quantranhong1999** [comment]
Ok, fair to me. I would rework this.

**Comment by quantranhong1999** [comment]
James side: https://github.com/apache/james-project/pull/2234
