### ISSUE TITLE
[Postgres] TMail pg-app

### ISSUE THREAD

**Issue by Arsnael** [linagora/tmail-backend#883]
Based on the postgresql branch in James, implement an experimental postgresql app for TMail.

- Rebase apache/postgresql on apache/master
- Create a postgresql branch on tmail, based on apache/postgresql for james submodule
- Implement pg-app without the JMAP dependencies and tmail extra features for now
- Jenkinsfile => disable docker image generation for master and tags, only generate docker image for pg-app and tagging them as experimental (tmail-backend:postgresql-experimental?)

DoD: Green build for pg-app

**Comment by Arsnael** [comment]
Hmmmm... When I click on the james-project submodule on github in that branch, I get a 404... I feel like this is something local.

We should do the rebase on apache repo postgresql branch and depend directly on this here.

But I get it that you do not have the rights to do that on apache james project. I will try to support on that today

**Comment by vttranlina** [comment]
yep, I'm testing something with CI
I'm also going to request a rebase apache/master on apache/postgresql after it passed

**Comment by vttranlina** [comment]
CI green https://github.com/linagora/tmail-backend/pull/892
@Arsnael can you rebase apache/master to  apache/postgresql?
