### ISSUE TITLE
Add a IsTeamMailbox matcher

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-backend#884]
### Why

I want to avoid forwarding team mailboxes to OBM-UI mail servers, 
so that local recipients can receive / send emails to team mailboxes.

### How

For this a `IsTeamMailbox` matcher is needed.

**Comment by chibenwa** [comment]
CF https://github.com/linagora/tmail-backend/pull/885

**Comment by Arsnael** [comment]
I feel like we should not do the loop at all anymore for all mails regarding local recipients and not just team mailboxes but... why not :)
