### ISSUE TITLE
No need to check links in discovery ecosystem endpoint

### ISSUE THREAD

**Issue by Arsnael** [linagora/tmail-backend#887]
From https://github.com/linagora/tmail-flutter/issues/2425

Not necessary to make the code so strict about links present in `{jmapEndpoint}/.well-known/linagora-ecosystem`

Need to add two links in the endpoint `{jmapEndpoint}/.well-known/linagora-ecosystem`. Relax this, no need to check those. This endpoint is more info endpoint, nothing critical about it.

**Comment by chibenwa** [comment]
Isn't it just configuration?

**Comment by chibenwa** [comment]
Fffffff

I'd prefer an Open key value configuration without to much checks / restrictions in order to be more flexible...

**Comment by Arsnael** [comment]
Agreed. Don't even remember why we were so strict on that... I think the ticket is still valid, but with a different task: we don't check the links in the file

**Comment by Arsnael** [comment]
https://github.com/linagora/tmail-backend/pull/891
