### ISSUE TITLE
[Story] [Postgresql] Integrate JMAP and other features to TMail pg-app

### ISSUE THREAD

**Issue by Arsnael** [linagora/tmail-backend#888]
After the JMAP implementation on postgres is done on James side, we need to do it on TMail side. That requires:
- rebase on latest james postgresql branch with jmap implementation
- binding pg-app with JMAP James modules
- implementing all JMAP and other extra features in TMail for postgres and do guice bindings for pg-app

Topic to be groomed.

**Comment by chibenwa** [comment]
And we also need to list datastructure of TMail that would need to be implemented with PGSQL...

**Comment by hungphan227** [comment]
List of tasks: 
- JMAP guice bindings for postgres
- implement PostgresFirebaseSubscriptionRepository
- implement PostgresLabelChangeRepository
- implement PostgresLabelRepository
- implement PostgresJmapSettingsRepository
- implement PostgresTicketStore
- implement PostgresRateLimitingPlanRepository
- implement PostgresRateLimitingPlanUserRepository
- postgres jmap integration tests

**Comment by quantranhong1999** [comment]
Basic table structures (feel free to add not null constraints):

  + PostgresFirebaseSubscriptionRepository
  ```sql
  CREATE TABLE firebase_subscription (
    user TEXT,
    device_client_id TEXT,
    id UUID,
    expires TIMESTAMP,
    fcm_token TEXT,
    types TEXT[],
    PRIMARY KEY (user, device_client_id)
  );
  ```

 + PostgresLabelChangeRepository
   ```sql
   CREATE TABLE label_change (
    account_id TEXT,
    state UUID,
    created TEXT[],
    updated TEXT[],
    destroyed TEXT[],
    PRIMARY KEY (account_id, state)
   );
   ```

   Notes: need to handle row TTL (same as MaiboxChange and EmailChange concern), state column uses UUID v7

  + PostgresLabelRepository
  ```sql
  CREATE TABLE labels (
      user TEXT,
      keyword TEXT,
      display_name TEXT,
      color TEXT,
      PRIMARY KEY (user, keyword)
  );
  ```

  + PostgresJmapSettingsRepository
  ```sql
  CREATE TABLE jmap_settings (
    user TEXT,
    state UUID,
    settings HSTORE,
    PRIMARY KEY (user)
  );
  ```

  + PostgresTicketStore
  ```sql
  CREATE TABLE ticket (
    key UUID PRIMARY KEY,
    clientAddress TEXT,
    username TEXT,
    generatedOn TIMESTAMPTZ,
    validUntil TIMESTAMPTZ
  );
  ```

  Notes: TTL 120 second for record
  Question: Seems we do not really use TicketStore. Should we just bind memory implementation?

  + PostgresRateLimitingPlanRepository
  ```sql
  CREATE TABLE rate_limit_plan (
    plan_id UUID PRIMARY KEY,
    plan_name TEXT,
    operation_limitation_name TEXT,
    rate_limitations JSONB
  );
  ```

  + PostgresRateLimitingPlanUserRepository
  ```sql
  CREATE TABLE rate_limit_plan_user (
    username TEXT,
    plan_id UUID,
    PRIMARY KEY (username)
  );
  ```

  + PostgresBlobIdList
  (not sure what is used for TBH)
  ```sql
  CREATE TABLE blobId_list (
    blob_id TEXT PRIMARY KEY
  );
  ```

  + PostgresEncryptedEmailContentStore
  ```sql
  CREATE TABLE encrypted_email_content (
    message_id UUID PRIMARY KEY,
    encrypted_preview TEXT,
    encrypted_html TEXT,
    has_attachment BOOLEAN,
    encrypted_attachment_metadata TEXT,
    position_blob_id_mapping HSTORE
  );
  ```

  + PostgresKeystoreManager
  ```sql
  CREATE TABLE keystore (
    username TEXT,
    id TEXT,
    key BYTEA,
    PRIMARY KEY (username, id)
  );
  ```

**Comment by Arsnael** [comment]
List of features (not detailed):

- JMAP guice bindings from apache james
- BlobId list
- Combined user repository
- Encrypted mailbox
- RabbitMQ ScheduledReconnectionHandler
- Team mailboxes 
- TMail Rate Limiting
- TMail Contact autocomplete
- JMAP Labels
- smtp extension => TMailValidRcptHandler (needs team mailboxes)
- TMail extra mailets: needs contacts, team mailboxes, tmail rate limiting
- JMAP Firebase
- JMAP tickets auth (?)
- JMAP webfinger
- JMAP linagora services discovery
- JMAP forwards
- JMAP filtering rules
- JMAP deleted message vault
- JMAP settings
- Webadmin TMAIL extra routes

**Comment by Arsnael** [comment]
Notes from grooming session:

- PostgresLabelChangeRepository => need extra column `timestamp` to manage TTLs
- PostgresTicketStore => is this necessary? Tickets were for websockets initially but we see even in our gatling jmap simulation we use basic auth with websockets for example. Is it necessary to keep or should we remove it as a feature?

Table data structures with RLS:
- firebase_subscription
- labels
- jmap_settings
- ticket (?)
- rate_limit_plan_user
- keystore

Does label_change concerned about RLS or not?

- Combined user repository => bound by default already? (should double check)
- RabbitMQ ScheduledReconnectionHandler => recheck that (remember we did something similar on apache James to detect channel closure exceptions and reconnect to reconsume queues?)

**Comment by vttranlina** [comment]
> Combined user repository => bound by default already? (should double check)

We already have integration test for it https://github.com/linagora/tmail-backend/blob/cc340a36f05f3dd4c6744515d0d4d359fab0f249/tmail-backend/apps/postgres/src/test/java/com/linagora/tmail/james/app/CombinedIdentityTmailServerTest.java (postgres + ldap)

The mechanism is just set one `PostgresUserDAO` is instance of  `UsersDAO` in `CombinedUserDAO` https://github.com/linagora/tmail-backend/blob/c401c0547d86872201784308af062e077b498a4b/tmail-backend/combined-identity/src/main/java/com/linagora/tmail/combined/identity/CombinedUserDAO.java#L27

**Comment by Arsnael** [comment]
Hung's grooming:

- https://github.com/linagora/tmail-backend/issues/917
- https://github.com/linagora/tmail-backend/issues/916
- https://github.com/linagora/tmail-backend/issues/915
- https://github.com/linagora/tmail-backend/issues/914
- https://github.com/linagora/tmail-backend/issues/913
- https://github.com/linagora/tmail-backend/issues/912
- https://github.com/linagora/tmail-backend/issues/911
- https://github.com/linagora/tmail-backend/issues/910

I think it represents all the table data structures except blobIdList. However table data structures alone are not enough, might need extra implementation and/or bindings with related features

**Comment by quantranhong1999** [comment]
I added some more tickets:
- https://github.com/linagora/tmail-backend/issues/922
- https://github.com/linagora/tmail-backend/issues/918
- https://github.com/linagora/tmail-backend/issues/919
- https://github.com/linagora/tmail-backend/issues/920
- https://github.com/linagora/tmail-backend/issues/921

**Comment by vttranlina** [comment]
> smtp extension => TMailValidRcptHandler (needs team mailboxes)

We don't need a task for it, This class works with interfaces (we don't need more Postgres DAO for it). 
Pass the integration test is enough

**Comment by vttranlina** [comment]
> JMAP webfinger
> JMAP linagora services discovery

No need tasks for it,

**Comment by Arsnael** [comment]
At least not forgetting the guice bindings though for webfinger and lng service discovery modules? (yes i know it's just the matter of a few lines... but should not forget^^)

**Comment by vttranlina** [comment]
> JMAP deleted message vault

We already have a `PostgresDeletedMessageMetadataVault` in james-project.

**Comment by Arsnael** [comment]
Yes but it's via webadmin on james. On TMail we have a JMAP route that allows the user to ask himself for data recovery, without asking an admin to do it via webadmin, if my memory is correct :)

**Comment by Arsnael** [comment]
https://github.com/linagora/tmail-backend/issues/924 => to be sure to not forget all easy win guice bindings
