### ISSUE TITLE
[Notification iOS] Only set `alert` flag when we have EmailDelivery state in push payload

### ISSUE THREAD

**Issue by dab246** [linagora/tmail-backend#889]
## Issue

-  Notification Service Extension (NSE) must always display a notification every time it receives data from APN. So when we add the `alert` attribute at PR-[880](https://github.com/linagora/tmail-backend/pull/880), any change to the email will shoot data back. NSE.

## Expectation 

- [x] Only add `alert` and `mutableContent` attributes when there is an `EmailDelivery` state (That is, there is a new email)

- [x] Set text default for alert:

    - title: `Twake Mail`
    - body: `You have new message`

**Comment by Arsnael** [comment]
Thanks for the report! The team will take care of it

**Comment by quantranhong1999** [comment]
https://github.com/linagora/tmail-backend/pull/890
