### ISSUE TITLE
[Deleted message vault] Second `EmailRecoveryAction` recover same emails as first `EmailRecoveryAction`

### ISSUE THREAD

**Issue by hieutbui** [linagora/tmail-backend#893]
### Description of the bug

- Requested `EmailRecoveryAction` twice and emails recovered have different ids but same values: sender, receiver, subject, body.
- I don't know if it's a bug or the logic of `Deleted message vault`.

### `Email/query` to get recovered email after first `EmailRecoveryAction` completed:

- `EmailRecoveryAction` id: "9ecb9013-2a4a-4bbe-a151-3cde8224a9e0"

| email.id | Subject | From | To | Date | Body |
| ---- | ---- | ---- | ---- | ---- | ---- |
|3aaa3c40-af9f-11ee-8c33-4d3a6a31f3bb|Fadel LLC|firstname4258.surname4258|firstname2025|Wed, 27 Dec 2023 07:50:17 +0000|f049c45b-8bb9-4d8a-81cd-667d5fd03287|
|3a7cc3a0-af9f-11ee-8c33-4d3a6a31f3bb|Miss Rona Schmeler|firstname368|firstname2025|Wed,27 Dec 2023 08:14:25 +0000|a593bea8-6c39-4ef1-902b-4f6cf2e461f5|
|3a67dc10-af9f-11ee-8c33-4d3a6a31f3bb|Bean Shoots|firstname657|firstname2025|Wed, 27 Dec 2023 09:38:23 +0000|e6aa4f5b-65fc-4ab1-a185-42b6bef933fc|
|3a67b500-af9f-11ee-8c33-4d3a6a31f3bb|Benin|firstname3408|firstname2025|Wed, 27 Dec 2023 09:33:13 +0000|a38f9326-d217-4bb9-9e67-23c6833b4b61|
|3a659220-af9f-11ee-8c33-4d3a6a31f3bb|Bean Shoots|firstname657|firstname2025|Wed, 27 Dec 2023 09:38:23 +0000|e6aa4f5b-65fc-4ab1-a185-42b6bef933fc|

### `Email/query` to get recovered email after second `EmailRecoveryAction` completed:

- `EmailRecoveryAction` id: "30aaa590-b0cc-4160-919f-a9ca13813254"

| email.id | Subject | From | To | Date | Body |
| ---- | ---- | ---- | ---- | ---- | ---- |
|8577b5e0-af9f-11ee-8c33-4d3a6a31f3bb|Bean Shoots|firstname657|firstname2025|Wed, 27 Dec 2023 09:38:23 +0000|e6aa4f5b-65fc-4ab1-a185-42b6bef933fc|
|857719a1-af9f-11ee-8c33-4d3a6a31f3bb|Miss Rona Schmeler|firstname368|firstname2025|Wed,27 Dec 2023 08:14:25 +0000|a593bea8-6c39-4ef1-902b-4f6cf2e461f5|
|857719a0-af9f-11ee-8c33-4d3a6a31f3bb|Benin|firstname3408|firstname2025|Wed, 27 Dec 2023 09:33:13 +0000|a38f9326-d217-4bb9-9e67-23c6833b4b61|
|8576f290-af9f-11ee-8c33-4d3a6a31f3bb|Bean Shoots|firstname657|firstname2025|Wed, 27 Dec 2023 09:38:23 +0000|e6aa4f5b-65fc-4ab1-a185-42b6bef933fc|
|8576f291-af9f-11ee-8c33-4d3a6a31f3bb|Fadel LLC|firstname4258.surname4258|firstname2025|Wed, 27 Dec 2023 07:50:17 +0000|f049c45b-8bb9-4d8a-81cd-667d5fd03287|

### Reproduction Steps

- `Restored-messages` mailbox's id: "a30c6520-add2-11ee-98e6-1585191e78bd"

1. Send request `EmailRecoveryAction/set` with `create`
2. Send request `EmailRecoveryAction/get` with id of  `EmailRecovery` in step 2
3. Send request `Mailbox/changes` and `Mailbox/get` to fetch recovered email
4. Send request `EmailRecoveryAction/set` with `create`
5. Send request `EmailRecoveryAction/get` with id of  `EmailRecovery` in step 4
6. Send request `Mailbox/changes` and `Mailbox/get` to fetch recovered email. The emails response look like in step 3

### Expected result

- The second `EmailRecoveryAction` will return emails that not in first `EmailRecoveryAction`

### Context

- OS: Windows, Android
- Environment: Preprod, Producttion server

### Additional information

- Reproduction video:

https://github.com/linagora/tmail-backend/assets/80142234/f4aec53b-c41d-4361-bc49-c9bbb76e2687

- To get how I implement `EmailRecovery`:
https://github.com/linagora/tmail-flutter/pull/2396

- QA test report about `EmailRecovery` feature:
https://github.com/linagora/tmail-flutter/issues/2441

**Comment by chibenwa** [comment]
> I don't know if it's a bug or the logic of Deleted message vault.

It's the logic of the feature.

Messages are not removed from the vault, just copied from it.

It's nicer also in terms of privacy: to "list the vault, repeated "gimme last 5" requests would not be enough.
