### ISSUE TITLE
[CI build] Postgres experimental branch pushes also postgres image to docker hub on latest tag

### ISSUE THREAD

**Issue by Arsnael** [linagora/tmail-backend#903]
When merging code to the postgresql branch, the build on the CI is not only pushing the postgres-experimental image to dockerhub with that tag but also under latest.

We should fix that, it should only push it with one tag only: postgresql-experimental

**Comment by vttranlina** [comment]
https://github.com/GoogleContainerTools/jib/tree/master/jib-maven-plugin#extended-usage

**Comment by vttranlina** [comment]
pr https://github.com/linagora/tmail-backend/pull/904

**Comment by vttranlina** [comment]
Will close after the CI job is completed, and verify the result on dockerhub
https://james-jenkins.lin-saas.com/blue/organizations/jenkins/Tmail%20build/detail/postgresql/3/pipeline

**Comment by vttranlina** [comment]
completed 
<img width="1123" alt="image" src="https://github.com/linagora/tmail-backend/assets/81145350/7f78add4-02e6-45cc-ac3f-69f5342cf3ef">
https://hub.docker.com/r/linagora/tmail-backend/tags
