### ISSUE TITLE
Extension to display RTF?

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-backend#906]
### Why ?

Outlook 2007 do not uses HTML but `application/rtf` which cannot be displayed by TMail front.

### How ?

*Approach 1:* Mailet that rewrittes `application/rtf` into `text/html` ? => It would alter the message but will be way less invasive in the code. => Alters signatures (eg SMIME, PGP ?)

*Approach 2:* JMAP extension? Would need compute on each and every message read. Would be also harder to implement.
EG with a route `HTMLPart/parse`.

**Comment by Arsnael** [comment]
Outlook 2007 is old, support was ended in 2017 (6 years ago)... really we need to support a mail client that is completely obsolete?

**Comment by chibenwa** [comment]
Not a priority 

Merely a record TBH

;-)
