### ISSUE TITLE
[Postgresql] PostgresLabelChangeRepository

### ISSUE THREAD

**Issue by hungphan227** [linagora/tmail-backend#911]
## How
- Table structure:
```sql
CREATE TABLE label_change (
 account_id TEXT,
 state UUID,
 created TEXT[],
 updated TEXT[],
 destroyed TEXT[],
 created_date TIMESTAMP
 PRIMARY KEY (account_id, state)
);
```
Notes: need to handle row TTL (same as MaiboxChange and EmailChange concern), state column uses UUID v7

- need RLS

## DoD
Pass contract

**Comment by Arsnael** [comment]
DAO + PostgresLabelChangeRepository + Guice bindings

Write example script for TTL

**Comment by quantranhong1999** [comment]
https://github.com/linagora/tmail-backend/pull/961
