### ISSUE TITLE
[Postgresql] Implement PostgresLabelRepository

### ISSUE THREAD

**Issue by hungphan227** [linagora/tmail-backend#912]
## How
- Table structure:
```sql
CREATE TABLE labels (
    user TEXT,
    keyword TEXT,
    display_name TEXT,
    color TEXT,
    PRIMARY KEY (user, keyword)
);
```
- need RLS

## DoD
Pass contract

**Comment by quantranhong1999** [comment]
Can you add RLS (enable/disable) to the tickets' detail cf: https://github.com/linagora/tmail-backend/issues/888#issuecomment-1909296598 ?

**Comment by Arsnael** [comment]
DAO + PostgresLabelRepository + Guice bindings
