### ISSUE TITLE
[Postgres] JMAP memory binding for TMail app

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/tmail-backend#918]
## Why
The goal is to have a JMAP server backed by memory for TMail postgres-app. Then we can replace one by one with real Postgres implementation.

## How
Do it similarly to https://github.com/linagora/james-project/issues/5022
(Must admit I did not look in detail into the TMail modules yet...)

## DoD
`TMailPostgresJmapServerTest` passes the contract test `JmapJamesServerContract`.

**Comment by Arsnael** [comment]
Maybe couple with this? https://github.com/linagora/tmail-backend/issues/919

I think can probably put in place the IT tests even when pg-app on top of memeory jmap and when we imlement step by step pg jmap features, it should still stay green..?

**Comment by hungphan227** [comment]
pr https://github.com/linagora/tmail-backend/pull/957
