### ISSUE TITLE
Integration tests for TMail JMAP extensions

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/tmail-backend#919]
## Why
We need JMAP integration tests for JMAP backed by Postgres.

## How 
- create module `tmail-backend/integration-tests/jmap/postgres-jmap-integration-tests`.
- create ITs that implement contract tests in `tmail-backend/integration-tests/jmap/jmap-integration-tests-common`.
  Notes: DB should be backed by Postgres and not memory.

## DoD
Pass all contracts.

**Comment by vttranlina** [comment]
wip  pr https://github.com/linagora/tmail-backend/pull/992
