### ISSUE TITLE
Webadmin integration tests for TMail postgres-app

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/tmail-backend#920]
## Why
We should have webadmin integration tests for the postgres-app to make sure features that are exposed via webadmin function well.

## How
- introduce a module `tmail-backend/integration-tests/webadmin/postgres-webadmin-integration-tests`
- Implement contract tests from the `webadmin-integration-test-common` module, and other tests if relevant.
  Fix guice binding issues and bugs if any.

## DoD
Webadmin ITs green.

**Comment by Arsnael** [comment]
+ Guice bindings webadmin routes to TMail pg-app

**Comment by vttranlina** [comment]
pr https://github.com/linagora/tmail-backend/pull/984
