### ISSUE TITLE
[Postgres] Integration test for TMail additional features

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/tmail-backend#921]
## Why
We need to make sure additional features work well with the TMail postgres-app.

## How
Introduce modules and implement Postgres Integration tests for these features:
- Health check: `TMailHealthCheckIntegrationTests`
- Rate limiting: `RateLimitingPlanIntegrationContract`
- Rspamd: `RspamdScannerIntegrationContract`
- SMTP extension (related to team mailbox): `TeamMailboxSmtpContract`

May include additional Guice binding and bug fixes if any.

## DoD
ITs pass.

**Comment by hungphan227** [comment]
draft pr https://github.com/linagora/tmail-backend/pull/1001
