### ISSUE TITLE
[Postgresql] Implement PostgresBlobIdList

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/tmail-backend#922]
## How
- Table structure:
```sql
CREATE TABLE blobId_list (
  blob_id TEXT PRIMARY KEY
);
```
RLS disabled.

## DoD
`SingleSaveBlobStoreContract` backed by Postgres?

**Comment by Arsnael** [comment]
+ Guice bindings

**Comment by quantranhong1999** [comment]
https://github.com/linagora/tmail-backend/pull/988

**Comment by vttranlina** [comment]
sorry for rethinking it

I think we can re-use [PostgresBlobStorageTable](https://github.com/apache/james-project/blob/86337cadbf97f0a25a0ee4e12ded85cb0592dc47/server/blob/blob-postgres/src/main/java/org/apache/james/blob/postgres/PostgresBlobStorageModule.java#L35) directly
One index for the blob_id column is enough

The dedicated table `blobId_list` for Cassandra I guess comes from some limited query on single this column

**Comment by quantranhong1999** [comment]
Hmm the issue is we do not always use the Postgres blob implementation. We can use S3 for example.

**Comment by vttranlina** [comment]
> Hmm the issue is we do not always use the Postgres blob implementation. We can use S3 for example.

it makes sense
I forgot it
