### ISSUE TITLE
Display glitch

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-backend#931]
CNB prod: linagora/tmail-web:v0.11.3-patch4-3

![image](https://github.com/linagora/tmail-backend/assets/6928740/8322da02-1fd9-4149-8fb6-1c5499a27b93)

The guy used chome. Waiting for OS and screen settings.

I tried on my side:

![image](https://github.com/linagora/tmail-backend/assets/6928740/cf4893b7-333a-484c-8877-24631a6e25d7)

Was ok on chromium.

@QuangHoang1210  please have a look.

**Comment by chibenwa** [comment]
![image](https://github.com/linagora/tmail-backend/assets/6928740/794f165c-9c33-447c-ab54-0bc3256d9997)

Truncated text.

Set "french" and activate vacation responder.

**Comment by Arsnael** [comment]
@chibenwa Shouldn't that issue be on tmail-frontend side, and not backend? :)

**Comment by Arsnael** [comment]
Recreated it att he right place => https://github.com/linagora/tmail-flutter/issues/2629

Closing this.
