### ISSUE TITLE
Reduce a loooot the log volume of out apisix extensions

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-backend#935]
![Screenshot from 2024-02-23 22-08-54](https://github.com/linagora/tmail-backend/assets/6928740/dd8d1fd9-79df-45d0-b211-26bfaea63aa4)
![Screenshot from 2024-02-23 22-08-42](https://github.com/linagora/tmail-backend/assets/6928740/490aa3ff-8f8d-4a4d-9afd-58121031986c)

Might be good for DEV

Questionable on PROD...

Cc @vttranlina

**Comment by chibenwa** [comment]
Goal: by default I should only have the access log, unless something goes really wrong.

**Comment by chibenwa** [comment]
![image](https://github.com/linagora/tmail-backend/assets/6928740/8a04c406-db11-4880-9705-468388e67697)

200 logs per minute.

Where does this come from?

Is this necessary?

**Comment by vttranlina** [comment]
- https://github.com/linagora/tmail-backend/pull/940

- [ ] TODO, rebuild the image `linagora/apisix:3.2.0-debian-javaplugin` , and re-deploy on prod environment

**Comment by vttranlina** [comment]
> ![image](https://private-user-images.githubusercontent.com/6928740/307452353-8a04c406-db11-4880-9705-468388e67697.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5OTc2NDgsIm5iZiI6MTcwODk5NzM0OCwicGF0aCI6Ii82OTI4NzQwLzMwNzQ1MjM1My04YTA0YzQwNi1kYjExLTQ4ODAtOTcwNS00NjgzODhlNjc2OTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjdUMDEyOTA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjM1ODg3ODNkY2FiMzJkMTMwYzQ0ZTU2MWNiMDBhOTU5YTRkZGVlMjZhODczZjEyYzg3NGVlNmFlNGZjM2ExOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.YpLHFF7bQpqoOzbvF3RUwnsANmeLoa_wZixQMqqnFAI)
> 
> 200 logs per minute.
> 
> Where does this come from?
> 
> Is this necessary?

It appears that the client tried to call the "not found"'s url (here is `xxx/admin/xxx`). 

I couldn't find the `/admin` url in our apisix configuration file (docker-compose & helm emaily-staging-apps). 

WDYT? @ducnm0711 @Arsnael

**Comment by Arsnael** [comment]
Would need to have a deeper look, no idea for now

**Comment by vttranlina** [comment]
The pr for tmail plugin is merged

**Comment by Arsnael** [comment]
Can you explain why you closed, then reopened the issue to then unassign yourself @vttranlina ? Is this finished or not?

**Comment by vttranlina** [comment]
> Can you explain why you closed, then reopened the issue to then unassign yourself @vttranlina ? Is this finished or not?

When I merged the code pr, the `github-project-automation` auto closed it
But I think this task needs todo more. => re-opened manually



--- Why open?

As my note:
>  TODO, rebuild the image linagora/apisix:3.2.0-debian-javaplugin , and re-deploy on prod environment

I do not have permission to push dockerhub. 

And Benoit's question at: https://github.com/linagora/tmail-backend/issues/935#issuecomment-1961997071, no idea for now. (I guess it comes from production setup)

**Comment by ducnm0711** [comment]
https://github.com/apache/apisix-ingress-controller/issues/1855
Bug logged but no solution yet

**Comment by ducnm0711** [comment]
Workaround - change log level from into --> error
https://github.com/apache/apisix-helm-chart/blob/master/charts/apisix-ingress-controller/values.yaml#L79
```
  ingress-controller:
    config:
      logLevel: "error"
```
![image](https://github.com/linagora/tmail-backend/assets/59911858/a75fd201-590e-4996-8b2b-df94f129c4f4)
