### ISSUE TITLE
FCM user notifcations should not fail if "no longer existing types" stored on the DB

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/tmail-backend#958]
## Why
**GIVEN** at first TMail support a change type e.g. Thread, and user register updates for the Thread changes via `FirebaseSubscription/set`.
**WHEN** TMail gives up supporting the Thread change type
**THEN**:
- `FirebaseSubscription/get` likely would fail as `TypeStateFactory` fails to parse the Thread type from DB
- `FirebasePushListener` likely would fail as `TypeStateFactory` fails to parse the Thread type from DB

Expect: Should not fail if DB contains the "no longer existing types".

## How
Be more lenient in `TypeStateFactory`:  skip the parsing failure upon retrieval phase and a WARN level log cf: https://github.com/linagora/tmail-backend/pull/956#discussion_r1515814867

## Notes

Could contribute this to PushSubscription on James side if suitable...

**Comment by chibenwa** [comment]
Idem for PushSubscriptions / james push?

**Comment by quantranhong1999** [comment]
James side: https://github.com/apache/james-project/pull/2343

for postgres-app and FCM (on the TMail side) adoption: it could be done later as I introduced breaking change in the API so we would not forget to adapt.

**Comment by Arsnael** [comment]
Little james sha-1 upgrade on tmail-backend perhaps? :)

**Comment by quantranhong1999** [comment]
> Little james sha-1 upgrade on tmail-backend perhaps? :)

https://github.com/linagora/tmail-backend/pull/1126
