### ISSUE TITLE
[PGSQL] Adapt opensearch-disabled for Postgres distributed

### ISSUE THREAD

**Issue by vttranlina** [linagora/tmail-backend#994]
Based on Tmail distributed: https://github.com/linagora/tmail-backend/pull/902/files

But for Postgresql

## Dod: 

Pass `com.linagora.tmail.integration.postgres.PostgresUsernameChangeIntegrationTest#shouldAdaptContacts`

**Comment by vttranlina** [comment]
Commit for master: https://github.com/linagora/tmail-backend/pull/990/commits/a30cf2e666f105c1092e5e3c8e5cbfc4a35c6092
Commit for postgresql:  https://github.com/linagora/tmail-backend/pull/984/commits/161b69c3483ade10910a936224c109cf1919ef4d

**Comment by Arsnael** [comment]
Good catch. Why commits and not opened PRs though?

**Comment by vttranlina** [comment]
> Good catch. Why commits and not opened PRs though?

Created pr for that, pr 990, 984
The github auto change href link

![image](https://github.com/linagora/tmail-backend/assets/81145350/218186db-b4a5-4438-9c8a-87027e66c54d)

```
Commit for master: https://github.com/linagora/tmail-backend/pull/990/commits/a30cf2e666f105c1092e5e3c8e5cbfc4a35c6092
Commit for postgresql:  https://github.com/linagora/tmail-backend/pull/984/commits/161b69c3483ade10910a936224c109cf1919ef4d
```

**Comment by Arsnael** [comment]
Pushed in existing PRs I see :)
